
# This uses Madoko (https://madoko.codeplex.com/)

deck:
	madoko intro-tiny-fstar.mdk
	cp madoko2.css madoko.css

clean:
	rm -f *~ css.sty madoko.css madoko.sty *math-dvi.tex *math-pdf.tex *math-dvi.final.tex *math-pdf.final.tex  *.aux *.dim *.dvi *.log *.out *.upa *.dimx *.html *.log *.pdf *.upa *.upb *.bbl *.blg .*~
	rm -dfr math
