SUBDIRS += 1
SUBDIRS += 2
SUBDIRS += 3
SUBDIRS += 4

# Has a special makefile: it drives fstar.exe file by file.
SUBDIRS_ALL += 5
SUBDIRS_VERIFY += 5
SUBDIRS_CLEAN += 5

FSTAR_ROOT ?= ../..
include $(FSTAR_ROOT)/mk/test.mk
