type t = unit
type rid = unit
type ('a, 'b) rref = 'b ref
let root = ()
type ('a, 'b, 'c) fresh_region = unit
let extends a b = true
let as_ref i r = r
let sel _ = failwith "nope"
type ('a, 'b, 'c) modifies_one = unit
type ('a, 'b, 'c, 'd) modifies_rref = unit
type ('a, 'b, 'c, 'd, 'e) fresh_rref = unit
