; F* verification rules (generated in sibling Hello-gen/ dir)
(dynamic_include ../Hello-gen/deps.build.inc)

; Extraction: Custard compiles the whole program, starting from Hello, into
; one OCaml file.
(rule
 (targets Hello.ml)
 (deps Hello.fst Hello.fst.checked)
 (action (run %{env:FSTAR_EXE=fstar.exe} --include . --already_cached "*,"
   --codegen OCaml --custard_entry_module Hello -o Hello.ml Hello.fst)))

; Build the Hello executable from extracted OCaml
(executable
  (name Hello)
  (libraries fstar.lib)
  (preprocess (pps ppx_deriving_yojson))
  (flags (:standard -w -8-9-11-26-27-32-33-39)))
