module Pulse.Lib.ForEvery

#lang-pulse
open FStar.Fin
open FStar.Bijection
open FStar.Enumerable
open Pulse.Lib.Trade
open FStar.FunctionalExtensionality { (^->) }
module F = FStar.FunctionalExtensionality
open FStar.Tactics.Easy { easy }

let timeless_emp (v:slprop)
: Lemma
  (requires v==emp)
  (ensures timeless v)
  [SMTPat (timeless v)]
= let x = timeless_emp in ()

let forallm_tag #a ([@@@mkey] s: a -> prop) ([@@@mkey] p: a -> slprop)
    (f: (x:a { s x }) -> stt_ghost unit emp_inames emp (fun _ -> p x)) : timeless_slprop =
  emp

// A universal quantifier with no closure resource (i.e., timeless and duplicable)
let forallm #a ([@@@mkey] s: a -> prop) ([@@@mkey] p: a -> slprop) : timeless_slprop =
  exists* f. forallm_tag s p f

ghost
fn forallm_intro u#a
  (#a: Type u#a) (s: a -> prop) (p: a -> slprop)
  (f: (x:a { s x }) -> stt_ghost unit emp_inames emp (fun _ -> p x))
  ensures
    forallm s (fun x -> p x)
{
  fold forallm_tag s (fun x -> p x) f;
  fold forallm s (fun x -> p x);
}

ghost fn forallm_get_elim u#a (#a: Type u#a) (s: a -> prop) (p: a -> slprop)
  requires
    forallm s (fun x -> p x)
  returns
    f: ((x:a { s x }) -> stt_ghost unit emp_inames emp (fun _ -> p x))
{
  unfold forallm s (fun x -> p x);
  with f. assert forallm_tag s (fun x -> p x) f;
  unfold forallm_tag s (fun x -> p x) f;
  reveal f;
}

ghost
fn forallm_dup u#a (#a: Type u#a) (s: a -> prop) (p: a -> slprop) () : duplicable_f (forallm s (fun x -> p x)) = {
  let f = forallm_get_elim s p;
  forallm_intro s p f;
  forallm_intro s p f;
}
instance forallm_duplicable (#a: Type u#a) (s: a -> prop) (p: a -> slprop) : duplicable (forallm s (fun x -> p x)) =
  { dup_f = forallm_dup s p }

(*
We set up `forall+` as an inductively defined slprop generated by the following three constructors:
  | Empty: forall+ (x:a {False}). p x
  | Fill: forall* (pred add: a->prop).
      (forallm add p ** forall+ (x:a {pred x}). p x) @==>
        forall+ (x:a { pred x \/ add x }). p x
  | Insert: forall* (pred: a->prop) (y: a).
      (p y ** forall+ (x:a { pred x }). p x) @==>
        forall+ (x:a { pred x \/ x == y}). p x

Pulse does not have inductively defined predicates (yet?), so we simulate it by
defining an inductive shape type, and then defining the slprop by recursion on
that shape.

Later in the file we'll get the obvious definitions for this type:
  - `forevery_rec`: a recursor
  - `forevery_intro_false`: the constructor for Empty
  - `forevery_fill`: the constructor for Fill
  - `forevery_insert`: the constructor for Insert
*)

noextract noeq type shape =
  | Empty
  | Fill of shape
  | Insert of shape

let rec forevery_aux (#a: Type u#a) (p: a -> slprop) (s: shape) (mask: a -> prop) : slprop =
  match s with
  | Empty -> pure (forall x. ~(mask x))
  | Fill s -> exists* (pred: a -> prop).
    forallm pred (fun x -> p x) ** forevery_aux p s (fun x -> mask x /\ ~(pred x))
  | Insert s -> exists* y. p y ** pure (mask y) ** forevery_aux p s (fun x -> mask x /\ x =!= y)

let timeless_exists' (#a:Type u#a) (p: a -> slprop) (h: (x:a -> squash (timeless (p x)))) :
    squash (timeless (exists* x. p x)) =
  introduce forall x. timeless (p x) with h x;
  timeless_exists p

let rec timeless_forevery_aux (#a: Type u#a) (p: a -> timeless_slprop) (s: shape) (mask: a -> prop) :
    squash (timeless (forevery_aux p s mask)) =
  match s with
  | Empty -> ()
  | Fill s ->
    assert_norm (forevery_aux p (Fill s) mask ==
      exists* (pred: a -> prop).
        forallm pred (fun x -> p x) ** forevery_aux p s (fun x -> mask x /\ ~(pred x)));
    timeless_exists' (fun (pred: a -> prop) ->
        forallm pred (fun x -> p x) ** forevery_aux p s (fun x -> mask x /\ ~(pred x)))
      (fun pred -> timeless_forevery_aux p s (fun x -> mask x /\ ~(pred x)))
  | Insert s ->
    assert_norm (forevery_aux p (Insert s) mask ==
      exists* y. p y ** pure (mask y) ** forevery_aux p s (fun x -> mask x /\ x =!= y));
    timeless_exists' (fun y -> p y ** pure (mask y) ** forevery_aux p s (fun x -> mask x /\ x =!= y))
      (fun y -> timeless_forevery_aux p s (fun x -> mask x /\ x =!= y))

let (forall+) #a (p: a -> slprop) : slprop =
  exists* (s: shape). forevery_aux (fun x -> p x) s (fun x -> True)

let timeless_forevery #a (p: a -> slprop) :
    Lemma (requires forall x. timeless (p x))
      (ensures timeless (op_forall_Plus p))
      [SMTPat (timeless (op_forall_Plus p))] =
  assert_norm (op_forall_Plus p ==
    exists* (s: shape). forevery_aux (fun x -> p x) s (fun x -> True));
  timeless_exists' (fun (s: shape) -> forevery_aux (fun x -> p x) s (fun x -> True))
    (fun s -> timeless_forevery_aux _ _ _)

ghost
fn forevery_intro_empty (#a:Type0) (p: a -> slprop)
  requires
    pure (forall (x:a). False)
  ensures
    forall+ (x:a). p x
{
  fold forevery_aux (fun x -> p x) Empty (fun x -> True);
  fold forall+ (x:a). p x
}

ghost
fn forevery_elim_empty (#a:Type0) (p: a -> slprop)
  requires
    pure (forall (x:a). False)
  requires
    forall+ (x:a). p x
{
  drop_ (forall+ (x:a). p x);
}

ghost
fn forevery_intro_false (#a:Type0) (p: a -> slprop)
  ensures
    forall+ (x:a {False}). p x
{
  forevery_intro_empty (fun (x:a {False}) -> p x);
}

ghost
fn rec aux_mono
  (#a:Type0)
  (p: a -> slprop)
  (#f g: a -> prop)
  (s: shape)
  (#mask: (x:a{f x} -> prop))
  (mask': (x:a{g x} -> prop))
  requires
    forevery_aux #(x:a{f x}) (fun x -> p x) s mask
  requires
    pure (forall (x:a). f x ==> g x /\ (mask x <==> mask' x))
  requires
    pure (forall (x:a). ~(f x) /\ g x ==> ~(mask' x))
  ensures
    forevery_aux #(x:a{g x}) (fun x -> p x) s mask'
  decreases
    s
{
  match s {
    Empty -> {
      assert rewrites_to s Empty;
      unfold forevery_aux #(x:a{f x}) (fun x -> p x) Empty mask;
      fold forevery_aux #(x:a{g x}) (fun x -> p x) Empty mask';
    }
    Fill s' -> {
      assert rewrites_to s (Fill s');
      unfold forevery_aux #(x:a{f x}) (fun x -> p x) (Fill s') mask; with pred. _;
      let pred': (x:a{g x} -> prop) = (fun (x:a) -> f x /\ pred x);
      aux_mono #a p #f g s' #(fun (x:a{f x}) -> id (mask x /\ ~(pred x) <: prop))
        (fun (x:a{g x}) -> id (mask' x /\ ~(pred' x) <: prop));
      let h = forallm_get_elim #(x:a{f x}) pred p;
      forallm_intro #(x:a{g x}) pred' p fn x { h x };
      fold forevery_aux #(x:a{g x}) (fun x -> p x) (Fill s') mask';
    }
    Insert s' -> {
      assert rewrites_to s (Insert s');
      unfold forevery_aux #(x:a{f x}) (fun x -> p x) (Insert s') mask; with y. _;
      aux_mono #a p #f g s' #(fun (x:a{f x}) -> id (mask x /\ ~(eq2 #(x:a{f x}) x y) <: prop))
        (fun (x:a{g x}) -> id (mask' x /\ ~(eq2 #(x:a{g x}) x y) <: prop));
      fold forevery_aux #(x:a{g x}) (fun x -> p x) (Insert s') mask';
    }
  }
}

ghost
fn forevery_insert
  (#a: Type0)
  (#f: a->prop)
  (p: a -> slprop)
  (y: a)
  requires
    forall+ (x:a {f x}). p x
  requires
    p y
  requires
    pure (~(f y))
  ensures
    forall+ (x:a {f x \/ y == x}). p x
{
  unfold (forall+ (x:a {f x}). p x); with s. _;
  aux_mono (fun (x:a) -> p x) (fun x -> f x \/ y == x) s
    (fun x -> True /\ ~(eq2 #(x: a{f x \/ eq2 #a y x}) x y));
  fold forevery_aux #(x: a{f x \/ eq2 #a y x})
    (fun x -> p x) (Insert s) (fun x -> True);
  fold (forall+ (x:a {f x \/ y == x}). p x);
}

ghost
fn forevery_fill
  (#a: Type0)
  (#f: a->prop)
  (p: a -> slprop)
  (pred: a -> prop)
  (g: (x:a{pred x} -> stt_ghost unit emp_inames emp (fun _ -> p x)))
  requires
    forall+ (x:a {f x}). p x
  requires
    pure (forall x. pred x ==> ~(f x))
  ensures
    forall+ (x:a {f x \/ pred x}). p x
{
  unfold (forall+ (x:a {f x}). p x); with s. _;
  aux_mono (fun (x:a) -> p x) (fun x -> f x \/ pred x) s
    (fun x -> True /\ ~(pred x));
  forallm_intro #(x: a{f x \/ pred x}) pred (fun x -> p x) g;
  fold forevery_aux #(x: a{f x \/ pred x})
    (fun x -> p x) (Fill s) (fun x -> True);
  fold (forall+ (x:a {f x \/ pred x}). p x);
}

ghost
fn forevery_rw_type
  (a:Type0)
  (b:Type{a == b})
  (f : a -> slprop)
  requires
    forall+ (x:a). f x
  ensures
    forall+ (x:b). f x
{
  rewrite
    forall+ (x:a). f x
  as
    forall+ (x:b). f x
}

ghost
fn forevery_refine_ext'
  (#a: Type0)
  (#f g: a->prop)
  (#_ : squash (forall x. f x <==> g x))
  (p: (x:a{f x} -> slprop))
  requires
    forall+ (x:a {f x}). p x
  ensures
    forall+ (w:a {g w}). p w
{
  RefinementExtensionality.refext a f g;
  forevery_rw_type (x:a {f x}) (x:a {g x}) p;
}

ghost
fn forevery_refine_ext
  (#a: Type0)
  (#f g: a->prop)
  (p: a -> slprop)
  requires
    forall+ (x:a {f x}). p x
  requires
    pure (forall x. f x <==> g x)
  ensures
    forall+ (w:a {g w}). p w
{
  forevery_refine_ext' #a #f g p;
}

unfold let set_of #a (f: a->prop) = F.on_dom _ f
let set_ext #a (f g: a^->prop) : Lemma (requires forall x. f x <==> g x) (ensures f == g) =
  introduce forall x. f x == g x with PropositionalExtensionality.apply (f x) (g x);
  assert F.feq f g

ghost
fn rec aux_rec
  (#a: Type0)
  (p: a -> slprop)
  (#s: shape)
  (inv: (a -> prop) -> slprop)
  (ih_fill: (pred:(a -> prop) -> add:(a -> prop) { forall x. add x ==> ~(pred x) } ->
    f:((x:a { add x }) -> stt_ghost unit emp_inames emp (fun _ -> p x)) ->
    stt_ghost unit emp_inames (inv pred)
      (fun _ -> inv (set_of fun x -> pred x \/ add x))))
  (ih_insert: (pred:(a -> prop) -> x:a ->
    stt_ghost unit emp_inames (inv pred ** p x ** pure (~(pred x)))
      (fun _ -> inv (set_of fun y -> pred y \/ x == y))))
  (mask: a -> prop)
  requires
    forevery_aux #a p s mask
  requires
    inv (set_of fun _ -> False)
  ensures
    exists* (pred': a ^-> prop). inv pred' ** pure (forall x. pred' x <==> mask x)
  decreases s
{
  match s {
    Empty -> {
      unfold forevery_aux #a p Empty mask;
      set_ext (set_of fun _ -> False) (set_of mask);
      rewrite each set_of (fun (x:a) -> (False<:prop)) as (set_of mask);
    }
    Fill s' -> {
      unfold forevery_aux #a p (Fill s') mask; with pred. _;
      aux_rec p #s' inv ih_fill ih_insert (fun (x:a) -> id (mask x /\ ~(pred x) <: prop));
      with mask'. assert inv mask';
      assert pure (forall x. mask' x <==> mask x /\ ~(pred x));
      let h = forallm_get_elim #a pred p;
      ih_fill mask' (set_of fun x -> mask x /\ pred x) fn x { h x };
    }
    Insert s' -> {
      unfold forevery_aux #a p (Insert s') mask; with y. _;
      aux_rec p #s' inv ih_fill ih_insert (fun (x:a) -> id (mask x /\ x =!= y <: prop));
      with mask'. assert inv mask';
      ih_insert mask' y;
    }
  }
}

ghost
fn forevery_rec
  (#a: Type0)
  (p: a -> slprop)
  (inv: (a -> prop) -> slprop)
  (ih_fill: (pred:(a -> prop) -> add:(a -> prop) { forall x. add x ==> ~(pred x) } ->
    f:((x:a { add x }) -> stt_ghost unit emp_inames emp (fun _ -> p x)) ->
    stt_ghost unit emp_inames (inv pred)
      (fun _ -> inv (set_of fun x -> pred x \/ add x))))
  (ih_insert: (pred:(a -> prop) -> x:a ->
    stt_ghost unit emp_inames (inv pred ** p x ** pure (~(pred x)))
      (fun _ -> inv (set_of fun y -> pred y \/ x == y))))
  requires
    forall+ x. p x
  requires
    inv (set_of fun _ -> False)
  ensures
    inv (set_of fun _ -> True)
{
  unfold (forall+ (x:a). p x);
  aux_rec (fun x -> p x) inv ih_fill ih_insert _;
  with pred'. assert inv pred';
  set_ext pred' (set_of fun _ -> True);
  rewrite each pred' as set_of fun _ -> True
}

ghost
fn forevery_ext
  (#a:Type0)
  (f : a -> slprop)
  (g : a -> slprop { forall x. f x == g x })
  requires
    forall+ (x:a). f x
  ensures
    forall+ (x:a). g x
{
  rewrite (forall+ (x:a). f x) as (forall+ (x:a). g x)
}

ghost
fn forevery_ext_2
  (#a:Type0)
  (#b:Type0)
  (f : a -> b -> slprop)
  (g : a -> b -> slprop)
  requires
    pure (forall x y. f x y == g x y)
  requires
    forall+ (x:a) (y:b). f x y
  ensures
    forall+ (x:a) (y:b). g x y
{
  rewrite (forall+ (x:a) (y:b). f x y)
    as (forall+ (x:a) (y:b). g x y);
}

ghost
fn forevery_intro_pure (#a:Type0) (p: a -> prop)
  requires
    pure (forall x. p x)
  ensures
    forall+ x. pure (p x)
{
  forevery_intro_false (fun x -> pure (p x));
  forevery_fill
    #a
    #(fun _ -> False)
    (fun x -> pure (p x))
    (fun _ -> True)
    fn x {};
  forevery_rw_type (x:a{False \/ True}) a (fun x -> pure (p x));
}

ghost
fn forevery_map
  (#a:Type0)
  (p1 p2 : a -> slprop)
  (f : (x:a -> stt_ghost unit emp_inames (p1 x) (fun _ -> p2 x)))
  requires
    forall+ (x:a). p1 x
  ensures
    forall+ (x:a). p2 x
{
  forevery_intro_false p2;
  forevery_rec p1 (fun pred -> forall+ (x:a { pred x }). p2 x)
    fn pred add g { forevery_fill p2 add fn x { g x; f x } }
    fn pred x { f x; forevery_insert p2 x };
  forevery_refine_ext (fun _ -> True) p2;
}

ghost
fn forevery_intro_pure_2 (#a:Type0) (#b:Type0) (p: a -> b -> prop)
  requires
    pure (forall x y. p x y)
  ensures
    forall+ (x:a) (y:b). pure (p x y)
{
  forevery_intro_false (fun (x:a) -> forall+ (y:b). pure (p x y));
  forevery_fill
    #a
    #(fun _ -> False)
    (fun x -> forall+ (y:b). pure (p x y))
    (fun _ -> True)
    fn x { forevery_intro_pure #b (fun y -> p x y) };
  forevery_rw_type (x:a{False \/ True}) a (fun x -> forall+ (y:b). pure (p x y));
}

ghost
fn rewrite_cond_ext (p:prop) (s1 s2:slprop) (q:prop)
requires
  cond (t2b p) s1 s2
requires
  (pure (p <==> q))
ensures cond (t2b q) s1 s2
{
  rewrite cond (t2b p) s1 s2 as cond (t2b q) s1 s2
}

ghost
fn forevery_remove'
  (#a: Type0)
  (f: a->prop)
  (p: a -> slprop)
  (y: a { f y })
  requires
    forall+ (x:a {f x}). p x
  ensures
    forall+ (x:a {f x /\ x =!= y}). p x
  ensures
    p y
{
  forevery_intro_false p;
  intro_cond_false (p y) emp; rewrite each false as t2b False;
  forevery_refine_ext #_ #(fun _ -> l_False) (fun z -> f z /\ ~(z == y) /\ l_False) p;
  forevery_rec #(x:a{f x}) p (fun pred ->
      cond (t2b (pred y)) (p y) emp **
      forall+ (z:a { f z /\ z =!= y /\ pred z }). p z)
    fn pred add g {
      forevery_fill p (fun z -> f z /\ z =!= y /\ add z)
        fn x { g x };
      forevery_refine_ext (fun (z: a) -> f z /\ ~(eq2 #a z y) /\ (pred z \/ add z <: prop)) p;
      let b = t2b (add y);
      if b {
        elim_cond_false (t2b (pred y)) (p y) emp;
        g y;
        rewrite p y as cond (t2b (pred y \/ add y)) (p y) emp;
      } else {
        rewrite cond (t2b (pred y)) (p y) emp
        as cond (t2b (pred y \/ add y)) (p y) emp;
      }
    }
    fn pred x {
      let b = t2b (x == y);
      if b {
        assert rewrites_to y x;
        elim_cond_false (t2b (pred y)) (p y) emp;
        rewrite p x as cond (t2b (pred x \/ x == y)) (p y) emp;
        rewrite_cond_ext _ _ _ (pred x \/ eq2 #(x:a{f x}) x x);
        forevery_refine_ext (fun (z: a) -> f z /\ ~(z == y) /\ (pred z \/ eq2 #(x:a{f x}) x z)) p;
      } else {
        forevery_insert p x;
        forevery_refine_ext (fun (z: a) -> f z /\ ~(z == y) /\ (pred z \/ eq2 #(x:a{f x}) x z)) p;
        rewrite cond (t2b (pred y)) (p y) emp
        as cond (t2b (pred y \/ eq2 #(x:a{f x}) x y)) (p y) emp;
      }
    };
  forevery_refine_ext #_ #(fun z -> f z /\ ~(z == y) /\ l_True) (fun z -> f z /\ ~(z == y)) p;
  elim_cond_true _ (p y) emp;
}

ghost
fn forevery_remove
  (#a: Type0)
  (p: a -> slprop)
  (y: a)
  requires
    forall+ (x:a). p x
  ensures
    forall+ (x:a {x =!= y}). p x
  ensures
    p y
{
  forevery_remove' #a (fun _ -> True) p y;
  forevery_rw_type (x:a{True /\ x =!= y}) (x:a{x =!= y}) p;
  ()
}

ghost
fn forevery_intro_fill (#a: Type0) (p: a -> slprop)
  (f: (x:a -> stt_ghost unit emp_inames emp (fun _ -> p x)))
  ensures
    forall+ x. p x
{
  forevery_intro_false p;
  forevery_fill p (fun _ -> True) fn x { f x };
  forevery_rw_type (x:a{False \/ True}) a p;
}

ghost
fn forevery_unrefine
  (#a: Type0)
  (#f: a->prop)
  (p: a -> slprop)
  requires
    forall+ (x:a {f x}). p x
  requires
    pure (forall x. f x)
  ensures
    forall+ x. p x
{
  forevery_refine_ext (fun _ -> True) _;
}

ghost
fn forevery_singleton_intro'
  (#a:Type0)
  (p : a -> slprop)
  (x: a)
  requires
    pure (forall (y: a). x == y)
  requires
    p x
  ensures
    forall+ (x:a). p x
{
  forevery_intro_false p;
  forevery_insert p x;
  forevery_unrefine p;
}

ghost
fn forevery_singleton_elim'
  (#a:Type0)
  (p : a -> slprop)
  (x: a)
  requires
    pure (forall (y: a). x == y)
  requires
    forall+ (x:a). p x
  ensures
    p x
{
  forevery_remove p x;
  forevery_elim_empty (fun (y: a{~(y == x)}) -> p y);
}

ghost
fn forevery_refine_split
  (#a:Type0)
  (p: a -> slprop)
  (f: a -> prop)
  requires
    forall+ x. p x
  ensures
    forall+ (x:a{f x}). p x
  ensures
    forall+ (x:a{~(f x)}). p x
{
  forevery_intro_false p;
  forevery_intro_false p;
  forevery_rw_type (z:a{False}) (z:a{f z /\ False}) p;
  forevery_rw_type (z:a{False}) (z:a{~(f z) /\ False}) p;
  forevery_rec p
    (fun pred ->
      (forall+ (z:a{f z /\ pred z}). p z) **
      (forall+ (z:a{~(f z) /\ pred z}). p z))
    fn pred add g {
      forevery_fill #a #(fun z -> f z /\ pred z) p (fun z -> add z /\ f z) fn x { g x };
      forevery_fill #a #(fun z -> ~(f z) /\ pred z) p (fun z -> add z /\ ~(f z)) fn x { g x };
      forevery_refine_ext #a
        #(fun (x: a) -> f x /\ pred x \/ add x /\ f x)
        (fun (x: a) -> f x /\ (pred x \/ add x))
        p;
      forevery_refine_ext #a
        #(fun (x: a) -> ~(f x) /\ pred x \/ add x /\ ~(f x))
        (fun (x: a) -> ~(f x) /\ (pred x \/ add x))
        p;
    }
    fn pred x {
      let b = t2b (f x);
      if b {
        forevery_insert #a #(fun z -> f z /\ pred z) p x;
        forevery_refine_ext #a
          #(fun (z: a) -> (f z /\ pred z) \/ x == z)
          (fun (z: a) -> f z /\ (pred z \/ x == z))
          p;
        forevery_refine_ext #a
          #(fun (z: a) -> ~(f z) /\ pred z)
          (fun (z: a) -> ~(f z) /\ (pred z \/ x == z))
          p;
      } else {
        forevery_insert #a #(fun z -> ~(f z) /\ pred z) p x;
        forevery_refine_ext #a
          #(fun (z: a) -> (~(f z) /\ pred z) \/ x == z)
          (fun (z: a) -> ~(f z) /\ (pred z \/ x == z))
          p;
        forevery_refine_ext #a
          #(fun (z: a) -> (f z) /\ pred z)
          (fun (z: a) -> (f z) /\ (pred z \/ x == z))
          p;
      }
    };
  ();
  forevery_rw_type (z:a{f z /\ True})    (z:a{f z}) p;
  forevery_rw_type (z:a{~(f z) /\ True}) (z:a{~(f z)}) p;
}

ghost
fn forevery_refine_join
  (#a:Type0)
  (p: a -> slprop)
  (f g: a -> prop)
  requires
    forall+ (x:a{f x}). p x
  requires
    forall+ (x:a{g x}). p x
  requires
    pure (forall x. ~(f x /\ g x))
  ensures
    forall+ (x:a{f x \/ g x}). p x
{
  forevery_rw_type (x:a{g x}) (x:a{(f x /\ False) \/ g x}) p;
  forevery_rec #(x:a{f x}) p
    (fun pred ->
      forall+ (x:a{(f x /\ pred x) \/ g x}). p x)
    fn pred add h {
      forevery_fill p (fun z -> f z /\ add z) fn x { h x };
      forevery_refine_ext #a (fun x -> f x /\ (pred x \/ add x) \/ g x) p;
    }
    fn pred x {
      forevery_insert p x;
      forevery_refine_ext #a (fun z -> f z /\ (pred z \/ eq2 #(x:a{f x}) x z) \/ g z) p;
    };
  forevery_rw_type (x:a{(f x /\ True) \/ g x}) (x:a{f x \/ g x}) p;
  ();
}

ghost
fn forevery_refine_join'
  (#a:Type0)
  (f g: a -> prop)
  (p: (x:a{f x \/ g x}) -> slprop)
  requires
    forall+ (x:a{f x}). p x
  requires
    forall+ (x:a{g x}). p x
  requires
    pure (forall x. ~(f x /\ g x))
  ensures
    forall+ (x:a{f x \/ g x}). p x
{
  forevery_ext #(x:a{f x}) (fun x -> p x) (fun x -> when__ (f x \/ g x) (fun _ -> p x));
  forevery_ext #(x:a{g x}) (fun x -> p x) (fun x -> when__ (f x \/ g x) (fun _ -> p x));
  forevery_refine_join (fun x -> when__ (f x \/ g x) (fun _ -> p x)) f g;
  forevery_ext #(x:a{f x \/ g x}) (fun x -> when__ (f x \/ g x) (fun _ -> p x)) (fun x -> p x);
}

ghost
fn forevery_unrefine_pred
  (#a:Type0)
  (p: a -> slprop)
  (f: a -> prop)
  requires
    forall+ (x:a { f x }). p x
  ensures
    forall+ (x:a). when_ (f x) (p x)
{
  forevery_ext #(x:a { f x }) p (fun (x:a{f x}) -> when_ (f x) (p x));
  forevery_intro_fill (fun (x:a {~(f x)}) -> when_ (f x) (p x))
    fn x { rewrite emp as when_ (f x) (p x) };
  forevery_refine_join (fun x -> when_ (f x) (p x)) f (fun x -> ~(f x));
  forevery_unrefine (fun x -> when_ (f x) (p x));
}

ghost
fn forevery_unrefine_pred'
  (#a:Type0)
  (f: a -> prop)
  (p: (x:a -> squash (f x) -> slprop))
  requires
    forall+ (x:a { f x }). p x ()
  ensures
    forall+ (x:a). when__ (f x) (p x)
{
  forevery_ext #(x:a { f x }) (fun x -> p x ()) (fun (x:a{f x}) -> when__ (f x) (p x));
  forevery_intro_fill (fun (x:a {~(f x)}) -> when__ (f x) (p x))
    fn x { rewrite emp as when__ (f x) (p x) };
  forevery_refine_join (fun x -> when__ (f x) (p x)) f (fun x -> ~(f x));
  forevery_unrefine (fun x -> when__ (f x) (p x));
}

ghost
fn forevery_refine_pred
  (#a:Type0)
  (p: a -> slprop)
  (f: a -> prop)
  requires
    forall+ (x:a). when_ (f x) (p x)
  ensures
    forall+ (x:a { f x }). p x
{
  forevery_refine_split (fun x -> when_ (f x) (p x)) f;
  drop_ (forall+ (x:a { ~(f x) }). when_ (f x) (p x));
  forevery_ext (fun (x:a { f x }) -> when_ (f x) (p x)) (fun x -> p x);
}

ghost
fn forevery_unzip
  (#a:Type0)
  (p1 p2 : a -> slprop)
  requires
    forall+ (x:a). p1 x ** p2 x
  ensures
    (forall+ (x:a). p1 x) **
    (forall+ (x:a). p2 x)
{
  forevery_intro_false p1;
  forevery_intro_false p2;
  forevery_rec (fun x -> p1 x ** p2 x)
      (fun pred -> (forall+ (x:a{pred x}). p1 x) ** (forall+ (x:a{pred x}). p2 x))
    fn pred add f {
      forevery_fill p1 add fn x { f x; drop_ (p2 x) };
      forevery_fill p2 add fn x { f x; drop_ (p1 x) };
    }
    fn pred x {
      forevery_insert p1 x;
      forevery_insert p2 x;
    };
}

ghost
fn forevery_zip
  (#a:Type0)
  (p1 p2 : a -> slprop)
  requires
    (forall+ (x:a). p1 x) **
    (forall+ (x:a). p2 x)
  ensures
    forall+ (x:a). p1 x ** p2 x
{
  forevery_intro_false (fun x -> p1 x ** p2 x);
  forevery_rw_type a (x:a{~False}) p2;
  forevery_rec p1
    (fun pred ->
      (forall+ (z:a{pred z}). p1 z ** p2 z) **
      (forall+ (z:a{~(pred z)}). p2 z))
    fn pred add g {
      forevery_refine_split #(z:a{~(pred z)}) p2 (fun z -> add z);
      forevery_map #(x: (z: a{~(pred z)}){add x}) p2 (fun z -> p1 z ** p2 z)
        fn x { g x };
      forevery_refine_join (fun z -> p1 z ** p2 z)
        (fun z -> pred z) (fun z -> ~(pred z) /\ add z);
      forevery_refine_ext #a #(fun z -> pred z \/ ~(pred z) /\ add z)
        (fun z -> pred z \/ add z) (fun z -> p1 z ** p2 z);
      rewrite forall+ (x: (z: a{~(pred z)}){~(add x)}). p2 x
        as forall+ (z: a{~(pred z) /\ ~(add z)}). p2 z;
      forevery_refine_ext #a #(fun z -> ~(pred z) /\ ~(add z))
        (fun z -> ~(pred z \/ add z)) (fun z -> p2 z);
    }
    fn pred x {
      forevery_remove' (fun x -> ~(pred x)) p2 x;
      forevery_insert (fun x -> p1 x ** p2 x) x;
      forevery_refine_ext #a #(fun (z:a) -> ~(pred z) /\ (z =!= x))
        (fun (z:a) -> ~(pred z \/ x == z)) p2;
    };
  forevery_elim_empty (fun (x: a{~True}) -> p2 x);
  ();
}

ghost
fn forevery_zip3
  (#a:Type0)
  (p1 p2 p3 : a -> slprop)
  requires
    forall+ (x:a). p1 x
  requires
    forall+ (x:a). p2 x
  requires
    forall+ (x:a). p3 x
  ensures
    forall+ (x:a). p1 x ** p2 x ** p3 x
{
  forevery_zip p2 p3;
  forevery_zip p1 (fun x -> p2 x ** p3 x);
}

ghost
fn forevery_unzip3
  (#a:Type0)
  (p1 p2 p3 : a -> slprop)
  requires
    forall+ (x:a). p1 x ** p2 x ** p3 x
  ensures
    forall+ (x:a). p1 x
  ensures
    forall+ (x:a). p2 x
  ensures
    forall+ (x:a). p3 x
{
  forevery_unzip p1 (fun x -> p2 x ** p3 x);
  forevery_unzip p2 p3;
}

ghost
fn forevery_dup (#a: Type0) (p: a -> slprop) {| (x:a -> duplicable (p x)) |} ()
  : duplicable_f (forall+ (x: a). p x) =
{
  forevery_map p (fun x -> p x ** p x) fn x { dup (p x) () };
  forevery_unzip p p;
}

instance forevery_duplicable #a (p: a -> slprop) {| (x:a -> duplicable (p x)) |} :
  duplicable (forall+ (x: a). p x) = { dup_f = forevery_dup p }

ghost
fn forevery_iso
  (#a:Type0)
  (#b:Type0)
  (bij : a =~ b)
  (p : a -> slprop)
  requires
    forall+ (x:a). p x
  ensures
    forall+ (y:b). p (bij.left y)
{
  forevery_intro_false (fun y -> p (bij.left y));
  forevery_rec p (fun pred -> forall+ (y:b { pred (bij.left y) }). p (bij.left y))
    fn pred add g {
      forevery_fill (fun y -> p (bij.left y)) (fun z -> add (bij.left z))
        fn x { g (bij.left x) }
    }
    fn pred x {
      rewrite p x as p (bij.left (bij.right x));
      forevery_insert (fun y -> p (bij.left y)) (bij.right x);
      forevery_refine_ext (fun y -> pred (bij.left y) \/ x == bij.left y) (fun y -> p (bij.left y));
    }
}

let snd_bij #a #b (x: a) : (b =~ (xy: (a & b) { x == fst xy })) =
  {
    right = (fun y -> ((x,y) <: (xy: (a&b) {x == fst xy})));
    left = (fun xy -> snd xy);
    right_left = (fun _ -> ());
    left_right = (fun _ -> ());
  }

let snd_bij_dep #a (#b : a -> Type) (x: a) : (b x =~ (xy: (x:a & b x) { x == xy._1 })) =
  {
    right = (fun y -> ((|x,y|) <: (xy: (x:a & b x) {x == xy._1})));
    left = (fun xy -> xy._2);
    right_left = (fun _ -> ());
    left_right = (fun _ -> ());
  }

ghost
fn forevery_flatten
  (#a:Type0)
  (#b:Type0)
  (f : a -> b -> slprop)
  requires
    forall+ (x:a) (y:b). f x y
  ensures
    forall+ (xy : a & b). f xy._1 xy._2
{
  forevery_intro_false (fun (xy: a & b) -> f xy._1 xy._2);
  forevery_rec (fun x -> forall+ y. f x y)
    (fun pred -> forall+ (xy: a & b { pred (fst xy) }). f xy._1 xy._2)
    fn pred add g {
      forevery_fill (fun (xy: a & b) -> f xy._1 xy._2) (fun xy -> add xy._1)
        fn xy {
          g xy._1;
          forevery_remove (f xy._1) xy._2;
          drop_ (forall+ (x: b{~(x == xy._2)}). f xy._1 x);
        };
    }
    fn pred x {
      forevery_iso (snd_bij x) (f x);
      forevery_ext #(xy: (a & b){x == fst xy})
        (fun xy -> f x ((snd_bij x).left xy))
        (fun xy -> f xy._1 xy._2);
      forevery_refine_join #(a & b) (fun xy -> f xy._1 xy._2)
        (fun xy -> pred (fst xy))
        (fun xy -> x == fst xy);
    };
}

ghost
fn forevery_flatten_dep
  (#a : Type0)
  (#b : a -> Type0)
  (f : (x:a -> b x -> slprop))
  requires
    forall+ (x:a) (y:b x). f x y
  ensures
    forall+ (xy : (x:a & b x)). f xy._1 xy._2
{
  forevery_intro_false (fun (xy: (x:a & b x)) -> f xy._1 xy._2);
  forevery_rec (fun x -> forall+ y. f x y)
    (fun pred -> forall+ (xy: (x:a & b x) { pred xy._1 }). f xy._1 xy._2)
    fn pred add g {
      forevery_fill (fun (xy: (x:a & b x)) -> f xy._1 xy._2) (fun xy -> add xy._1)
        fn xy {
          g xy._1;
          forevery_remove (f xy._1) xy._2;
          drop_ (forall+ (y: (b xy._1){~(y == xy._2)}). f xy._1 y);
        };
    }
    fn pred x {
      forevery_iso (snd_bij_dep #a #b x) (f x);
      forevery_ext #(xy: (x:a & b x){x == xy._1})
        (fun xy -> f x ((snd_bij_dep x).left xy))
        (fun xy -> f xy._1 xy._2);
      forevery_refine_join #(x:a & b x) (fun xy -> f xy._1 xy._2)
        (fun xy -> pred xy._1)
        (fun xy -> x == xy._1);
    };
}

ghost
fn forevery_flatten'
  (#a:Type0)
  (#b:Type0)
  (f : a & b -> slprop)
  requires
    forall+ (x:a) (y:b). f (x, y)
  ensures
    forall+ (xy : a & b). f xy
{
  forevery_flatten (fun x y -> f (x, y));
  forevery_ext (fun (xy: a & b) -> f (xy._1, xy._2)) f;
}

ghost
fn forevery_unflatten
  (#a:Type0)
  (#b:Type0)
  (f : a -> b -> slprop)
  requires
    forall+ (xy : a & b). f xy._1 xy._2
  ensures
    forall+ (x:a) (y:b). f x y
{
  forevery_intro_fill (fun x -> forall+ (y:b{False}). f x y)
    fn x { forevery_intro_false (fun y -> f x y) };
  forevery_rec #(a&b) (fun xy -> f xy._1 xy._2)
    (fun pred -> forall+ (x:a) (y:b{ pred (x, y) }). f x y)
    fn pred add g {
      forevery_map
        (fun x -> forall+ (y:b { pred (x, y) }). f x y)
        (fun x -> forall+ (y:b { pred (x, y) \/ add (x, y) }). f x y)
        fn x {
          forevery_fill (f x) (fun y -> add (x, y)) fn y {
            g (x, y);
            with x' y'. rewrite f x' y' as f x y;
          };
        };
    }
    fn pred xy {
      forevery_singleton_intro' (fun (x: a { x == xy._1 }) -> f x xy._2) xy._1;
      forevery_unrefine_pred (fun x -> f x xy._2) (fun x -> x == xy._1);
      forevery_zip
        (fun x -> forall+ (y:b { pred (x, y) }). f x y)
        (fun x -> when_ (x == xy._1) (f x xy._2));
      forevery_map
        (fun x -> (forall+ (y: b{pred (x, y)}). f x y) ** when_ (x == xy._1) (f x xy._2))
        (fun x -> forall+ (y: b { pred (x, y) \/ xy == (x, y) }). f x y)
        fn x {
          let b = t2b (x == xy._1);
          if b {
            rewrite when_ (x == xy._1) (f x xy._2) as f x xy._2;
            forevery_insert (f x) xy._2;
            forevery_refine_ext (fun y -> pred (x, y) \/ xy == (x, y)) (f x);
          } else {
            rewrite when_ (x == xy._1) (f x xy._2) as emp;
            forevery_refine_ext (fun y -> pred (x, y) \/ xy == (x, y)) (f x);
          };
        };
    };
}

ghost
fn forevery_unflatten'
  (#a:Type0)
  (#b:Type0)
  (f : a & b -> slprop)
  requires
    forall+ (xy : a & b). f xy
  ensures
    forall+ (x:a) (y:b). f (x, y)
{
  forevery_ext f (fun (xy: a & b) -> f (xy._1, xy._2));
  forevery_unflatten (fun x y -> f (x, y));
}

ghost
fn forevery_unflatten_dep
  (#a : Type0)
  (#b : a -> Type0)
  (f : (x:a -> b x -> slprop))
  requires
    forall+ (xy : (x:a & b x)). f xy._1 xy._2
  ensures
    forall+ (x:a) (y:b x). f x y
{
  forevery_intro_fill (fun x -> forall+ (y:b x{False}). f x y)
    fn x { forevery_intro_false (fun y -> f x y) };
  forevery_rec #(x:a & b x) (fun xy -> f xy._1 xy._2)
    (fun pred -> forall+ (x:a) (y:b x{ pred (|x, y|) }). f x y)
    fn pred add g {
      forevery_map
        (fun x -> forall+ (y:b x { pred (|x, y|) }). f x y)
        (fun x -> forall+ (y:b x { pred (|x, y|) \/ add (|x, y|) }). f x y)
        fn x {
          forevery_fill (f x) (fun y -> add (|x, y|)) fn y {
            g (|x, y|);
            with x' y'. rewrite f x' y' as f x y;
          };
        };
    }
    fn pred xy {
      forevery_singleton_intro' (fun (x: a { x == xy._1 }) -> f x xy._2) xy._1;
      assert (forall+ (x:a{ x == xy._1 }). f x xy._2);
      forevery_unrefine_pred' #a (fun x -> x == xy._1) (fun (x:a) _ -> f x xy._2);
      forevery_zip
        (fun x -> forall+ (y:b x { pred (|x, y|) }). f x y)
        (fun x -> when__ (x == xy._1) (fun _ -> f x xy._2));
      forevery_map
        (fun x -> (forall+ (y: b x{pred (|x, y|)}). f x y) ** when__ (x == xy._1) (fun _ -> f x xy._2))
        (fun x -> forall+ (y: b x { pred (|x, y|) \/ xy == (|x, y|) }). f x y)
        fn x {
          let b = t2b (x == xy._1);
          if b {
            rewrite when__ (x == xy._1) (fun _ -> f x xy._2) as f x xy._2;
            forevery_insert (f x) xy._2;
            forevery_refine_ext (fun y -> pred (|x, y|) \/ xy == (|x, y|)) (f x);
          } else {
            rewrite when__ (x == xy._1) (fun _ -> f x xy._2) as emp;
            forevery_refine_ext (fun y -> pred (|x, y|) \/ xy == (|x, y|)) (f x);
          };
        };
    };
}

ghost
fn forevery_unflatten_dep'
  (#a : Type0)
  (#b : a -> Type0)
  (f : (x:a & b x) -> slprop)
  requires
    forall+ (xy : (x:a & b x)). f xy
  ensures
    forall+ (x:a) (y:b x). f (|x, y|)
{
  forevery_ext
    (fun (xy: (x:a & b x)) -> f xy)
    (fun (xy: (x:a & b x)) -> f (|xy._1, xy._2|));
  forevery_unflatten_dep #a #b (fun x y -> f (|x, y|));
  ();
}

let swap_bij a b : (a & b =~ b & a) =
  {
    right = (fun (x,y) -> (y,x));
    left = (fun (y,x) -> (x,y));
    right_left = easy;
    left_right = easy;
  }

ghost
fn forevery_commute
  (#a:Type0)
  (#b:Type0)
  (f : a -> b -> slprop)
  requires
    forall+ (x:a) (y:b). f x y
  ensures
    forall+ (y:b) (x:a). f x y
{
  forevery_flatten f;
  forevery_iso (swap_bij a b) (fun xy -> f (fst xy) (snd xy));
  forevery_ext _ (fun (xy: b & a) -> f xy._2 xy._1);
  forevery_unflatten (fun y x -> f x y);
}

ghost
fn forevery_iso_back
  (#a:Type0)
  (#b:Type0)
  (bij : a =~ b)
  (p : a -> slprop)
  requires
    forall+ (y:b). p (bij.left y)
  ensures
    forall+ (x:a). p x
{
  forevery_iso (bij_sym bij) _;
  forevery_ext (fun y -> p (bij.left ((bij_sym bij).left y))) p;
}

ghost
fn forevery_fin_extend
  (#n: nat)
  (m: nat { m >= n })
  (p: fin n -> slprop)
  requires
    forall+ (i: fin n). p i
  ensures
    forall+ (i: fin m { i < n }). p (fin_coerce i)
{
  forevery_refine_ext' #int (fun i -> 0 <= i /\ i < m /\ i < n) (fun i -> p i);
  ()
}

ghost
fn forevery_fin_restrict
  (#n: nat)
  (m: nat { m >= n })
  (p: fin n -> slprop)
  requires
    forall+ (i: fin m { i < n }). p (fin_coerce i)
  ensures
    forall+ (i: fin n). p i
{
  forevery_refine_ext' #int (fun i -> 0 <= i /\ i < n) (fun i -> p i)
}

ghost
fn forevery_fin_pop
  (n: nat { n > 0 })
  (p: fin n -> slprop)
  requires
    forall+ (i: fin n). p i
  ensures
    forall+ (i: fin (n-1)). p (fin_coerce i)
  ensures
    p (n-1)
{
  forevery_refine_split p (fun i -> i < n-1);
  forevery_singleton_elim' #(x: fin n {~(b2t (x < n - 1))}) p (n-1);
  forevery_fin_restrict #(n-1) n (fun i -> p (fin_coerce i));
}

ghost
fn forevery_fin_push
  (n: nat { n > 0 })
  (p: fin n -> slprop)
  requires
    forall+ (i: fin (n-1)). p (fin_coerce i)
  requires
    p (n-1)
  ensures
    forall+ (i: fin n). p i
{
  forevery_fin_extend #(n-1) n (fun i -> p (fin_coerce i));
  forevery_singleton_intro' #(x: fin n {~(b2t (x < n - 1))}) p (n-1);
  forevery_refine_join p (fun i -> i < n - 1) _;
  forevery_unrefine p;
}

let bij_mirror_n (n:nat) : (fin n =~ fin n) =
  {
    right = (fun (i:fin n) -> n - 1 - i <: fin n);
    left = (fun (i:fin n) -> n - 1 - i <: fin n);
    right_left = easy;
    left_right = easy;
  }


ghost
fn forevery_fin_pop_shift
  (n: nat { n > 0 })
  (p: fin n -> slprop)
  requires
    forall+ (i: fin n). p i
  ensures
    forall+ (i: fin (n-1)). p (i + 1)
  ensures
    p 0
{
  forevery_iso (bij_mirror_n n) p;
  forevery_fin_pop n _;
  rewrite p ((bij_mirror_n n).left (n-1)) as p 0;

  forevery_ext #(fin (n-1)) _
    (fun (i: fin (n-1)) -> p (n - 1 - i));

  forevery_iso (bij_mirror_n (n-1))
    (fun i -> p (n - 1 - i));

  forevery_ext #(fin (n-1)) _
    (fun (i: fin (n-1)) -> p (i + 1));
}

ghost
fn forevery_fin_push_shift
  (n: nat { n > 0 })
  (p: fin n -> slprop)
  requires
    forall+ (i: fin (n-1)). p (i + 1)
  requires
    p 0
  ensures
    forall+ (i: fin n). p i
{
  forevery_iso (bij_mirror_n (n-1))
    (fun i -> p (i + 1));

  forevery_ext #(fin (n-1)) _
    (fun (i: fin (n-1)) -> p (n - 1 - i));

  rewrite p 0 as p (n - 1 - (n - 1));

  forevery_fin_push n (fun i -> p (n - 1 - i));

  forevery_iso_back (bij_mirror_n n) p;
}

ghost
fn rec forevery_exists_fin
  (#n: nat)
  (#b: Type0)
  (p: fin n -> b -> slprop)
  requires
    forall+ (x:fin n). exists* (y:b). p x y
  returns
    y:(fin n -> b)
  ensures
    forall+ (x:fin n). p x (y x)
  decreases
    n
{
  if (n = 0) {
    let y: (fin n -> b) = (fun _ -> ());
    forevery_ext
      (fun x -> exists* (y:b). p x y)
      (fun x -> p x (y x));
    y
  } else {
    forevery_fin_pop n _;
    with yn1. assert p (n-1) yn1; let yn1_ = reveal yn1;
    let y = forevery_exists_fin #(n-1) (fun x y -> p (fin_coerce x) y);
    let y': (fin n -> b) =
      (fun i -> if i = n-1 then yn1_ else y (fin_coerce i));
    rewrite p (n-1) yn1 as p (n-1) (y' (n-1));
    forevery_ext (fun (i: fin (n-1)) -> p (fin_coerce i) (y i))
      (fun (i: fin (n-1)) -> p (fin_coerce i) (y' (fin_coerce i)));
    forevery_fin_push n (fun i -> p i (y' i));
    y'
  }
}

ghost
fn forevery_exists
  (#a: Type0) {| d : enumerable a |}
  (#b: Type0)
  (p: a -> b -> slprop)
  requires
    forall+ (x:a). exists* (y:b). p x y
  returns
    y:(a->GTot b)
  ensures
    forall+ (x:a). p x (y x)
{
  forevery_iso d.bij (fun x -> exists* (y:b). p x y);
  let y = forevery_exists_fin (fun i y -> p (of_nat i) y);
  let y' = (fun x -> y (to_nat x));
  forevery_ext _ (fun (y: fin (cardinal a #d)) -> p (d.bij.left y) (y' (d.bij.left y)));
  forevery_iso_back d.bij (fun x -> p x (y' x));
  y'
}

ghost
fn forevery_exists_2
  (#a: Type0) {| enumerable a |}
  (#b: Type0) {| enumerable b |}
  (#c: Type0)
  (p: a -> b -> c -> slprop)
  requires
    forall+ (x:a) (y:b).
      exists* (z:c). p x y z
  returns
    f:(a->b->GTot c)
  ensures
    forall+ (x:a) (y:b).
       p x y (f x y)
{
  forevery_flatten _;
  let f = forevery_exists #(a & b) (fun xy z -> p xy._1 xy._2 z);
  let f' = (fun x y -> f (x, y));
  forevery_unflatten' _;
  forevery_ext_2
    (fun x y -> p (x,y)._1 (x,y)._2 (f (x,y)))
    (fun x y -> p x y (f' x y));
  f'
}

ghost
fn forevery_emp_intro
  (a : Type0)
  ensures
    forall+ (_ : a). emp
{
  forevery_intro_fill (fun (_: a) -> emp) fn _ {}
}

ghost
fn forevery_emp_elim
  (a : Type0)
  requires
    forall+ (_ : a). emp
{
  drop_ (forall+ (_: a). emp)
}

let singleton_lemma (#a:Type) {| d : enumerable a |} (_:squash (cardinal a #d == 1))
: Lemma (forall (y:a). of_nat 0 == y)
= introduce forall (y:a). of_nat 0 == y
  with assert (d.bij.right y == 0)

ghost
fn forevery_singleton_intro
  (#a:Type0) {| enumerable a |}
  (p : a -> slprop { cardinal a #_ == 1 })
  requires
    p (of_nat 0)
  ensures
    forall+ (x:a). p x
{ singleton_lemma #a ();
  forevery_singleton_intro' p (of_nat 0);
}

ghost
fn forevery_singleton_elim
  (#a:Type0) {| enumerable a |}
  (p : a -> slprop { cardinal a #_ == 1 })
  requires
    forall+ (x:a). p x
  ensures
    p (of_nat 0)
{singleton_lemma #a ();
  forevery_singleton_elim' p (of_nat 0);
}

ghost
fn forevery_unit_intro
  (p : slprop)
  requires
    p
  ensures
    forevery unit (fun _ -> p)
{
  forevery_singleton_intro #unit (fun _ -> p);
}

ghost
fn forevery_unit_elim
  (p : slprop)
  requires
    forevery unit (fun _ -> p)
  ensures
    p
{
  forevery_singleton_elim #unit (fun _ -> p);
}

ghost
fn forevery_bool_intro
  (p: bool -> slprop)
  requires
    p false
  requires
    p true
  ensures
    forall+ (x: bool). p x
{
  forevery_intro_false p;
  forevery_insert p false;
  forevery_insert p true;
  forevery_unrefine p;
}

ghost
fn forevery_bool_elim
  (p: bool -> slprop)
  requires
    forall+ (x: bool). p x
  ensures
    p false
  ensures
    p true
{
  forevery_remove p false;
  forevery_remove' (fun x -> x =!= false) p true;
  forevery_elim_empty _;
}

ghost
fn forevery_eta
  (#a:Type0)
  (p : a -> slprop)
  requires
    forevery a p
  ensures
    forevery a (fun x -> p x)
{
  unfold op_forall_Plus #a p;
  fold op_forall_Plus #a (fun x -> p x);
}

ghost
fn forevery_uneta
  (#a:Type0)
  (p : a -> slprop)
  requires
    forevery a (fun x -> p x)
  ensures
    forevery a p
{
  unfold op_forall_Plus #a (fun x -> p x);
  fold op_forall_Plus #a p;
}

ghost
fn forevery_rw_size
  (n1 : nat)
  (n2 : nat{n1 == n2})
  (#p : fin n1 -> slprop)
  requires
    forall+ (i : fin n1). p i
  ensures
    forall+ (i : fin n2). p i
{
  rewrite each n1 as n2;
}

ghost
fn forevery_rw_size2
  (n1 : nat)
  (n2 : nat{n1 == n2})
  (n3 : nat)
  (n4 : nat{n3 == n4})
  (#p : fin n1 -> fin n3 -> slprop)
  requires
    forall+ (i : fin n1) (j : fin n3). p i j
  ensures
    forall+ (i : fin n2) (j : fin n4). p i j
{
  rewrite each n1 as n2;
  rewrite each n3 as n4;
}

ghost
fn forevery_factor
  (n : nat)
  (d1 : nat) (d2 : nat { n == d1 * d2 })
  (p : fin n -> slprop)
  requires
    forall+ (i:fin n). p i
  ensures
    forall+ (i1:fin d1) (i2:fin d2). p (i1 * d2 + i2)
{
  forevery_rw_size n (d1 * d2);
  forevery_iso (bij_sym <| bij_nat_prod #d1 #d2) _;
  forevery_unflatten #(fin d1) #(fin d2) (fun i1 i2 -> p (i1 * d2 + i2));
}

ghost
fn forevery_factor'
  (n : nat)
  (d1 : nat) (d2 : nat { n == d1 * d2 })
  (p : fin d1 -> fin d2 -> slprop)
  requires
    forall+ (i:fin n). p (i/d2) (i%d2)
  ensures
    forall+ (i1:fin d1) (i2:fin d2). p i1 i2
{
  forevery_factor n d1 d2 (fun i -> p (i / d2) (i % d2));
  forevery_ext_2
    (fun (i1 : fin d1) (i2 : fin d2) -> p ((i1 * d2 + i2) / d2) ((i1 * d2 + i2) % d2))
    (fun (i1 : fin d1) (i2 : fin d2) -> p i1 i2);
  ();
}

ghost
fn forevery_unfactor
  (n : nat)
  (d1 : nat) (d2 : nat { n == d1 * d2 })
  (p : fin n -> slprop)
  requires
    forall+ (i1:fin d1) (i2:fin d2). p (i1 * d2 + i2)
  ensures
    forall+ (i:fin n). p i
{
  forevery_flatten #(fin d1) #(fin d2) (fun i1 i2 -> p (i1 * d2 + i2));
  forevery_iso (bij_nat_prod #d1 #d2) _;
  forevery_rw_size (d1 * d2) n;
  forevery_ext _ p;
}

ghost
fn forevery_unfactor'
  (n : nat)
  (d1 : nat) (d2 : nat { n == d1 * d2 })
  (p : fin d1 -> fin d2 -> slprop)
  requires
    forall+ (i1:fin d1) (i2:fin d2). p i1 i2
  ensures
    forall+ (i:fin n). p (i/d2) (i%d2)
{
  rewrite
    forall+ (i1: fin d1) (i2: fin d2). p i1 i2
  as
    forall+ (i1: fin d1) (i2: fin d2).
      p ((i1 * d2 + i2) / d2) ((i1 * d2 + i2) % d2);
  forevery_unfactor n d1 d2 (fun i -> p (i/d2) (i%d2));
}

ghost
fn forevery_map_2
  (#a:Type0)
  (#b:Type0)
  (p1 p2 : a -> b -> slprop)
  (f : (x:a -> y:b -> stt_ghost unit emp_inames (p1 x y) (fun _ -> p2 x y)))
  requires
    forall+ (x:a) (y:b). p1 x y
  ensures
    forall+ (x:a) (y:b). p2 x y
{
  forevery_map #a
    (fun x -> forevery b (fun y -> p1 x y))
    (fun x -> forevery b (fun y -> p2 x y))
    (fun x -> forevery_map (fun y -> p1 x y)
                          (fun y -> p2 x y)
                          (f x));
}

ghost
fn forevery_map'
  (#a:Type0)
  (#b:Type0 { a == b })
  (p1 : a -> slprop)
  (p2 : b -> slprop)
  (f : (x:a -> y:b { x === y } -> stt_ghost unit emp_inames (p1 x) (fun _ -> p2 y)))
  requires
    forall+ (x:a). p1 x
  ensures
    forall+ (x:b). p2 x
{
  rewrite each a as b;
  forevery_map #b p1 p2 fn x { f x x };
}

ghost
fn forevery_zip_2
  (#a:Type0)
  (#b:Type0)
  (p1 p2 : a -> b -> slprop)
  requires
    (forall+ (x:a) (y:b). p1 x y) **
    (forall+ (x:a) (y:b). p2 x y)
  ensures
    forall+ (x:a) (y:b). p1 x y ** p2 x y
{
  forevery_zip (fun (x:a) -> forall+ (y:b). p1 x y) _;
  forevery_map _ _ (fun x -> forevery_zip (fun (y:b) -> p1 x y) _);
}

ghost
fn forevery_unzip_2
  (#a:Type0)
  (#b:Type0)
  (p1 p2 : a -> b -> slprop)
  requires
    forall+ (x:a) (y:b). p1 x y ** p2 x y
  ensures
    (forall+ (x:a) (y:b). p1 x y) **
    (forall+ (x:a) (y:b). p2 x y)
{
  forevery_map _ _ (fun x -> forevery_unzip (fun (y:b) -> p1 x y) _);
  forevery_unzip (fun (x:a) -> forall+ (y:b). p1 x y) _;
}

ghost
fn forevery_pad
  (n1 : nat)
  (n2 : nat{n1 <= n2})
  (p : fin n1 -> slprop)
  requires
    forall+ (i : fin n1). p i
  ensures
    forall+ (i : fin n2). pad_f n2 p i
{
  forevery_ext #(fin n1) p (fun (i: fin n1) -> pad_f n2 p (fin_coerce i));
  forevery_fin_extend n2 (fun (i: fin n1) -> pad_f n2 p (fin_coerce i));
  forevery_fill (fun (i: fin n2) -> pad_f n2 p i)
    (fun i -> i >= n1) fn i { rewrite emp as pad_f #n1 n2 p i };
  forevery_unrefine (fun (i: fin n2) -> pad_f n2 p i);
}

ghost
fn forevery_unpad
  (n1 : nat)
  (n2 : nat{n1 <= n2})
  (p : fin n1 -> slprop)
  requires
    forall+ (i : fin n2). pad_f n2 p i
  ensures
    forall+ (i : fin n1). p i
{
  forevery_refine_split (fun (i: fin n2) -> pad_f n2 p i) (fun i -> i < n1);
  drop_ (forall+ (i: fin n2 { ~(i < n1) }). pad_f n2 p i);
  forevery_fin_restrict n2 (fun (i: fin n1) -> pad_f n2 p (fin_coerce i));
  forevery_ext #(fin n1) (fun (i: fin n1) -> pad_f n2 p (fin_coerce i)) p;
}

ghost
fn forevery_extract
  (#a:Type0)
  (z : a)
  (p : a -> slprop)
  requires
    forall+ (x:a). p x
  ensures
    p z ** (p z @==> forall+ (x:a). p x)
{
  forevery_remove p z;
  intro (p z @==> forall+ (x:a). p x) #(forall+ (x:a{x =!= z}). p x) fn _ {
    forevery_insert p z;
    forevery_unrefine p;
  }
}

// FIXME: Type-class inference fails inside Pulse?!?
let forevery_extract'_aux #a (z:a) (p: a->slprop) =
  intro (forall* (p' : a -> slprop).
      p' z ** pure (forall (x:a{x =!= z}). p' x == p x)
        @==> (forall+ (x:a). p' x))
    #(forall+ (x:a{x =!= z}). p x)

ghost
fn forevery_extract'
  (#a:Type0)
  (z : a)
  (p  : a -> slprop)
  requires
    forall+ (x:a). p x
  ensures
    p z **
      (forall* (p' : a -> slprop).
        p' z ** pure (forall (x:a{x =!= z}). p' x == p x)
          @==> (forall+ (x:a). p' x))
{
  forevery_remove p z;
  forevery_extract'_aux z p fn _ p' {
    forevery_map #(x:a{x =!= z}) p p'
      fn x { rewrite p x as p' x };
    forevery_insert p' z;
    forevery_unrefine p';
  };
}

ghost
fn forevery_extract_2
  (#a:Type0)
  (#b:Type0)
  (z : a) (w : b)
  (p : a -> b -> slprop)
  requires
    forall+ (x:a) (y:b). p x y
  ensures
    p z w ** (p z w @==> forall+ (x:a) (y:b). p x y)
{
  forevery_flatten p;
  forevery_remove (fun (xy: a & b) -> p xy._1 xy._2) (z, w);
  with z' w'. rewrite p z' w' as p z w;
  intro (p z w @==> forall+ (x:a) (y:b). p x y)
    #(forall+ (xy: a&b { xy =!= (z,w) }). p xy._1 xy._2)
    fn _ {
      rewrite p z w as p (z,w)._1 (z,w)._2;
      forevery_insert (fun (xy: a&b) -> p xy._1 xy._2) (z, w);
      forevery_unrefine (fun (xy: a&b) -> p xy._1 xy._2);
      forevery_unflatten p;
    };
}

ghost
fn forevery_extract_if
  (#a:Type0)
  (z : a)
  (p : a -> slprop)
  requires
    forall+ (x:a). p x
  ensures
    p z **
    (forall+ (x:a). unless (x == z) (p x))
{
  forevery_remove p z;
  forevery_unrefine_pred p (fun x -> x =!= z);
  forevery_ext (fun x -> when_ (x =!= z) (p x)) (fun x -> unless (x == z) (p x));
}

ghost
fn forevery_extract_if_eqtype
  (#a:eqtype)
  (z : a)
  (p : a -> slprop)
  requires
    forall+ (x:a). p x
  ensures
    p z **
    (forall+ (x:a).
      if x = z then emp else p x)
{
  forevery_extract_if z p;
  rewrite
    (forall+ (x:a).
      if t2b (x == z) then emp else p x)
  as
    (forall+ (x:a).
      if x = z then emp else p x);
}

ghost
fn forevery_unextract_if
  (#a:Type0)
  (z : a)
  (p : a -> slprop)
  requires
    p z **
    (forall+ (x:a). unless (x == z) (p x))
  ensures
    forall+ (x:a). p x
{
  forevery_remove (fun x -> unless (x == z) (p x)) z;
  rewrite unless (z == z) (p z) as emp;
  // Need to annotate #a below
  forevery_ext
    (fun (x: a{x =!= z}) -> unless (eq2 #a x z) (p x))
    (fun (x: a{x =!= z}) -> p x);
  forevery_insert p z;
  forevery_unrefine p;
}

ghost
fn forevery_unextract_if_eqtype
  (#a:eqtype)
  (z : a)
  (p : a -> slprop)
  requires
    p z **
    (forall+ (x:a).
      if x = z then emp else p x)
  ensures
    forall+ (x:a). p x
{
  rewrite
    (forall+ (x:a).
      if x = z then emp else p x)
  as
    (forall+ (x:a).
      if t2b (x == z) then emp else p x);
  forevery_unextract_if z p;
}

ghost
fn forevery_extract_if_2
  (#a:Type0)
  (#b:Type0)
  (z : a) (w : b)
  (p : a -> b -> slprop)
  requires
    forall+ (x:a) (y:b). p x y
  ensures
    p z w **
    (forall+ (x:a) (y:b).
      unless ((x, y) == (z, w)) (p x y))
{
  forevery_flatten #a #b _;
  forevery_extract_if (z, w) _;
  forevery_unflatten' #a #b _;
  rewrite p (z,w)._1 (z,w)._2 as p z w;
  with q. rewrite
    (forall+ (x:a) (y:b). q x y)
  as
    (forall+ (x:a) (y:b).
      unless ((x, y) == (z, w)) (p x y));
}

ghost
fn forevery_boolean_split
  (#a:Type0)
  (b : a -> bool)
  (p : a -> slprop)
  requires
    forall+ (x:a). p x
  ensures
    (forall+ (x:a). if b x then emp else p x) **
    (forall+ (x:a). if b x then p x else emp)
{
  forevery_refine_split p (fun x -> b x);
  forevery_unrefine_pred p (fun x -> b x);
  forevery_unrefine_pred p (fun x -> ~(b x));
  forevery_ext (fun x -> when_ (~(b x)) (p x)) (fun x -> if b x then emp else p x);
  forevery_ext (fun x -> when_ (b x) (p x)) (fun x -> if b x then p x else emp);
}

ghost
fn forevery_boolean_join
  (#a:Type0)
  (b : a -> bool)
  (p1 p2 : a -> slprop)
  requires
    (forall+ (x:a). if b x then p1 x else emp) **
    (forall+ (x:a). if b x then emp else p2 x)
  ensures
    (forall+ (x:a). if b x then p1 x else p2 x)
{
  forevery_ext (fun x -> if b x then p1 x else emp) (fun x -> when_ (b x) (p1 x));
  forevery_refine_pred p1 (fun x -> b x);
  forevery_ext (fun x -> if b x then emp else p2 x) (fun x -> when_ (~(b x)) (p2 x));
  forevery_refine_pred p2 (fun x -> ~(b x));
  forevery_ext #(x:a{ b x }) p1 (fun x -> if b x then p1 x else p2 x);
  forevery_ext #(x:a{ ~(b x) }) p2 (fun x -> if b x then p1 x else p2 x);
  forevery_refine_join (fun x -> if b x then p1 x else p2 x) (fun x -> b x) (fun x -> ~(b x));
  forevery_unrefine _;
}

ghost
fn forevery_boolean_equal_sides
  (#a:Type0)
  (b : a -> bool)
  (p : a -> slprop)
  requires
    (forall+ (x:a). if b x then p x else p x)
  ensures
    (forall+ (x:a). p x)
{
  forevery_ext (fun x -> if b x then p x else p x) p;
}

ghost
fn forevery_intro_if
  (#a:Type0)
  (z : a)
  (p : a -> slprop)
  requires
    p z
  ensures
    (forall+ (x:a). when_ (x == z) (p x))
{
  forevery_singleton_intro' #(x:a { x == z }) p z;
  forevery_unrefine_pred p _;
}

let bij_either_inl a b : ((x: either a b { Inl? x }) =~ a) =
  mk_bijection #(x: either a b { Inl? x }) Inl?.v (fun x -> Inl x) easy easy

let bij_either_inr a b : ((x: either a b { ~(Inl? x) }) =~ b) =
  mk_bijection #(x: either a b { ~(Inl? x) }) (fun x -> Inr?.v x) (fun x -> Inr x) easy easy

ghost
fn forevery_split_either
  (#a #b : Type0)
  (p : either a b -> slprop)
  requires
    forall+ (x:either a b). p x
  ensures
    (forall+ (x:a). p (Inl x)) **
    (forall+ (x:b). p (Inr x))
{
  forevery_refine_split p (fun x -> Inl? x);
  forevery_iso (bij_either_inl a b) p;
  forevery_ext (fun x -> p ((bij_either_inl a b).left x)) (fun x -> p (Inl x));
  forevery_iso (bij_either_inr a b) p;
  forevery_ext (fun x -> p ((bij_either_inr a b).left x)) (fun x -> p (Inr x));
}

ghost
fn forevery_join_either
  (#a #b : Type0)
  (p : either a b -> slprop)
  requires
    (forall+ (x:a). p (Inl x)) **
    (forall+ (x:b). p (Inr x))
  ensures
    forall+ (x:either a b). p x
{
  forevery_ext (fun x -> p (Inl x)) (fun x -> p ((bij_either_inl a b).left x));
  forevery_ext (fun x -> p (Inr x)) (fun x -> p ((bij_either_inr a b).left x));
  forevery_iso_back (bij_either_inl a b) p;
  forevery_iso_back (bij_either_inr a b) p;
  forevery_refine_join p (fun x -> Inl? x) (fun x -> ~(Inl? x));
  forevery_unrefine p;
}

ghost
fn rec __forevery_map_extra_nat
  (#n : nat)
  (m : nat{m <= n})
  (k : slprop)
  (p1 p2 : fin n -> slprop)
  (f : (x:fin n -> stt_ghost unit emp_inames (k ** p1 x) (fun _ -> k ** p2 x)))
  preserves k
  requires
    (forall+ (x : fin n{x < m}). p1 x) **
    (forall+ (x : fin n{x >= m}). p2 x)
  ensures
    (forall+ (x : fin n). p2 x)
  decreases m
{
  if (m = 0) {
    rewrite each m as 0;
    forevery_elim_empty #(x: fin n { x < 0 }) p1;
    forevery_unrefine _;
    ()
  } else {
    forevery_remove' #(fin n) (fun x -> x < m) p1 (m-1);
    f (m-1);
    forevery_refine_ext #(fin n)
      #(fun x -> x < m /\ ~(eq2 #(fin n) x (m-1)))
      (fun x -> x < m-1)
      p1;
    forevery_insert p2 (m-1);
    forevery_refine_ext #(fin n)
      #(fun x -> x >= m \/ eq2 #(fin n) (m-1) x)
      (fun x -> x >= m-1)
      p2;
    __forevery_map_extra_nat (m-1) k p1 p2 f;
  }
}

ghost
fn forevery_map_extra_nat
  (#n : nat)
  (k : slprop)
  (p1 p2 : fin n -> slprop)
  (f : (x:fin n -> stt_ghost unit emp_inames (k ** p1 x) (fun _ -> k ** p2 x)))
  preserves k
  requires
    forall+ (x : fin n). p1 x
  ensures
    forall+ (x : fin n). p2 x
{
    forevery_refine_ext #(fin n)
      (fun x -> x < n)
      p1;
  forevery_intro_empty #(x : fin n{x >= n}) p2;
  __forevery_map_extra_nat #n n k p1 p2 f;
}

ghost
fn forevery_map_extra
  (#a:Type0) {| d : enumerable a |}
  (k : slprop)
  (p1 p2 : a -> slprop)
  (f : (x:a -> stt_ghost unit emp_inames (k ** p1 x) (fun _ -> k ** p2 x)))
  preserves k
  requires
    forall+ (x:a). p1 x
  ensures
    forall+ (x:a). p2 x
{
  forevery_iso d.bij _;
  ghost
  fn f' (x: fin (cardinal a #_))
    requires k ** p1 (of_nat x)
    ensures  k ** p2 (of_nat x)
  {
    f (of_nat x)
  };
  forevery_map_extra_nat #(cardinal a #_) k _ _ f';
  forevery_iso_back d.bij _;
}

let bij_nested_3
     (#a #b #c : Type0)
  : ((a & b & c) =~ ((a & b) & c)) =
  mk_bijection
    #(a & b & c)
    #((a & b) & c)
    (fun x -> ((x._1, x._2), x._3))
    (fun y -> (y._1._1, y._1._2, y._2))
    easy easy

ghost
fn forevery_flatten3'
  (#a #b #c : Type0)
  (f : a & b & c -> slprop)
  requires
    forall+ (x:a) (y:b) (z:c). f (x, y, z)
  ensures
    forall+ (xyz : a & b & c). f xyz
{
  forevery_flatten _;
  forevery_flatten _;
  forevery_iso (bij_sym <| bij_nested_3 #a #b #c) _;
  forevery_ext
    _
    (fun (xyz: a & b & c) -> f xyz);
  ();
}

ghost
fn forevery_unflatten3'
  (#a #b #c : Type0)
  (f : a & b & c -> slprop)
  requires
    forall+ (xyz : a & b & c). f xyz
  ensures
    forall+ (x:a) (y:b) (z:c). f (x, y, z)
{
  forevery_iso (bij_nested_3 #a #b #c) _;
  forevery_ext
    _
    (fun (xyz : ((a & b) & c)) -> f (xyz._1._1, xyz._1._2, xyz._2));
  forevery_unflatten' _;
  forevery_unflatten' _;
  ();
}

let bij_nested_4
     (#a #b #c #d : Type0)
  : ((a & b & c & d) =~ (((a & b) & c) & d)) =
  mk_bijection
    #(a & b & c & d)
    #(((a & b) & c) & d)
    (fun x -> ((((x._1, x._2), x._3), x._4)))
    (fun y -> (y._1._1._1, y._1._1._2, y._1._2, y._2))
    easy easy

ghost
fn forevery_flatten4'
  (#a #b #c #d : Type0)
  (f : a & b & c & d -> slprop)
  requires
    forall+ (x:a) (y:b) (z:c) (w:d). f (x, y, z, w)
  ensures
    forall+ (xyzw : a & b & c & d). f xyzw
{
  forevery_flatten _;
  forevery_flatten _;
  forevery_flatten _;
  forevery_iso (bij_sym <| bij_nested_4 #a #b #c #d) _;
  forevery_ext
    _
    (fun (xyzw: a & b & c & d) -> f xyzw);
  ();
}

ghost
fn forevery_unflatten4'
  (#a #b #c #d : Type0)
  (f : a & b & c & d -> slprop)
  requires
    forall+ (xyzw : a & b & c & d). f xyzw
  ensures
    forall+ (x:a) (y:b) (z:c) (w:d). f (x, y, z, w)
{
  forevery_iso (bij_nested_4 #a #b #c #d) _;
  forevery_ext
    _
    (fun (xyzw : (((a & b) & c) & d)) -> f (xyzw._1._1._1, xyzw._1._1._2, xyzw._1._2, xyzw._2));
  forevery_unflatten' _;
  forevery_unflatten' _;
  forevery_unflatten' _;
  ();
}

ghost
fn forevery_split_or_2
  (#a:Type0)
  (r s : a -> prop)
  (p : a -> slprop)
  requires
    pure (~ (exists (x:a). r x /\ s x))
  requires
    forall+ (x:a { r x \/ s x }). p x
  ensures
    (forall+ (x:a { r x }). p x) **
    (forall+ (x:a { s x }). p x)
{
  forevery_refine_split (fun (x: a { r x \/ s x }) -> p x) (fun x -> r x);
  forevery_refine_ext #a #(fun x -> (r x \/ s x) /\ r x) r p;
  forevery_refine_ext #a #(fun x -> (r x \/ s x) /\ ~(r x)) s p;
}

let or_n_bij #a #b (r: b -> a -> prop)
      (p : a -> slprop { forall (i1 i2 : b) x. r i1 x /\ r i2 x ==> i1 == i2 }) :
    (x:a { exists i. r i x } =~ i: b & (x:a { r i x })) =
  let get_i (x: a { exists i. r i x }) : GTot (i: b { r i x }) =
    IndefiniteDescription.indefinite_description_ghost (b) (fun i -> r i x) in
  {
    right = (fun x -> (| get_i x, x |))
      <: (x:a { exists i. r i x } -> GTot (i: b & (x:a { r i x })));
    left = (fun (|i, x|) -> x)
      <: (i: b & (x:a { r i x }) -> x:a { exists i. r i x });
    right_left = (fun _ -> ());
    left_right = (fun _ -> ());
  }

ghost
fn forevery_split_or_n
  (#a #b:Type0)
  (r : b -> a -> prop)
  (p : a -> slprop)
  requires
    pure (forall (i1 i2 : b) x.
      r i1 x /\ r i2 x ==> i1 == i2)
  requires
    forall+ (x:a {exists i. r i x}). p x
  ensures
    forall+ (i : b).
      forall+ (x:a { r i x }).
        p x
{
  forevery_iso (or_n_bij r p) _;
  forevery_unflatten_dep' _;
  rewrite
    forall+ (x: b) (y: a{r x y}). p ((or_n_bij r p).left (| x, y |))
  as
    forall+ (x: b) (y: a{r x y}). p y;
}

ghost
fn forevery_join_or_n
  (#a #b:Type0)
  (r : b -> a -> prop)
  (p : a -> slprop)
  requires
    pure (forall (i1 i2 : b) x.
      r i1 x /\ r i2 x ==> i1 == i2)
  requires
    forall+ (i : b).
      forall+ (x:a { r i x }).
        p x
  ensures
    forall+ (x:a {exists i. r i x}). p x
{
  forevery_flatten_dep _;
  forevery_iso (bij_sym (or_n_bij r p)) _;
  rewrite
    forall+ (y: a{exists i. r i y}). p ((bij_sym (or_n_bij r p)).left y)._2
  as
    forall+ (x:a {exists i. r i x}). p x;
}

ghost
fn on_forevery_elim (#a: Type0) (p: a -> slprop) (l: loc_id)
  requires
    on l (forall+ (x:a). p x)
  ensures
    forall+ (x:a). on l (p x)
{
  loc_get (); with l0. assert loc l0;
  ghost_impersonate l (on l (forall+ x. p x)) (on l0 (forall+ x. on l (p x))) fn _ {
    on_elim _;
    ghost_impersonate l0 emp (on l0 (forall+ (x: a {False}). on l (p x))) fn _ {
      forevery_intro_false (fun x -> on l (p x));
      on_intro (forall+ (x:a{False}). on l (p x));
    };
    forevery_rec p
      (fun ref -> loc l ** on l0 (forall+ (x:a{ref x}). on l (p x)))
      fn pred add f {
        ghost_impersonate l0 (on l0 (forall+ (x:a{pred x}). on l (p x)))
            (on l0 (forall+ (x:a{pred x \/ add x}). on l (p x))) fn _ {
          on_elim _;
          forevery_fill (fun x -> on l (p x)) add fn x {
            ghost_impersonate l emp (on l (p x)) fn _ {
              f x;
              on_intro (p x)
            }
          };
          on_intro (forall+ (x:a{pred x \/ add x}). on l (p x));
        }
      }
      fn pred z {
        on_intro (p z);
        ghost_impersonate l0
          (on l (p z) ** on l0 (forall+ (x: a{pred x}). on l (p x)))
          (on l0 (forall+ (x: a{pred x \/ z == x}). on l (p x)))
          fn _ {
            on_elim (forall+ (x:a{pred x}). on l (p x));
            forevery_insert (fun x -> on l (p x)) z;
            on_intro (forall+ (x:a{pred x \/ z == x}). on l (p x));
          };
      };
  };
  on_elim _;
  drop_ (loc l0)
}

ghost
fn is_send_across_forevery
  (#a:Type u#0) (#b:Type) (p: a -> slprop) (vis:loc_id -> b) {| sa: (x:a -> is_send_across vis (p x)) |} :
  is_send_across vis (forall+ x. p x) = l1 l2
{
  ghost_impersonate l1 (on l1 (forall+ x. p x)) (on l2 (forall+ x. p x)) fn _ {
    on_elim _;
    ghost_impersonate l2 emp (on l2 (forall+ (x: a {False}). p x)) fn _ {
      forevery_intro_false (fun x -> p x);
      on_intro (forall+ (x:a{False}). p x);
    };
    forevery_rec p (fun ref -> loc l1 ** on l2 (forall+ (x: a { ref x }). p x))
      fn pred add f {
        ghost_impersonate l2 (on l2 (forall+ (x: a { pred x }). p x))
            (on l2 (forall+ (x: a { pred x \/ add x }). p x)) fn _ {
          on_elim (forall+ (x: a { pred x }). p x);
          forevery_fill p add fn z { f z };
          on_intro (forall+ (x: a { pred x \/ add x }). p x);
        }
      }
      fn pred z {
        on_intro (p z);
        sa z l1 l2;
        ghost_impersonate l2 (on l2 (p z) ** on l2 (forall+ (x: a { pred x }). p x))
            (on l2 (forall+ (x: a { pred x \/ z == x }). p x)) fn _ {
          on_elim (p z);
          on_elim (forall+ (x: a { pred x }). p x);
          forevery_insert p z;
          on_intro (forall+ (x: a { pred x \/ z == x }). p x);
        }
      };
  }
}

ghost
fn forevery_factor_2
  (m : nat) (m1 m2 : nat { m == m1 * m2 })
  (n : nat) (n1 n2 : nat { n == n1 * n2 })
  (p : fin m -> fin n -> slprop)
  requires
    forall+ (i : fin m) (j : fin n). p i j
  ensures
    forall+ (i1 : fin m1) (i2 : fin m2) (j1 : fin n1) (j2 : fin n2).
      p (i1 * m2 + i2) (j1 * n2 + j2)
{
  forevery_map #(fin m)
    (fun i -> forall+ (j : fin n).p i j)
    (fun i -> forall+ (j1 : fin n1) (j2 : fin n2). p i (j1 * n2 + j2))
    (fun _ -> forevery_factor n n1 n2 _);
  forevery_factor m m1 m2 _;
}

ghost
fn forevery_unfactor_2
  (m : nat) (m1 m2 : nat { m == m1 * m2 })
  (n : nat) (n1 n2 : nat { n == n1 * n2 })
  (p : fin m -> fin n -> slprop)
  requires
    forall+ (i1 : fin m1) (i2 : fin m2) (j1 : fin n1) (j2 : fin n2).
      p (i1 * m2 + i2) (j1 * n2 + j2)
  ensures
    forall+ (i : fin m) (j : fin n). p i j
{
  forevery_unfactor' m m1 m2 _;
  forevery_map #(fin m)
    (fun i -> forall+ (j1 : fin n1) (j2 : fin n2). p (i / m2 * m2 + i % m2) (j1 * n2 + j2))
    (fun i -> forall+ (j : fin n). p i j)
    fn i {
      rewrite each (i / m2 * m2 + i % m2) as i;
      forevery_unfactor' n n1 n2 _;
      forevery_ext #(fin n) _ (fun j -> p i j);
    };
}

ghost
fn forevery_mid_flip
  (#a #b #c : Type0)
  (p : a -> b -> c -> slprop)
  requires
    forall+ (x:a) (y:b) (z:c). p x y z
  ensures
    forall+ (x:a) (z:c) (y:b). p x y z
{
  forevery_map #a
    (fun x -> forall+ (y:b) (z:c). p x y z)
    (fun x -> forall+ (z:c) (y:b). p x y z)
    fn x { forevery_commute _ };
}

let silly_coerce_helper
  (n : pos)
  (q : fin n -> prop)
  : Lemma (requires (forall (x : fin (n-1)). q (fin_coerce x)) /\
                    (q (n-1)))
          (ensures  forall (x : fin n). q x)
  = introduce forall (x : fin n). q x with
    if x = (n-1) then (
      ()
    ) else (
      assert (fin_coerce #(n-1) #n x == x);
      ()
    )

ghost
fn rec forevery_extract_pure_fin
  (n : nat)
  (p : fin n -> slprop)
  (q : fin n -> prop)
  (f : (x:fin n) -> stt_ghost unit emp_inames (p x) (fun _ -> p x ** pure (q x)))
  preserves
    forall+ (x:fin n). p x
  ensures
    pure (forall (x:fin n). q x)
  decreases n
{
  if (n = 0) {
    ()
  } else {
    assert pure (n > 0);
    forevery_fin_pop n _;
    f (n-1);
    forevery_extract_pure_fin (n-1)
      (fun i -> p (fin_coerce i))
      (fun i -> q (fin_coerce i))
      (fun i -> f (fin_coerce i));
    forevery_fin_push n _;
    silly_coerce_helper n q;
    (); // needed...
  }
}

let iso_lemma_prop
  (#a #b : Type0)
  (q : a -> prop)
  (bij : (a =~ b))
  : Lemma (requires forall (y:b). q (bij.left y))
          (ensures  forall (x:a). q x)
  = introduce forall (x:a). q x with
    let y = bij.right x in
    assert (x == bij.left y);
    ()

ghost
fn forevery_extract_pure
  (#a : Type0) {| d : enumerable a |}
  (p : a -> slprop)
  (q : a -> prop)
  (f : (x:a) -> stt_ghost unit emp_inames (p x) (fun _ -> p x ** pure (q x)))
  preserves
    forall+ (x:a). p x
  ensures
    pure (forall (x:a). q x)
{
  forevery_iso d.bij _;
  forevery_extract_pure_fin (cardinal a #_)
    (fun i -> p (of_nat i))
    (fun i -> q (of_nat i))
    (fun i -> f (of_nat i));
  forevery_iso_back d.bij _;
  iso_lemma_prop #a #(fin (cardinal a #_)) q d.bij;
  ();
}

let lemma_flatten_prop
  (#a #b : Type0)
  (q : a -> b -> prop)
  : Lemma (requires forall (xy: a & b). q xy._1 xy._2)
          (ensures  forall (x:a) (y:b). q x y)
  = introduce forall (x:a) (y:b). q x y with
    let p = (x,y) in
    ()

ghost
fn forevery_extract_pure_2
  (#a #b : Type0)
  {| enumerable a, enumerable b |}
  (p : a -> b -> slprop)
  (q : a -> b -> prop)
  (f : (x:a) -> (y:b) ->
    stt_ghost unit emp_inames (p x y) (fun _ -> p x y ** pure (q x y)))
  preserves
    forall+ (x:a) (y:b). p x y
  ensures
    pure (forall (x:a) (y:b). q x y)
{
  forevery_flatten _;
  forevery_extract_pure (fun (xy: a & b) -> p xy._1 xy._2)
    (fun (xy: a & b) -> q xy._1 xy._2)
    fn xy { f xy._1 xy._2 };
  forevery_unflatten _;
  assert pure (forall (xy:a&b). q xy._1 xy._2);
  lemma_flatten_prop #a #b q;
  assert pure (forall (x:a) (y:b). q x y);
  ();
}

ghost
fn forevery_rw_size4
  (n1 : nat)
  (n2 : nat{n1 == n2})
  (n3 : nat)
  (n4 : nat{n3 == n4})
  (n5 : nat)
  (n6 : nat{n5 == n6})
  (n7 : nat)
  (n8 : nat{n7 == n8})
  (#p : fin n1 -> fin n3 -> fin n5 -> fin n7 -> slprop)
  requires
    forall+ (i : fin n1) (j : fin n3) (k : fin n5) (l : fin n7). p i j k l
  ensures
    forall+ (i : fin n2) (j : fin n4) (k : fin n6) (l : fin n8). p i j k l
{
  rewrite each n1 as n2;
  rewrite each n3 as n4;
  rewrite each n5 as n6;
  rewrite each n7 as n8;
}

ghost
fn forevery_swap_mid_4
  (#a #b #c #d : Type0)
  (p : a -> b -> c -> d -> slprop)
  requires
    forall+ (w:a) (x:b) (y:c) (z:d). p w x y z
  ensures
    forall+ (w:a) (y:c) (x:b) (z:d). p w x y z
{
  (* forall+ w x y z -> forall+ w y x z *)
  (* Swap x and y by flattening (y,z) into a pair, commuting x with it, then unflattening *)
  forevery_map #a
    (fun w -> forall+ (x:b) (y:c) (z:d). p w x y z)
    (fun w -> forall+ (y:c) (x:b) (z:d). p w x y z)
    fn w {
      (* forall+ x y z -> forall+ x (y,z) *)
      forevery_map #b
        (fun x -> forall+ (y:c) (z:d). p w x y z)
        (fun x -> forall+ (yz : c & d). p w x yz._1 yz._2)
        fn x { forevery_flatten (fun y z -> p w x y z) };
      (* forall+ x (y,z) -> forall+ (y,z) x *)
      forevery_commute (fun (x:b) (yz : c & d) -> p w x yz._1 yz._2);
      (* forall+ (y,z) x -> forall+ y z x *)
      forevery_map #(c & d)
        (fun yz -> forall+ (x:b). p w x yz._1 yz._2)
        (fun yz -> forall+ (x:b). p w x (fst yz) (snd yz))
        fn yz { () };
      forevery_map #(c & d)
        (fun yz -> forall+ (x:b). p w x (fst yz) (snd yz))
        (fun yz -> forall+ (x:b). p w x yz._1 yz._2)
        fn yz { () };
      forevery_unflatten (fun (y:c) (z:d) -> forall+ (x:b). p w x y z);
      (* forall+ y z x -> forall+ y x z *)
      forevery_map #c
        (fun y -> forall+ (z:d) (x:b). p w x y z)
        (fun y -> forall+ (x:b) (z:d). p w x y z)
        fn y { forevery_commute (fun (z:d) (x:b) -> p w x y z) };
    };
}

ghost
fn forevery_zip3_2
  (#a #b : Type0)
  (p1 p2 p3 : a -> b -> slprop)
  requires
    forall+ (x:a) (y:b). p1 x y
  requires
    forall+ (x:a) (y:b). p2 x y
  requires
    forall+ (x:a) (y:b). p3 x y
  ensures
    forall+ (x:a) (y:b). p1 x y ** p2 x y ** p3 x y
{
  forevery_zip_2 p2 p3;
  forevery_zip_2 p1 (fun x y -> p2 x y ** p3 x y);
}

(* 4-way zip for 2-argument predicates *)
ghost
fn forevery_zip4_2
  (#a #b : Type0)
  (p1 p2 p3 p4 : a -> b -> slprop)
  requires
    forall+ (x:a) (y:b). p1 x y
  requires
    forall+ (x:a) (y:b). p2 x y
  requires
    forall+ (x:a) (y:b). p3 x y
  requires
    forall+ (x:a) (y:b). p4 x y
  ensures
    forall+ (x:a) (y:b). p1 x y ** p2 x y ** p3 x y ** p4 x y
{
  forevery_zip_2 p3 p4;
  forevery_zip_2 p2 (fun x y -> p3 x y ** p4 x y);
  forevery_zip_2 p1 (fun x y -> p2 x y ** p3 x y ** p4 x y);
}

ghost
fn forevery_ext_4
  (#a #b #c #d : Type0)
  (f : a -> b -> c -> d -> slprop)
  (g : a -> b -> c -> d -> slprop { forall w x y z. f w x y z == g w x y z })
  requires
    forall+ (w:a) (x:b) (y:c) (z:d). f w x y z
  ensures
    forall+ (w:a) (x:b) (y:c) (z:d). g w x y z
{
  rewrite (forall+ (w:a) (x:b) (y:c) (z:d). f w x y z)
    as (forall+ (w:a) (x:b) (y:c) (z:d). g w x y z);
}

ghost
fn forevery_push_pure
  (#a:Type0) (p : a -> slprop)
  (q : prop)
  requires
    pure q ** (forall+ (x:a). p x)
  ensures
    forall+ (x:a). p x ** pure q
{
  forevery_map p (fun x -> p x ** pure q)
    fn x { }
}
