language: csharp

matrix:
  fast_finish: true

  include:
    - env: Ubuntu=16.04
      os: linux
      dist: xenial
      sudo: required

    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

  allow_failures:
    - os: osx

before_install:
  - ./.ci/before_install.sh

install:
  - ./.ci/install.sh

script:
  - ./.ci/script.sh

notifications:
  slack:
    secure: HvfVJFkn9PhK5k6VPWK/URUPcseMEy1lGNLJWFr4j5b1ETLx8xrmZcQD7x9zMLO7aD3b5pc9XrNmvYe4phfGOm0PagKbvkYxt7L2ZY8Gp3WqgTHgjamcK/lObB0MGVwNGd/x7HzjWyNsgKqjvAY9vhk5l2kr1v3t2ql+MN1epAY=

git:
    depth: 3
