api:
	$(FSTAR) --explicit_deps --admit_fsi FStar.OrdSet --admit_fsi FStar.OrdMap  --admit_fsi Prins --admit_fsi FStar.IO \
		FStar.Ghost.fst FStar.FunctionalExtensionality.fst FStar.Set.fst FStar.Heap.fst \
		FStar.ST.fst FStar.All.fst FStar.IO.fsti FStar.List.fst FStar.List.Tot.fst \
		FStar.Relational.fst FStar.Comp.fst FStar.RelationalState.fst \
		ordset.fsi ordmap.fsi ../prins.fsi ffi.fst wysteria.fsi \
		wysteria.fst
