api:
	$(FSTAR) --explicit_deps      \
		FStar.Ghost.fst FStar.FunctionalExtensionality.fst FStar.Set.fst FStar.Heap.fst \
		FStar.ST.fst FStar.All.fst FStar.IO.fsti FStar.List.fst FStar.List.Tot.fst \
		FStar.Relational.fst FStar.Comp.fst FStar.RelationalState.fst \
		ordset.fsti ordmap.fsti ../prins.fsi ffi.fst wysteria.fst
