SUBDIRS += bug-reports
SUBDIRS += semiring
SUBDIRS += coercions
SUBDIRS += error-messages
SUBDIRS += tactics
SUBDIRS += ide
SUBDIRS += machine_integers
SUBDIRS += micro-benchmarks
SUBDIRS += prettyprinting
SUBDIRS += projectors
SUBDIRS += typeclasses
SUBDIRS += restricted_includes
SUBDIRS += vale
SUBDIRS += hacl
SUBDIRS += calc
SUBDIRS += friends
SUBDIRS += extraction

# These have special makefiles
SUBDIRS_ALL += simple_hello
SUBDIRS_CLEAN += simple_hello
SUBDIRS_ALL += dune_hello
SUBDIRS_CLEAN += dune_hello
SUBDIRS_ALL += incl
SUBDIRS_CLEAN += incl
SUBDIRS_ALL += extension-lang
SUBDIRS_CLEAN += extension-lang

FSTAR_ROOT ?= ..
include $(FSTAR_ROOT)/mk/test.mk
