FSTAR = ../../bin/fstar.exe

all: noninterference\
		 sample\
		 ro\
		 spdz\

noninterference:
	$(FSTAR) noninterference.fst

sample:
	$(FSTAR) sample.fst

ro:
	$(FSTAR) ro.fst

spdz:
	$(FSTAR) spdz.fst
