FSTAR = ../../bin/fstar.exe

all:
	$(FSTAR) noninterference.fst
	$(FSTAR) sample.fst
	$(FSTAR) ro.fst

noninterference:
	$(FSTAR) noninterference.fst

sample:
	$(FSTAR) sample.fst

ro:
	$(FSTAR) ro.fst
