all: verify

# Assuming share/steel/tests
STEEL_HOME ?= ../../..

# This consumes too much memory (8GB), so disable it for now.
EXCLUDE_FILES=SteelIntroExists.fst

include $(STEEL_HOME)/share/steel/Makefile.include
