#!/usr/bin/env python3
"""Generate FStarC.Parser.Unicode.fst from sedlex's Unicode tables.

The old (sedlex-based) lexer classifies characters using the general
categories shipped with sedlex; we extract the same tables so that the
new lexer classifies characters identically.

Usage: gen_unicode_tables.py path/to/sedlex/unicode.ml > FStarC.Parser.Unicode.fst
"""
import re
import sys

CATEGORIES = ["ll", "lu", "lt", "lo", "lm", "zs", "sm"]


FOOTER = r"""
let hex_digit (c:int) : int =
  if 48 <= c && c <= 57 then c - 48
  else if 97 <= c && c <= 102 then c - 87
  else if 65 <= c && c <= 70 then c - 55
  else -1

(* Decode a table into a flat array [lo0; hi0; lo1; hi1; ...] *)
let decode (s:string) : ML (A.t int) =
  let rec go (cs:list FStar.Char.char) (cur:int) (acc:list int) : ML (list int) =
    match cs with
    | [] -> List.rev (cur :: acc)
    | c :: cs ->
      let c = U.int_of_char c in
      if c = 44 (* , *) || c = 45 (* - *) then go cs 0 (cur :: acc)
      else go cs (cur * 16 + hex_digit c) acc
  in
  A.of_list (go (FStarC.String.list_of_string s) 0 [])

(* Binary search in a decoded table *)
let mem (tbl:A.t int) (c:int) : ML bool =
  let n = U.array_length tbl / 2 in
  let rec go (lo hi:int) : ML bool =
    (* invariant: candidates are ranges in [lo, hi) *)
    if lo >= hi then false
    else
      let mid = (lo + hi) / 2 in
      if c < U.array_index tbl (2 * mid) then go lo mid
      else if c > U.array_index tbl (2 * mid + 1) then go (mid + 1) hi
      else true
  in
  go 0 n

let ll_tbl = decode ll_ranges
let lu_tbl = decode lu_ranges
let lt_tbl = decode lt_ranges
let lo_tbl = decode lo_ranges
let lm_tbl = decode lm_ranges
let zs_tbl = decode zs_ranges
let sm_tbl = decode sm_ranges

let is_ll (c:int) : ML bool = mem ll_tbl c
let is_lu (c:int) : ML bool = mem lu_tbl c
let is_lt (c:int) : ML bool = mem lt_tbl c
let is_lo (c:int) : ML bool = mem lo_tbl c
let is_lm (c:int) : ML bool = mem lm_tbl c
let is_zs (c:int) : ML bool = mem zs_tbl c
let is_sm (c:int) : ML bool = mem sm_tbl c
"""


def main():
    src = open(sys.argv[1]).read()
    m = re.search(r'let version = "([^"]*)"', src)
    version = m.group(1) if m else "?"
    cats = {}
    for cat in CATEGORIES:
        m = re.search(r"let %s = Sedlex_cset.of_list\s*\[([^\]]*)\]" % cat, src)
        if not m:
            sys.exit("category %s not found" % cat)
        pairs = re.findall(r"(0x[0-9a-fA-F]+),\s*(0x[0-9a-fA-F]+)", m.group(1))
        cats[cat] = [(int(a, 16), int(b, 16)) for a, b in pairs]

    out = []
    out.append("(* This file was generated by gen_unicode_tables.py from sedlex's")
    out.append("   Unicode %s tables. Do not edit. *)" % version)
    out.append("module FStarC.Parser.Unicode")
    out.append("")
    out.append("open FStarC.Effect")
    out.append("module A = FStar.ImmutableArray.Base")
    out.append("module U = FStarC.Util")
    out.append("")
    out.append("(* Each table is a string of hexadecimal ranges lo-hi separated by commas. *)")
    for cat in CATEGORIES:
        rs = ",".join("%x-%x" % (a, b) for a, b in cats[cat])
        out.append("let %s_ranges : string =" % cat)
        out.append('  "%s"' % rs)
        out.append("")
    out.append(FOOTER)
    print("\n".join(out))


if __name__ == "__main__":
    main()
