SUBDIRS_ALL += low-star
SUBDIRS_CLEAN += low-star
# SUBDIRS += fstar_and_lowstar
# ^ This has never been enabled, add it? It does need karamel and krmllib.

FSTAR_ROOT ?= ../..
include $(FSTAR_ROOT)/mk/test.mk
