VERFILES=bug22.fst bug19.fst bug29.fst bug26.fst bug15.fst bug25.fst bug24.fst bug28.fst bug35.fst bug52.fst bug23.fst bug21.fst bug96.fst bug77.fst bug92.fst bug62.fst
include ../Makefile.include
all: .all.ver
