VERFILES=bug22.fst bug19.fst bug29.fst bug26.fst bug15.fst bug25.fst bug24.fst bug28.fst bug52.fst bug23.fst bug21.fst bug96.fst bug77.fst bug92.fst bug62.fst bug67.fst bug56.fst bug103.fst bug96.fst bug60.fst bug101.fst bug97b.fst bug122.fst bug170.fst bug178.fst bug179.fst bug195.fst
include ../Makefile.include
all: .all.ver

bug194: bug194.fst
	../../bin/fstar.exe --fstar_home ../.. ../../lib/classical.fst ../../lib/ext.fst ../../lib/constr.fst ../metatheory/stlc_strong_db_parsubst.fst bug194.fst 
