VERFILES=SfBasic SfLists SfPoly
FSTAR_HOME=../..
include ../Makefile.include

all: $(addsuffix .uver, $(VERFILES))

CFSTAR=$(subst CURRENT_DIR,examples/software_foundations,$(CVERFSTAR))
all-cver: $(addsuffix .ucver, $(ALLFILES))
