/* This file auto-generated by KreMLin! */
#ifndef __Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_H
#define __Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_H


#include "Prims.h"
#include "FStar_Mul.h"
#include "FStar_Squash.h"
#include "FStar_StrongExcludedMiddle.h"
#include "FStar_List_Tot.h"
#include "FStar_Classical.h"
#include "FStar_ListProperties.h"
#include "FStar_SeqProperties.h"
#include "FStar_Math_Lemmas.h"
#include "FStar_BitVector.h"
#include "FStar_UInt.h"
#include "FStar_Int.h"
#include "FStar_FunctionalExtensionality.h"
#include "FStar_PropositionalExtensionality.h"
#include "FStar_PredicateExtensionality.h"
#include "FStar_TSet.h"
#include "FStar_Set.h"
#include "FStar_Map.h"
#include "FStar_Ghost.h"
#include "FStar_All.h"
#include "FStar_Bytes.h"
#include "FStar_Buffer.h"
#include "Buffer_Utils.h"
#include "Crypto_Symmetric_Bytes.h"
#include "Crypto_Symmetric_Poly1305_Spec.h"
#include "Crypto_Symmetric_Poly1305_Parameters.h"
#include "Crypto_Symmetric_Poly1305_Bigint.h"
#include "Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part1.h"
#include "Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part2.h"
#include "Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part3.h"
#include "Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part4.h"
#include "kremlib.h"
#include "testlib.h"

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_carry_top_10(
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  uint64_t *b
);

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_mod_6_p(
  Prims_nat b0,
  Prims_nat b1,
  Prims_nat b2,
  Prims_nat b3,
  Prims_nat b4,
  Prims_nat b5,
  Prims_pos p
);

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_carry_top_11(
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  uint64_t *b
);

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_carry_top_1(
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  uint64_t *b
);

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_carry_top_20(
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  uint64_t *b
);

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_carry_top_2(
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  uint64_t *b
);

void Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_div_lt2(Prims_nat a, Prims_pos b);

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_norm_5(FStar_HyperStack_mem h, uint64_t *b);

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_carry_0_to_10(
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  uint64_t *b
);

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_carry_0_to_11(
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  uint64_t *b
);

void
Crypto_Symmetric_Poly1305_Bignum_Lemmas_Part5_lemma_carry_0_to_1(
  FStar_HyperStack_mem h0,
  FStar_HyperStack_mem h1,
  uint64_t *b
);
#endif
