pub fn l0(
    cdi: &mut [u8],
    fwid: &mut [u8],
    deviceID_label_len: u32,
    deviceID_label: &mut [u8],
    aliasKey_label_len: u32,
    aliasKey_label: &mut [u8],
    deviceIDCSR_ingredients: super::l0types::deviceIDCSR_ingredients_t,
    aliasKeyCRT_ingredients: super::l0types::aliasKeyCRT_ingredients_t,
    deviceID_pub: &mut [u8],
    aliasKey_pub: &mut [u8],
    aliasKey_priv: &mut [u8],
    deviceIDCSR_len: u32,
    deviceIDCSR_buf: &mut [u8],
    aliasKeyCRT_len: u32,
    aliasKeyCRT_buf: &mut [u8],
    cdi_repr: (),
    fwid_repr: (),
    deviceID_label_repr: (),
    aliasKey_label_repr: (),
    deviceID_pub_repr: (),
    aliasKey_pub_repr: (),
    aliasKey_priv_repr: (),
    deviceIDCSR_buf_repr: (),
    aliasKeyCRT_buf_repr: (),
) {
}
