FSTAR_HOME=../../..
include ../../Makefile.include

all:	NonTot.fail-uver	\
	Unresolved.fail-uver	\
	Unbound.fail-uver	\
	Ill1.fail-uver		\
	Ill2.fail-uver		\
	NatNeg.fail-uver	\
	LemmaArgs.fail-uver
