VERFILES=../../lib/FStar.FunctionalExtensionality.fst ../../lib/FStar.Relational.fst ../../lib/FStar.Bytes.fst crypto_interface.fst assumptions.fst alice.fsi alice.fst bob.fsi bob.fst ballot_box.fsi ballot_box.fst protocol.fst
include ../Makefile.include
all: .all.ver
