FSTAR_HOME=../..
VERFILES=../../lib/FStar.Relational.fst ../../lib/FStar.Comp.fst ../../lib/FStar.RelationalState.fst ../../lib/FStar.Bytes.fst crypto_interface.fst assumptions.fst alice.fst bob.fst ballot_box.fst protocol.fst
include ../Makefile.include
all: .all.ver
