# This makefile is shared by every sub directory. Whether the 'pos'
# or 'neg' rule is called depends on the parent Makefile, which decides
# from the name of the subdirectory.

FSTAR_ROOT?=../../..
NODEPEND=1
include $(FSTAR_ROOT)/mk/test.mk

# Do not warn about missing checked files in these tests.
OTHERFLAGS += --warn_error -241

check-pos: $(wildcard *.fst)
	$(call msg, "CHECK", $(basename $(notdir $(shell pwd))))
	$(Q)$(FSTAR) $(SIL) Test.fst
	@touch $@

check-neg: $(wildcard *.fst)
	$(call msg, "CHECKFAIL", $(basename $(notdir $(shell pwd))))
	$(Q)! $(FSTAR) $(SIL) Test.fst > error.log 2>&1
	@echo $^ failed as expected
	@touch $@

clean:
	$(Q)rm -f check-neg check-pos
