(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let is_reifiable (env : FStarC_TypeChecker_Env.env) (l : FStarC_Ident.lident) : bool =
  (let tmp = (FStarC_TypeChecker_Util.effect_extraction_mode env l) in
  (match tmp with
    | FStarC_Syntax_Syntax.Extract_reify -> true
    | tmp1 -> false
  ))

let reify_comp (env : FStarC_TypeChecker_Env.env) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (FStarC_TypeChecker_Env.reify_comp env c FStarC_Syntax_Syntax.U_unknown)

let is_erasable (env : FStarC_TypeChecker_Env.env) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : bool =
  (FStarC_TypeChecker_Env.is_erasable_effect env (FStarC_Syntax_Util.comp_effect_name c))

let impure_effect_result (env : FStarC_TypeChecker_Env.env) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option =
  (let tmp = (FStarC_Syntax_Util.head_and_args_full t) in
  (match tmp with
    | (hd, args) -> (let tmp1 = (FStarC_Syntax_Util.un_uinst hd) in
      let tmp2 = (tmp1).FStarC_Syntax_Syntax.n in
      (match tmp2 with
        | (FStarC_Syntax_Syntax.Tm_fvar (fv)) when (FStarC_TypeChecker_Env.fv_has_attr env fv FStarC_Parser_Const.extract_as_impure_effect_lid) -> (match args with
            | ((a, tmp3) :: tmp4) -> (Some (a))
            | [] -> None
          )
        | tmp3 -> None
      ))
  ))

let result_typ (env : FStarC_TypeChecker_Env.env) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let tmp = (is_erasable env c) in
  (if tmp then FStarC_Syntax_Syntax.t_unit else (let r = (FStarC_Syntax_Util.comp_result c) in
  let tmp1 = (impure_effect_result env r) in
  (match tmp1 with
    | (Some (a)) -> a
    | None -> r
  ))))

let of_lid (env : FStarC_TypeChecker_Env.env) (l : FStarC_Ident.lident) : FStarC_Custard_Syntax.eff =
  (let tmp = (if ((FStarC_Ident.lid_equals l FStarC_Parser_Const.effect_GHOST_lid) || (FStarC_Ident.lid_equals l FStarC_Parser_Const.effect_Ghost_lid)) then true else (FStarC_TypeChecker_Env.is_erasable_effect env l)) in
  (if tmp then FStarC_Custard_Syntax.E_Ghost else (if (((FStarC_Ident.lid_equals l FStarC_Parser_Const.effect_PURE_lid) || (FStarC_Ident.lid_equals l FStarC_Parser_Const.effect_Pure_lid)) || (FStarC_Ident.lid_equals l FStarC_Parser_Const.effect_Tot_lid)) then FStarC_Custard_Syntax.E_Pure else (let tmp1 = (FStarC_TypeChecker_Util.effect_extraction_mode env l) in
  (match tmp1 with
    | (FStarC_Syntax_Syntax.Extract_none (reason)) -> (FStarC_Errors.fStarC_Errors_raise_error0__list_document FStarC_Errors_Codes.Error_CustardUnextractableEffect ((FStarC_Errors_Msg.text (Prims.strcat "Custard cannot extract the effect " (Prims.strcat (FStarC_Ident.string_of_lid l) "."))) :: ((FStarC_Errors_Msg.text reason) :: [])))
    | tmp2 -> FStarC_Custard_Syntax.E_Impure
  )))))

let head_is_impure_marker (env : FStarC_TypeChecker_Env.env) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : bool =
  (let tmp = (FStarC_Syntax_Util.head_and_args_full t) in
  (match tmp with
    | (hd, tmp1) -> (let tmp2 = (FStarC_Syntax_Util.un_uinst hd) in
      let tmp3 = (tmp2).FStarC_Syntax_Syntax.n in
      (match tmp3 with
        | (FStarC_Syntax_Syntax.Tm_fvar (fv)) -> (FStarC_TypeChecker_Env.fv_has_attr env fv FStarC_Parser_Const.extract_as_impure_effect_lid)
        | tmp4 -> false
      ))
  ))

let of_comp (env : FStarC_TypeChecker_Env.env) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : FStarC_Custard_Syntax.eff =
  (let e = (of_lid env (FStarC_Syntax_Util.comp_effect_name c)) in
  let tmp = (head_is_impure_marker env (FStarC_Syntax_Util.comp_result c)) in
  (if tmp then FStarC_Custard_Syntax.E_Impure else e))

let reify_steps : (FStarC_TypeChecker_Env.step) list =
  (FStarC_TypeChecker_Env.Inlining :: (FStarC_TypeChecker_Env.ForExtraction :: (FStarC_TypeChecker_Env.Unascribe :: [])))

let rec maybe_reify (env : FStarC_TypeChecker_Env.env) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (l : FStarC_Ident.lident) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let tmp = (is_reifiable env l) in
  let tmp1 = (not tmp) in
  (if tmp1 then t else (let tmp2 = (FStarC_Syntax_Subst.compress t) in
  let tmp3 = (tmp2).FStarC_Syntax_Syntax.n in
  (match tmp3 with
    | (FStarC_Syntax_Syntax.Tm_let ({ FStarC_Syntax_Syntax.lbs = true; lbs1 = lbs; body = body; _ })) -> (let tmp4 = (FStarC_Syntax_Subst.open_let_rec lbs body) in
      (match tmp4 with
        | (lbs1, body1) -> (let env' = (FStarC_List.fold_left (fun env1 lb -> (match (lb).FStarC_Syntax_Syntax.lbname with
              | (FStar_Pervasives.Inl (bv)) -> (FStarC_TypeChecker_Env.push_bv env1 bv)
              | (FStar_Pervasives.Inr (tmp5)) -> env1
            )) env lbs1) in
          let body2 = (maybe_reify env' body1 l) in
          let tmp5 = (FStarC_Syntax_Subst.close_let_rec lbs1 body2) in
          (match tmp5 with
            | (lbs2, body3) -> { FStarC_Syntax_Syntax.n = (FStarC_Syntax_Syntax.Tm_let (({ FStarC_Syntax_Syntax.lbs = true; lbs1 = lbs2; body = body3 } : FStarC_Syntax_Syntax.term'__Tm_let__payload)));
                pos = (t).FStarC_Syntax_Syntax.pos;
                hash_code = (t).FStarC_Syntax_Syntax.hash_code }
          ))
      ))
    | tmp4 -> (let tmp5 = (FStarC_Syntax_Util.mk_reify t (Some (l))) in
      (FStarC_TypeChecker_Util.norm_reify env reify_steps tmp5))
  ))))

