(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let run_tm (m : ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'a * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either))) (ps : (FStarC_Tactics_Types.proofstate ref)) : (string, 'u_'a) FStar_Pervasives.either =
  (let x = (m ((Prims.parse_int "0"), []) ps) in
  (match x with
    | (FStar_Pervasives.Inr ((x1, tmp))) -> (FStar_Pervasives.Inr (x1))
    | s -> (FStar_Pervasives.Inl ((match s with
        | (FStar_Pervasives.Inl (v)) -> v
      )))
  ))

type expr =
  | Lit of Prims.int
  | Atom of Prims.int * FStarC_Reflection_Types.term
  | Plus of expr * expr
  | Mult of expr * expr
  | Minus of expr * expr
  | Land of expr * expr
  | Lxor of expr * expr
  | Lor of expr * expr
  | Ladd of expr * expr
  | Lsub of expr * expr
  | Shl of expr * expr
  | Shr of expr * expr
  | Neg of expr
  | Udiv of expr * expr
  | Umod of expr * expr
  | MulMod of expr * expr
  | NatToBv of expr


let op_let_Bang (m : ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'a * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either))) (f : ('u_'a -> ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'b * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either)))) (i : (Prims.int * (FStarC_Reflection_Types.term) list)) : ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'b * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either) =
  (fun ps -> (let x = (m i ps) in
  ((match x with
    | (FStar_Pervasives.Inr ((x1, j))) -> (f x1 j)
    | s -> (fun tmp -> (FStar_Pervasives.Inl ((match s with
        | (FStar_Pervasives.Inl (v)) -> v
      ))))
  ) ps)))

let return (x : 'u_'a) (i : (Prims.int * (FStarC_Reflection_Types.term) list)) : ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'a * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either) =
  (fun tmp -> (FStar_Pervasives.Inr ((x, i))))

let liftM2 (f : ('u_'a -> ('u_'b -> 'u_'c))) (x : ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'a * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either))) (y : ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'b * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either))) : ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'c * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either)) =
  (op_let_Bang x (fun xx -> (op_let_Bang y (fun yy -> (return (f xx yy))))))

let rec find_idx (f : ('u_'a -> ((FStarC_Tactics_Types.proofstate ref) -> bool))) (l : ('u_'a) list) : ((FStarC_Tactics_Types.proofstate ref) -> ((Prims.int * 'u_'a)) option) =
  (match l with
    | [] -> (fun tmp -> None)
    | (x :: xs) -> (fun ps -> (let x1 = (f x ps) in
      ((if x1 then (fun tmp -> (Some (((Prims.parse_int "0"), x)))) else (fun ps1 -> (let x2 = (find_idx f xs ps1) in
      (match x2 with
        | None -> None
        | (Some ((i, x3))) -> (Some (((Prims.op_Plus i (Prims.parse_int "1")), x3)))
      )))) ps)))
  )

let atom (t : FStarC_Reflection_Types.term) (tmp : (Prims.int * (FStarC_Reflection_Types.term) list)) : ((FStarC_Tactics_Types.proofstate ref) -> (string, (expr * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either) =
  (match tmp with
    | (n, atoms) -> (fun ps -> (let x = (find_idx (fun a -> (fun tmp1 -> (FStar_Reflection_TermEq_Simple.term_eq t a))) atoms ps) in
      (match x with
        | None -> (FStar_Pervasives.Inr (((Atom (n, t)), ((Prims.op_Plus n (Prims.parse_int "1")), (t :: atoms)))))
        | (Some ((i, t1))) -> (FStar_Pervasives.Inr (((Atom ((Prims.op_Minus (Prims.op_Minus n (Prims.parse_int "1")) i), t1)), (n, atoms))))
      )))
  )

let liftM (f : ('u_'a -> 'u_'b)) (x : ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'a * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either))) : ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'b * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either)) =
  (op_let_Bang x (fun xx -> (return (f xx))))

let rec as_arith_expr (t : FStarC_Reflection_Types.term) : ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, (expr * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either)) =
  (let tmp = (FStar_Reflection_V2_Collect.collect_app_ln t) in
  (match tmp with
    | (hd, tl) -> (match (let tmp1 = (FStarC_Reflection_V2_Builtins.inspect_ln hd) in
      (tmp1, tl)) with
        | ((FStarC_Reflection_V2_Data.Tv_FVar (fv)), ((e1, FStarC_Reflection_V2_Data.Q_Implicit) :: ((e2, FStarC_Reflection_V2_Data.Q_Explicit) :: ((e3, FStarC_Reflection_V2_Data.Q_Explicit) :: [])))) -> (let qn = (FStarC_Reflection_V2_Builtins.inspect_fv fv) in
          let e2' = (as_arith_expr e2) in
          let e3' = (as_arith_expr e3) in
          (if ((=) qn FStar_Reflection_Const.land_qn) then (liftM2 (fun u__eta u__eta1 -> (Land (u__eta, u__eta1))) e2' e3') else (if ((=) qn FStar_Reflection_Const.lxor_qn) then (liftM2 (fun u__eta u__eta1 -> (Lxor (u__eta, u__eta1))) e2' e3') else (if ((=) qn FStar_Reflection_Const.lor_qn) then (liftM2 (fun u__eta u__eta1 -> (Lor (u__eta, u__eta1))) e2' e3') else (if ((=) qn FStar_Reflection_Const.shiftr_qn) then (liftM2 (fun u__eta u__eta1 -> (Shr (u__eta, u__eta1))) e2' e3') else (if ((=) qn FStar_Reflection_Const.shiftl_qn) then (liftM2 (fun u__eta u__eta1 -> (Shl (u__eta, u__eta1))) e2' e3') else (if ((=) qn FStar_Reflection_Const.udiv_qn) then (liftM2 (fun u__eta u__eta1 -> (Udiv (u__eta, u__eta1))) e2' e3') else (if ((=) qn FStar_Reflection_Const.umod_qn) then (liftM2 (fun u__eta u__eta1 -> (Umod (u__eta, u__eta1))) e2' e3') else (if ((=) qn FStar_Reflection_Const.mul_mod_qn) then (liftM2 (fun u__eta u__eta1 -> (MulMod (u__eta, u__eta1))) e2' e3') else (if ((=) qn FStar_Reflection_Const.ladd_qn) then (liftM2 (fun u__eta u__eta1 -> (Ladd (u__eta, u__eta1))) e2' e3') else (if ((=) qn FStar_Reflection_Const.lsub_qn) then (liftM2 (fun u__eta u__eta1 -> (Lsub (u__eta, u__eta1))) e2' e3') else (atom t))))))))))))
        | ((FStarC_Reflection_V2_Data.Tv_FVar (fv)), ((l, FStarC_Reflection_V2_Data.Q_Explicit) :: ((r, FStarC_Reflection_V2_Data.Q_Explicit) :: []))) -> (let qn = (FStarC_Reflection_V2_Builtins.inspect_fv fv) in
          let ll = (as_arith_expr l) in
          let rr = (as_arith_expr r) in
          (if ((=) qn FStar_Reflection_Const.add_qn) then (liftM2 (fun u__eta u__eta1 -> (Plus (u__eta, u__eta1))) ll rr) else (if ((=) qn FStar_Reflection_Const.minus_qn) then (liftM2 (fun u__eta u__eta1 -> (Minus (u__eta, u__eta1))) ll rr) else (if ((=) qn FStar_Reflection_Const.mult_qn) then (liftM2 (fun u__eta u__eta1 -> (Mult (u__eta, u__eta1))) ll rr) else (atom t)))))
        | ((FStarC_Reflection_V2_Data.Tv_FVar (fv)), ((l, FStarC_Reflection_V2_Data.Q_Implicit) :: ((r, FStarC_Reflection_V2_Data.Q_Explicit) :: []))) -> (let qn = (FStarC_Reflection_V2_Builtins.inspect_fv fv) in
          let rr = (as_arith_expr r) in
          (if ((=) qn FStar_Reflection_Const.nat_bv_qn) then (liftM (fun u__eta -> (NatToBv (u__eta))) rr) else (atom t)))
        | ((FStarC_Reflection_V2_Data.Tv_FVar (fv)), ((a, FStarC_Reflection_V2_Data.Q_Explicit) :: [])) -> (let qn = (FStarC_Reflection_V2_Builtins.inspect_fv fv) in
          let aa = (as_arith_expr a) in
          (if ((=) qn FStar_Reflection_Const.neg_qn) then (liftM (fun u__eta -> (Neg (u__eta))) aa) else (atom t)))
        | ((FStarC_Reflection_V2_Data.Tv_Const ((FStarC_Reflection_V2_Data.C_Int (i, tmp1)))), tmp2) -> (return (Lit (i)))
        | tmp1 -> (atom t)
      )
  ))

let lift (f : ('u_'a -> ((FStarC_Tactics_Types.proofstate ref) -> 'u_'b))) (x : 'u_'a) (st : (Prims.int * (FStarC_Reflection_Types.term) list)) : ((FStarC_Tactics_Types.proofstate ref) -> (string, ('u_'b * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either) =
  (fun ps -> (let x1 = (f x ps) in
  let x2 = (x1, st) in
  (FStar_Pervasives.Inr (x2))))

let fail (s : string) (i : (Prims.int * (FStarC_Reflection_Types.term) list)) : ((FStarC_Tactics_Types.proofstate ref) -> (string, ('a * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either) =
  (fun tmp -> (FStar_Pervasives.Inl (s)))

let is_arith_expr (t : FStarC_Reflection_Types.term) : ((Prims.int * (FStarC_Reflection_Types.term) list) -> ((FStarC_Tactics_Types.proofstate ref) -> (string, (expr * (Prims.int * (FStarC_Reflection_Types.term) list))) FStar_Pervasives.either)) =
  (op_let_Bang (as_arith_expr t) (fun a -> (match a with
    | (Atom (tmp, t1)) -> (let tmp1 = (FStar_Reflection_V2_Derived_Lemmas.collect_app_ref t1) in
      (match tmp1 with
        | (hd, tl) -> (match (let tmp2 = (FStarC_Reflection_V2_Builtins.inspect_ln hd) in
          (tmp2, tl)) with
            | ((FStarC_Reflection_V2_Data.Tv_FVar (tmp2)), []) -> (return a)
            | ((FStarC_Reflection_V2_Data.Tv_BVar (tmp2)), []) -> (return a)
            | ((FStarC_Reflection_V2_Data.Tv_Var (tmp2)), []) -> (return a)
            | tmp2 -> (op_let_Bang (lift FStarC_Tactics_V2_Builtins.term_to_string t1) (fun s -> (fail (Prims.strcat "not an arithmetic expression: (" (Prims.strcat s ")")))))
          )
      ))
    | tmp -> (return a)
  )))

let rec compare_expr (e1 : expr) (e2 : expr) : FStar_Order.order =
  (match (e1, e2) with
    | ((Lit (i)), (Lit (j))) -> (FStar_Order.compare_int i j)
    | ((Atom (tmp, t)), (Atom (tmp1, s))) -> (FStar_Reflection_V2_Compare.compare_term t s)
    | ((Plus (l1, l2)), (Plus (r1, r2))) -> (FStar_Order.lex (compare_expr l1 r1) (fun tmp -> (compare_expr l2 r2)))
    | ((Minus (l1, l2)), (Minus (r1, r2))) -> (FStar_Order.lex (compare_expr l1 r1) (fun tmp -> (compare_expr l2 r2)))
    | ((Mult (l1, l2)), (Mult (r1, r2))) -> (FStar_Order.lex (compare_expr l1 r1) (fun tmp -> (compare_expr l2 r2)))
    | ((Neg (e11)), (Neg (e21))) -> (compare_expr e11 e21)
    | ((Lit (tmp)), tmp1) -> FStar_Order.Lt
    | (tmp, (Lit (tmp1))) -> FStar_Order.Gt
    | ((Atom (tmp, tmp1)), tmp2) -> FStar_Order.Lt
    | (tmp, (Atom (tmp1, tmp2))) -> FStar_Order.Gt
    | ((Plus (tmp, tmp1)), tmp2) -> FStar_Order.Lt
    | (tmp, (Plus (tmp1, tmp2))) -> FStar_Order.Gt
    | ((Mult (tmp, tmp1)), tmp2) -> FStar_Order.Lt
    | (tmp, (Mult (tmp1, tmp2))) -> FStar_Order.Gt
    | ((Neg (tmp)), tmp1) -> FStar_Order.Lt
    | (tmp, (Neg (tmp1))) -> FStar_Order.Gt
    | tmp -> FStar_Order.Gt
  )

