(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let map (f : ('u___a -> 'u___b)) (o : ('u___a) option) : ('u___b) option =
  (match o with
    | (Some (x)) -> (let tmp = (f x) in
      (Some (tmp)))
    | None -> None
  )

let must (tmp : ('u___a) option) : 'u___a =
  (match tmp with
    | (Some (x)) -> x
    | None -> (FStarC_Effect.failwith "FStarC.Option.must: called on None")
  )

let bind (o : ('u___a) option) (f : ('u___a -> ('u___b) option)) : ('u___b) option =
  (match o with
    | (Some (x)) -> (f x)
    | None -> None
  )

let dflt (d : 'u___a) (tmp : ('u___a) option) : 'u___a =
  (match tmp with
    | (Some (x)) -> x
    | None -> d
  )

let rec find (f : ('u___a -> bool)) (xs : ('u___a) list) : ('u___a) option =
  (match xs with
    | [] -> None
    | (x :: xs1) -> (let tmp = (f x) in
      (if tmp then (Some (x)) else (find f xs1)))
  )

let catch (o : ('u___a) option) (f : (unit -> ('u___a) option)) : ('u___a) option =
  (match o with
    | (Some (x)) -> (Some (x))
    | None -> (f ())
  )

let iter (f : ('u___a -> unit)) (tmp : ('u___a) option) : unit =
  (match tmp with
    | (Some (x)) -> (f x)
    | None -> ()
  )

