(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let write_json (js : FStarC_Json.json) : unit =
  ((FStarC_Format.print_raw (FStarC_Json.string_of_json js));
  (FStarC_Format.print_raw "\n"))

let try_assoc (key : string) (d : ((string * FStarC_Json.json)) list) : (FStarC_Json.json) option =
  (let tmp = (FStarC_Util.try_find (fun tmp -> (match tmp with
      | (k, tmp1) -> ((=) k key)
    )) d) in
  (FStarC_Option.map Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd tmp))

exception InvalidQuery of string

exception UnexpectedJsonType of (string * FStarC_Json.json)

let js_fail (expected : string) (got : FStarC_Json.json) : 'u_'a =
  (raise (UnexpectedJsonType ((expected, got))))

let js_assoc (tmp : FStarC_Json.json) : ((string * FStarC_Json.json)) list =
  (match tmp with
    | (FStarC_Json.JsonAssoc (a)) -> a
    | other -> (js_fail "dictionary" other)
  )

let js_str (tmp : FStarC_Json.json) : string =
  (match tmp with
    | (FStarC_Json.JsonStr (s)) -> s
    | other -> (js_fail "string" other)
  )

let js_int (tmp : FStarC_Json.json) : Prims.int =
  (match tmp with
    | (FStarC_Json.JsonInt (i)) -> i
    | other -> (js_fail "int" other)
  )

let js_bool (tmp : FStarC_Json.json) : bool =
  (match tmp with
    | (FStarC_Json.JsonBool (b)) -> b
    | other -> (js_fail "int" other)
  )

let js_list (k : (FStarC_Json.json -> 'u_'a)) (tmp : FStarC_Json.json) : ('u_'a) list =
  (match tmp with
    | (FStarC_Json.JsonList (l)) -> (FStarC_List.map k l)
    | other -> (js_fail "list" other)
  )

let json_debug (tmp : FStarC_Json.json) : string =
  (match tmp with
    | FStarC_Json.JsonNull -> "null"
    | (FStarC_Json.JsonBool (b)) -> (FStarC_Format.fmt1 "bool (%s)" (if b then "true" else "false"))
    | (FStarC_Json.JsonInt (i)) -> (let tmp1 = (FStarC_Class_Show.fStarC_Class_Show_show__int i) in
      (FStarC_Format.fmt1 "int (%s)" tmp1))
    | (FStarC_Json.JsonStr (s)) -> (FStarC_Format.fmt1 "string (%s)" s)
    | (FStarC_Json.JsonList (tmp1)) -> "list (...)"
    | (FStarC_Json.JsonAssoc (tmp1)) -> "dictionary (...)"
  )

