(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

type real_literal_repr = {
  mantissa : Prims.int;
  exponent : Prims.int;
} [@@deriving yojson]

let rec pow10 (n : Prims.int) : Prims.int =
  (if ((=) n Prims.int_zero) then Prims.int_one else (Prims.op_Star (Prims.of_int (10)) (pow10 (Prims.op_Minus n Prims.int_one))))

let rec ndigits (x : Prims.int) : Prims.int =
  (if (Prims.op_Less x (Prims.of_int (10))) then Prims.int_one else (Prims.op_Plus Prims.int_one (ndigits (Prims.op_Slash x (Prims.of_int (10))))))

let rec zeros (n : Prims.int) (s : string) : string =
  (if ((=) n Prims.int_zero) then s else (zeros (Prims.op_Minus n Prims.int_one) (Prims.strcat "0" s)))

let to_string (r : real_literal_repr) : string =
  (let m = (if (Prims.op_Less (r).mantissa Prims.int_zero) then (Prims.op_Tilde_Minus (r).mantissa) else (r).mantissa) in
  let k = (Prims.op_Tilde_Minus (r).exponent) in
  let p = (pow10 k) in
  let fpart = (Prims.op_Percent m p) in
  let pad = (if (Prims.op_Greater_Equals (ndigits fpart) k) then Prims.int_zero else (Prims.op_Minus k (ndigits fpart))) in
  (Prims.strcat (if (Prims.op_Less (r).mantissa Prims.int_zero) then "-" else "") (Prims.strcat (Prims.string_of_int (Prims.op_Slash m p)) (Prims.strcat "." (if ((=) k Prims.int_zero) then "0" else (zeros pad (Prims.string_of_int fpart)))))))

let compare (r1 : real_literal_repr) (r2 : real_literal_repr) : Prims.int =
  (let e = (if (Prims.op_Less_Equals (r1).exponent (r2).exponent) then (r1).exponent else (r2).exponent) in
  let m1 = (Prims.op_Star (r1).mantissa (pow10 (Prims.op_Minus (r1).exponent e))) in
  let m2 = (Prims.op_Star (r2).mantissa (pow10 (Prims.op_Minus (r2).exponent e))) in
  (if (Prims.op_Less m1 m2) then (Prims.of_int (-1)) else (if ((=) m1 m2) then Prims.int_zero else Prims.int_one)))

let of_int (i : Prims.int) : real_literal_repr =
  { mantissa = i; exponent = Prims.int_zero }

let rec strip (m : Prims.int) (e : Prims.int) : real_literal_repr =
  (if (((=) e Prims.int_zero) || ((<>) (Prims.op_Percent m (Prims.of_int (10))) Prims.int_zero)) then { mantissa = m; exponent = e } else (strip (Prims.op_Slash m (Prims.of_int (10))) (Prims.op_Plus e Prims.int_one)))

let mk (m : Prims.int) (e : Prims.int) : real_literal_repr =
  (if (Prims.op_Greater_Equals e Prims.int_zero) then { mantissa = (Prims.op_Star m (pow10 e)); exponent = Prims.int_zero } else (strip m e))

