(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let iface_only : (unit) FStarC_SMap.t =
  (FStarC_SMap.create (Prims.parse_int "10"))

let loaded_memo : (unit) FStarC_SMap.t =
  (FStarC_SMap.create (Prims.parse_int "100"))

let loaded (env : FStarC_TypeChecker_Env.env) (m : string) (want_impl : bool) : bool =
  (let m1 = (FStarC_String.lowercase m) in
  let key = (Prims.strcat (if want_impl then "!" else "?") m1) in
  let tmp = (FStarC_SMap.try_find loaded_memo key) in
  (match tmp with
    | (Some (())) -> true
    | None -> (let b = (FStarC_List.existsb (fun md -> (((=) (FStarC_String.lowercase (FStarC_Ident.string_of_lid (md).FStarC_Syntax_Syntax.name)) m1) && (not (want_impl && (md).FStarC_Syntax_Syntax.is_interface)))) (FStarC_TypeChecker_Env.modules env)) in
      (if b then (FStarC_SMap.add loaded_memo key ()) else ());
      b)
  ))

let module_is_loaded (deps : FStarC_Parser_Dep.deps) (env : FStarC_TypeChecker_Env.env) (m : string) : bool =
  (let m' = (FStarC_String.lowercase m) in
  let tmp = (FStarC_Parser_Dep.implementation_of deps m') in
  let tmp1 = (match tmp with
      | (Some (v)) -> true
      | tmp1 -> false
    ) in
  let want_impl = (if tmp1 then (let tmp2 = (FStarC_SMap.try_find iface_only m') in
    (match tmp2 with
      | None -> true
      | tmp3 -> false
    )) else false) in
  (loaded env m want_impl))

let candidate_files (deps : FStarC_Parser_Dep.deps) (m : string) : (string) list =
  (let m1 = (FStarC_String.lowercase m) in
  let tmp = (FStarC_Parser_Dep.implementation_of deps m1) in
  let tmp1 = (FStarC_Parser_Dep.interface_of deps m1) in
  let tmp2 = (tmp, tmp1) in
  (match tmp2 with
    | ((Some (i)), (Some (j))) -> (i :: (j :: []))
    | ((Some (i)), None) -> (i :: [])
    | (None, o) -> (match o with
        | (Some (j)) -> (j :: [])
        | None -> []
      )
  ))

let loading : (unit) FStarC_SMap.t =
  (FStarC_SMap.create (Prims.parse_int "100"))

let cache_primed : (unit) FStarC_SMap.t =
  (FStarC_SMap.create (Prims.parse_int "100"))

let rec prime_cache (deps : FStarC_Parser_Dep.deps) (env : FStarC_TypeChecker_Env.env) (fn : string) : unit =
  (let tmp = (FStarC_SMap.try_find cache_primed fn) in
  (match tmp with
    | (Some (tmp1)) -> ()
    | None -> ((FStarC_SMap.add cache_primed fn ());
      let tmp1 = (FStarC_Parser_Dep.is_implementation fn) in
      (if tmp1 then (let tmp2 = (FStarC_Parser_Dep.lowercase_module_name fn) in
      let tmp3 = (FStarC_Parser_Dep.interface_of deps tmp2) in
      (match tmp3 with
        | (Some (i)) -> (prime_cache deps env i)
        | None -> ()
      )) else ());
      let tmp2 = (FStarC_Parser_Dep.deps_of deps fn) in
      (FStarC_List.iter (prime_cache deps env) tmp2);
      (FStarC_Custard_Prof.timed "cachefile" (fun tmp3 -> ((ignore (FStarC_CheckedFiles.load_module_from_cache env fn));
      ()))))
  ))

let rec ensure_loaded__first_usable (deps : FStarC_Parser_Dep.deps) (env : FStarC_TypeChecker_Env.env) (m : string) (fns : (string) list) : (string * FStarC_CheckedFiles.tc_result) =
  (match fns with
    | [] -> (FStarC_Errors.fStarC_Errors_raise_error0__list_document FStarC_Errors_Codes.Error_CustardEntryNotFound ((FStarC_Errors_Msg.text (Prims.strcat "Custard needs module " (Prims.strcat m ", but no usable checked file for it is in the dependency graph."))) :: ((FStarC_Errors_Msg.text "Verify the module first, or pass --already_cached appropriately.") :: [])))
    | (fn :: fns1) -> ((prime_cache deps env fn);
      let tmp = (FStarC_Custard_Prof.timed "cachefile" (fun tmp -> (FStarC_CheckedFiles.load_module_from_cache env fn))) in
      (match tmp with
        | None -> ((ensure_loaded__first_usable deps env m) fns1)
        | (Some (tcr)) -> (fn, tcr)
      ))
  )

let loaded_files : (unit) FStarC_SMap.t =
  (FStarC_SMap.create (Prims.parse_int "100"))

let rec ensure_loaded (deps : FStarC_Parser_Dep.deps) (env : FStarC_TypeChecker_Env.env) (m : string) : FStarC_TypeChecker_Env.env =
  (let tmp = (module_is_loaded deps env m) in
  (if tmp then env else (let tmp1 = (FStarC_SMap.try_find loading (FStarC_String.lowercase m)) in
  let tmp2 = (match tmp1 with
      | (Some (v)) -> true
      | tmp2 -> false
    ) in
  (if tmp2 then env else (let tmp3 = (candidate_files deps m) in
  let tmp4 = ((ensure_loaded__first_usable deps env m) tmp3) in
  (match tmp4 with
    | (fn, tcr) -> ((FStarC_SMap.add loaded_files fn ());
      (FStarC_SMap.add loading (FStarC_String.lowercase m) ());
      let tmp5 = (FStarC_Parser_Dep.deps_of deps fn) in
      let env1 = (FStarC_List.fold_left (fun env1 dfn -> (let dm = (FStarC_Parser_Dep.module_name_of_file dfn) in
        (if ((=) (FStarC_String.lowercase dm) (FStarC_String.lowercase m)) then env1 else (ensure_loaded deps env1 dm)))) env tmp5) in
      (FStarC_SMap.remove loading (FStarC_String.lowercase m));
      let tmp6 = (FStarC_Parser_Dep.is_implementation fn) in
      let tmp7 = (not tmp6) in
      (if tmp7 then (FStarC_SMap.add iface_only (FStarC_String.lowercase m) ()) else ());
      let tmp8 = (FStarC_Parser_Dep.is_implementation fn) in
      let tmp9 = (not tmp8) in
      let tmp10 = (if tmp9 then (loaded env1 m false) else false) in
      (if tmp10 then env1 else (let tmp11 = (FStarC_List.existsb (fun tmp11 -> (match tmp11 with
          | (l, tmp12) -> ((=) (FStarC_String.lowercase (FStarC_Ident.string_of_lid l)) (FStarC_String.lowercase m))
        )) (FStarC_Syntax_DsEnv.open_modules (env1).FStarC_TypeChecker_Env.dsenv)) in
      let dsenv = (if tmp11 then (env1).FStarC_TypeChecker_Env.dsenv else (let tmp12 = (FStarC_ToSyntax_ToSyntax.add_modul_to_env (tcr).FStarC_CheckedFiles.checked_module (tcr).FStarC_CheckedFiles.mii) in
        let tmp13 = (tmp12 (env1).FStarC_TypeChecker_Env.dsenv) in
        (match tmp13 with
          | (tmp14, dsenv) -> dsenv
        ))) in
      let env2 = (FStarC_TypeChecker_Tc.load_checked_module { FStarC_TypeChecker_Env.solver = (env1).FStarC_TypeChecker_Env.solver;
          range = (env1).FStarC_TypeChecker_Env.range;
          curmodule = (env1).FStarC_TypeChecker_Env.curmodule;
          gamma = (env1).FStarC_TypeChecker_Env.gamma;
          gamma_sig = (env1).FStarC_TypeChecker_Env.gamma_sig;
          gamma_cache = (env1).FStarC_TypeChecker_Env.gamma_cache;
          modules = (env1).FStarC_TypeChecker_Env.modules;
          expected_typ = (env1).FStarC_TypeChecker_Env.expected_typ;
          sigtab = (env1).FStarC_TypeChecker_Env.sigtab;
          attrtab = (env1).FStarC_TypeChecker_Env.attrtab;
          instantiate_imp = (env1).FStarC_TypeChecker_Env.instantiate_imp;
          effects = (env1).FStarC_TypeChecker_Env.effects;
          generalize = (env1).FStarC_TypeChecker_Env.generalize;
          letrecs = (env1).FStarC_TypeChecker_Env.letrecs;
          rec_names = (env1).FStarC_TypeChecker_Env.rec_names;
          top_level = (env1).FStarC_TypeChecker_Env.top_level;
          check_uvars = (env1).FStarC_TypeChecker_Env.check_uvars;
          use_eq_strict = (env1).FStarC_TypeChecker_Env.use_eq_strict;
          is_iface = (env1).FStarC_TypeChecker_Env.is_iface;
          admit = (env1).FStarC_TypeChecker_Env.admit;
          phase1 = (env1).FStarC_TypeChecker_Env.phase1;
          failhard = (env1).FStarC_TypeChecker_Env.failhard;
          flychecking = (env1).FStarC_TypeChecker_Env.flychecking;
          uvar_subtyping = (env1).FStarC_TypeChecker_Env.uvar_subtyping;
          intactics = (env1).FStarC_TypeChecker_Env.intactics;
          nocoerce = (env1).FStarC_TypeChecker_Env.nocoerce;
          tc_term = (env1).FStarC_TypeChecker_Env.tc_term;
          typeof_tot_or_gtot_term = (env1).FStarC_TypeChecker_Env.typeof_tot_or_gtot_term;
          universe_of = (env1).FStarC_TypeChecker_Env.universe_of;
          typeof_well_typed_tot_or_gtot_term = (env1).FStarC_TypeChecker_Env.typeof_well_typed_tot_or_gtot_term;
          teq_nosmt_force = (env1).FStarC_TypeChecker_Env.teq_nosmt_force;
          subtype_nosmt_force = (env1).FStarC_TypeChecker_Env.subtype_nosmt_force;
          qtbl_name_and_index = (env1).FStarC_TypeChecker_Env.qtbl_name_and_index;
          qtbl_name_and_index1 = (env1).FStarC_TypeChecker_Env.qtbl_name_and_index1;
          fv_delta_depths = (env1).FStarC_TypeChecker_Env.fv_delta_depths;
          proof_ns = (env1).FStarC_TypeChecker_Env.proof_ns;
          synth_hook = (env1).FStarC_TypeChecker_Env.synth_hook;
          try_solve_implicits_hook = (env1).FStarC_TypeChecker_Env.try_solve_implicits_hook;
          splice = (env1).FStarC_TypeChecker_Env.splice;
          mpreprocess = (env1).FStarC_TypeChecker_Env.mpreprocess;
          postprocess = (env1).FStarC_TypeChecker_Env.postprocess;
          identifier_info = (env1).FStarC_TypeChecker_Env.identifier_info;
          tc_hooks = (env1).FStarC_TypeChecker_Env.tc_hooks;
          dsenv = dsenv;
          nbe = (env1).FStarC_TypeChecker_Env.nbe;
          strict_args_tab = (env1).FStarC_TypeChecker_Env.strict_args_tab;
          disc_proj_tab = (env1).FStarC_TypeChecker_Env.disc_proj_tab;
          erasable_types_tab = (env1).FStarC_TypeChecker_Env.erasable_types_tab;
          enable_defer_to_tac = (env1).FStarC_TypeChecker_Env.enable_defer_to_tac;
          unif_allow_ref_guards = (env1).FStarC_TypeChecker_Env.unif_allow_ref_guards;
          erase_erasable_args = (env1).FStarC_TypeChecker_Env.erase_erasable_args;
          core_check = (env1).FStarC_TypeChecker_Env.core_check;
          missing_decl = (env1).FStarC_TypeChecker_Env.missing_decl;
          iface_todo = (env1).FStarC_TypeChecker_Env.iface_todo;
          iface_hidden = (env1).FStarC_TypeChecker_Env.iface_hidden;
          iface_lids = (env1).FStarC_TypeChecker_Env.iface_lids;
          iface_val_lids = (env1).FStarC_TypeChecker_Env.iface_val_lids } (tcr).FStarC_CheckedFiles.checked_module) in
      (if ((tcr).FStarC_CheckedFiles.checked_module).FStarC_Syntax_Syntax.is_interface then env2 else (FStarC_List.fold_left (fun env3 se -> (let env4 = (FStarC_TypeChecker_Env.push_sigelt_force env3 se) in
      (FStarC_List.iter (fun l -> ((ignore (FStarC_TypeChecker_Env.lookup_sigelt env4 l));
      ())) (FStarC_Syntax_Util.lids_of_sigelt se));
      env4)) env2 ((tcr).FStarC_CheckedFiles.checked_module).FStarC_Syntax_Syntax.declarations)))))
  ))))))

let loaded_digests (tmp : unit) : ((string * string)) list =
  (let tmp1 = (FStarC_SMap.keys loaded_files) in
  (FStarC_List.map (fun fn -> (let tmp2 = (FStarC_Util.digest_of_file fn) in
  (fn, tmp2))) tmp1))

