(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let on_sort_binder (f : (FStarC_Reflection_Types.term -> ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_Types.term))) (b : FStarC_Reflection_Types.binder) (ps : (FStarC_Tactics_Types.proofstate ref)) : FStarC_Reflection_Types.binder =
  (let x = (FStarC_Reflection_V2_Builtins.inspect_binder b) in
  let tmp = ((x : FStarC_Reflection_V2_Data.binder_view)).FStarC_Reflection_V2_Data.sort in
  let x1 = (f tmp ps) in
  let tmp1 = (x).FStarC_Reflection_V2_Data.qual in
  let tmp2 = (x).FStarC_Reflection_V2_Data.attrs in
  let tmp3 = ((x : FStarC_Reflection_V2_Data.binder_view)).FStarC_Reflection_V2_Data.ppname in
  let x2 = ({ FStarC_Reflection_V2_Data.sort = x1;
      qual = tmp1;
      attrs = tmp2;
      ppname = tmp3 } : FStarC_Reflection_V2_Data.binder_view) in
  (FStarC_Reflection_V2_Builtins.pack_binder x2))

let on_sort_simple_binder (f : (FStarC_Reflection_Types.term -> ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_Types.term))) (b : FStarC_Syntax_Syntax.binder) (ps : (FStarC_Tactics_Types.proofstate ref)) : FStarC_Syntax_Syntax.binder =
  (let x = (FStarC_Reflection_V2_Builtins.inspect_binder b) in
  let tmp = ((x : FStarC_Reflection_V2_Data.binder_view)).FStarC_Reflection_V2_Data.sort in
  let x1 = (f tmp ps) in
  let tmp1 = (x).FStarC_Reflection_V2_Data.qual in
  let tmp2 = (x).FStarC_Reflection_V2_Data.attrs in
  let tmp3 = ((x : FStarC_Reflection_V2_Data.binder_view)).FStarC_Reflection_V2_Data.ppname in
  let x2 = ({ FStarC_Reflection_V2_Data.sort = x1;
      qual = tmp1;
      attrs = tmp2;
      ppname = tmp3 } : FStarC_Reflection_V2_Data.binder_view) in
  (FStarC_Reflection_V2_Builtins.pack_binder x2))

let rec visit_flag (ff : (FStarC_Reflection_Types.term -> ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_Types.term))) (f : FStarC_Reflection_V2_Data.cflag) : ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_V2_Data.cflag) =
  (match f with
    | (FStarC_Reflection_V2_Data.SMTPAT (t)) -> (fun ps -> (let x = (visit_tm ff t ps) in
      (FStarC_Reflection_V2_Data.SMTPAT (x))))
    | (FStarC_Reflection_V2_Data.DECREASES ((FStarC_Reflection_V2_Data.Decreases_lex (ts)))) -> (fun ps -> (let x = (FStar_Tactics_Util.map (visit_tm ff) ts ps) in
      let x1 = (FStarC_Reflection_V2_Data.Decreases_lex (x)) in
      (FStarC_Reflection_V2_Data.DECREASES (x1))))
    | (FStarC_Reflection_V2_Data.DECREASES ((FStarC_Reflection_V2_Data.Decreases_wf (rel, e)))) -> (fun ps -> (let x = (visit_tm ff rel ps) in
      let x1 = (visit_tm ff e ps) in
      (FStarC_Reflection_V2_Data.DECREASES ((FStarC_Reflection_V2_Data.Decreases_wf (x, x1))))))
  )

and visit_comp (ff : (FStarC_Reflection_Types.term -> ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_Types.term))) (c : FStarC_Reflection_Types.comp) (ps : (FStarC_Tactics_Types.proofstate ref)) : FStarC_Reflection_Types.comp =
  (let x = (FStarC_Reflection_V2_Builtins.inspect_comp c) in
  let tmp = (x).FStarC_Reflection_V2_Data.result_typ in
  let x1 = (visit_tm ff tmp ps) in
  let tmp1 = (x).FStarC_Reflection_V2_Data.flags in
  let x2 = (FStar_Tactics_Util.map (visit_flag ff) tmp1 ps) in
  let tmp2 = (x).FStarC_Reflection_V2_Data.effect_name in
  let tmp3 = (x).FStarC_Reflection_V2_Data.source_effect_name in
  let x3 = { FStarC_Reflection_V2_Data.effect_name = tmp2;
      result_typ = x1;
      flags = x2;
      source_effect_name = tmp3 } in
  (FStarC_Reflection_V2_Builtins.pack_comp x3))

and visit_pat (ff : (FStarC_Reflection_Types.term -> ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_Types.term))) (p : FStarC_Reflection_V2_Data.pattern) : ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_V2_Data.pattern) =
  (match p with
    | (FStarC_Reflection_V2_Data.Pat_Constant (tmp)) -> (fun tmp1 -> p)
    | (FStarC_Reflection_V2_Data.Pat_Var (v, s)) -> (fun tmp -> (FStarC_Reflection_V2_Data.Pat_Var (v, s)))
    | (FStarC_Reflection_V2_Data.Pat_Cons (head, univs, subpats)) -> (fun ps -> (let x = (FStar_Tactics_Util.map (fun tmp -> (match tmp with
          | (p1, b) -> (fun ps1 -> (let x = (visit_pat ff p1 ps1) in
            (x, b)))
        )) subpats ps) in
      (FStarC_Reflection_V2_Data.Pat_Cons (head, univs, x))))
    | (FStarC_Reflection_V2_Data.Pat_Dot_Term (t)) -> (fun ps -> (let x = (FStar_Tactics_Util.map_opt (visit_tm ff) t ps) in
      (FStarC_Reflection_V2_Data.Pat_Dot_Term (x))))
  )

and visit_br (ff : (FStarC_Reflection_Types.term -> ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_Types.term))) (b : (FStarC_Reflection_V2_Data.pattern * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) : ((FStarC_Tactics_Types.proofstate ref) -> (FStarC_Reflection_V2_Data.pattern * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) =
  (fun ps -> ((match b with
    | (p, t) -> (fun ps1 -> (let x = (visit_pat ff p ps1) in
      let x1 = (visit_tm ff t ps1) in
      (x, x1)))
  ) ps))

and visit_tm (ff : (FStarC_Reflection_Types.term -> ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_Types.term))) (t : FStarC_Reflection_Types.term) : ((FStarC_Tactics_Types.proofstate ref) -> FStarC_Reflection_Types.term) =
  (fun ps -> (let x = (FStarC_Reflection_V2_Builtins.inspect_ln t) in
  let x1 = ((match x with
      | (FStarC_Reflection_V2_Data.Tv_FVar (tmp)) -> (fun tmp1 -> x)
      | (FStarC_Reflection_V2_Data.Tv_Var (tmp)) -> (fun tmp1 -> x)
      | (FStarC_Reflection_V2_Data.Tv_BVar (tmp)) -> (fun tmp1 -> x)
      | (FStarC_Reflection_V2_Data.Tv_UInst (tmp, tmp1)) -> (fun tmp2 -> x)
      | (FStarC_Reflection_V2_Data.Tv_Type (u)) -> (fun tmp -> (FStarC_Reflection_V2_Data.Tv_Type (u)))
      | (FStarC_Reflection_V2_Data.Tv_Const (c)) -> (fun tmp -> (FStarC_Reflection_V2_Data.Tv_Const (c)))
      | (FStarC_Reflection_V2_Data.Tv_Uvar (i, u)) -> (fun tmp -> (FStarC_Reflection_V2_Data.Tv_Uvar (i, u)))
      | FStarC_Reflection_V2_Data.Tv_Unknown -> (fun tmp -> FStarC_Reflection_V2_Data.Tv_Unknown)
      | FStarC_Reflection_V2_Data.Tv_Unsupp -> (fun tmp -> FStarC_Reflection_V2_Data.Tv_Unsupp)
      | (FStarC_Reflection_V2_Data.Tv_Arrow (b, c)) -> (fun ps1 -> (let x1 = (on_sort_binder (visit_tm ff) b ps1) in
        let x2 = (visit_comp ff c ps1) in
        (FStarC_Reflection_V2_Data.Tv_Arrow (x1, x2))))
      | (FStarC_Reflection_V2_Data.Tv_Abs (b, t1)) -> (fun ps1 -> (let x1 = (on_sort_binder (visit_tm ff) b ps1) in
        let x2 = (visit_tm ff t1 ps1) in
        (FStarC_Reflection_V2_Data.Tv_Abs (x1, x2))))
      | (FStarC_Reflection_V2_Data.Tv_App (l, (r, q))) -> (fun ps1 -> (let x1 = (visit_tm ff l ps1) in
        let x2 = (visit_tm ff r ps1) in
        (FStarC_Reflection_V2_Data.Tv_App (x1, (x2, q)))))
      | (FStarC_Reflection_V2_Data.Tv_Refine (b, r)) -> (fun ps1 -> (let x1 = (on_sort_simple_binder (visit_tm ff) b ps1) in
        let x2 = (visit_tm ff r ps1) in
        (FStarC_Reflection_V2_Data.Tv_Refine (x1, x2))))
      | (FStarC_Reflection_V2_Data.Tv_Let (r, attrs, b, def, t1)) -> (fun ps1 -> (let x1 = (on_sort_simple_binder (visit_tm ff) b ps1) in
        let x2 = (visit_tm ff def ps1) in
        let x3 = (visit_tm ff t1 ps1) in
        (FStarC_Reflection_V2_Data.Tv_Let (r, attrs, x1, x2, x3))))
      | (FStarC_Reflection_V2_Data.Tv_Match (sc, ret_opt, brs)) -> (fun ps1 -> (let x1 = (visit_tm ff sc ps1) in
        let x2 = (FStar_Tactics_Util.map_opt (fun tmp -> (match tmp with
            | (b, asc) -> (fun ps2 -> (let x2 = (on_sort_binder (visit_tm ff) b ps2) in
              let x3 = ((match asc with
                  | ((FStar_Pervasives.Inl (t1)), tacopt, use_eq) -> (fun ps3 -> (let x3 = (visit_tm ff t1 ps3) in
                    let x4 = (FStar_Pervasives.Inl (x3)) in
                    let x5 = (FStar_Tactics_Util.map_opt (visit_tm ff) tacopt ps3) in
                    (x4, x5, use_eq)))
                  | ((FStar_Pervasives.Inr (c)), tacopt, use_eq) -> (fun ps3 -> (let x3 = (visit_comp ff c ps3) in
                    let x4 = (FStar_Pervasives.Inr (x3)) in
                    let x5 = (FStar_Tactics_Util.map_opt (visit_tm ff) tacopt ps3) in
                    (x4, x5, use_eq)))
                ) ps2) in
              (x2, x3)))
          )) ret_opt ps1) in
        let x3 = (FStar_Tactics_Util.map (visit_br ff) brs ps1) in
        (FStarC_Reflection_V2_Data.Tv_Match (x1, x2, x3))))
      | (FStarC_Reflection_V2_Data.Tv_AscribedT (e, t1, topt, use_eq)) -> (fun ps1 -> (let x1 = (visit_tm ff e ps1) in
        let x2 = (visit_tm ff t1 ps1) in
        (FStarC_Reflection_V2_Data.Tv_AscribedT (x1, x2, topt, use_eq))))
      | (FStarC_Reflection_V2_Data.Tv_AscribedC (e, c, topt, use_eq)) -> (fun ps1 -> (let x1 = (visit_tm ff e ps1) in
        let x2 = (visit_comp ff c ps1) in
        (FStarC_Reflection_V2_Data.Tv_AscribedC (x1, x2, topt, use_eq))))
    ) ps) in
  let tmp = (FStarC_Reflection_V2_Builtins.pack_ln x1) in
  (ff tmp ps)))

