(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let process_args (tmp : unit) : (FStarC_Getopt.parse_cmdline_res * (string) list) =
  (FStarC_Options.parse_cmd_line ())

let print_stats (tmp : unit) : unit =
  (let tmp1 = (!(FStarC_Stats.ever_enabled)) in
  (if tmp1 then (let tmp2 = (FStarC_Stats.print_all ()) in
  (FStarC_Format.print1_error "Stats:\n%s\n" tmp2)) else ()))

let set_error_trap (tmp : unit) : unit =
  ((ignore (FStarC_Util.get_sigint_handler ()));
  let h' = (fun s -> ((FStarC_Util.kill_all ());
    (FStarC_Debug.enable ());
    (FStarC_Options.set_option "error_contexts" (FStarC_Options.Bool (true)));
    (FStarC_Errors.fStarC_Errors_diag__range_list_document FStarC_Range_Type.dummyRange ((FStarC_Errors_Msg.text "GOT SIGINT! Exiting") :: []));
    (print_stats ());
    (FStarC_Effect.exit (Prims.parse_int "1")))) in
  (FStarC_Util.set_sigint_handler (FStarC_Util.sigint_handler_f h')))

let print_help_for (o : string) : unit =
  (let tmp = (FStarC_Options.help_for_option o) in
  (match tmp with
    | None -> ((FStarC_Format.print_string "Use `--help` to see all available options.\n");
      ())
    | (Some (doc)) -> (let tmp1 = (FStarC_Errors_Msg.renderdoc doc) in
      (FStarC_Format.print_error tmp1))
  ))

let load_native_tactics (tmp : unit) : unit =
  (let tmp1 = (FStarC_Options.load ()) in
  let modules_to_load = (FStarC_List.map FStarC_Ident.lid_of_str tmp1) in
  let tmp2 = (FStarC_Options.load_cmxs ()) in
  let cmxs_to_load = (FStarC_List.map FStarC_Ident.lid_of_str tmp2) in
  let ml_module_name = (fun m -> (FStarC_Extraction_ML_Util.ml_module_name_of_lid m)) in
  let ml_file = (fun m -> (let tmp3 = (ml_module_name m) in
    (Prims.strcat tmp3 ".ml"))) in
  let cmxs_file = (fun m -> (let tmp3 = (ml_module_name m) in
    let cmxs = (Prims.strcat tmp3 ".cmxs") in
    let tmp4 = (FStarC_Find.find_file_odir cmxs) in
    (match tmp4 with
      | (Some (f)) -> f
      | None -> (if (FStarC_List.contains m cmxs_to_load) then (FStarC_Errors.fStarC_Errors_raise_error0__string FStarC_Errors_Codes.Fatal_FailToCompileNativeTactic (FStarC_Format.fmt1 "Could not find %s to load" cmxs)) else (let tmp5 = (ml_file m) in
        let tmp6 = (FStarC_Find.find_file_odir tmp5) in
        (match tmp6 with
          | None -> (let tmp7 = (ml_file m) in
            let tmp8 = (FStarC_Format.fmt1 "Extracted module %s not found." tmp7) in
            let tmp9 = (FStarC_Errors_Msg.text tmp8) in
            let tmp10 = (tmp9 :: []) in
            let tmp11 = ((FStarC_Errors_Msg.text "Failed to compile native tactic.") :: tmp10) in
            (FStarC_Errors.fStarC_Errors_raise_error0__list_document FStarC_Errors_Codes.Fatal_FailToCompileNativeTactic tmp11))
          | (Some (ml)) -> (let dir = (FStarC_Filepath.dirname ml) in
            let tmp7 = (ml_module_name m) in
            let tmp8 = (tmp7 :: []) in
            (FStarC_Plugins.compile_modules dir tmp8);
            let tmp9 = (FStarC_Find.find_file_odir cmxs) in
            (match tmp9 with
              | None -> (FStarC_Errors.fStarC_Errors_raise_error0__list_document FStarC_Errors_Codes.Fatal_FailToCompileNativeTactic ((FStarC_Errors_Msg.text "Failed to compile native tactic.") :: ((FStarC_Errors_Msg.text (FStarC_Format.fmt1 "Compilation seemingly succeeded, but compiled object %s not found." cmxs)) :: [])))
              | (Some (f)) -> f
            ))
        )))
    ))) in
  let cmxs_files = (FStarC_List.map cmxs_file (FStarC_List.op_At modules_to_load cmxs_to_load)) in
  (FStarC_Plugins.load_plugins cmxs_files);
  let tmp3 = (FStarC_Options.use_native_tactics ()) in
  (FStarC_Option.iter FStarC_Plugins.load_plugins_dir tmp3);
  ())

let finished_message (fmods : ((bool * FStarC_Ident.lident)) list) (errs : Prims.int) : unit =
  (let print_to = (if (Prims.op_Greater errs (Prims.parse_int "0")) then FStarC_Format.print_error else FStarC_Format.print_string) in
  let tmp = (FStarC_Options.silent ()) in
  let tmp1 = (not tmp) in
  (if tmp1 then ((FStarC_List.iter (fun tmp2 -> (match tmp2 with
    | (iface, name) -> (let tag = (if iface then "i'face (or impl+i'face)" else "module") in
      let tmp3 = (FStarC_Options.should_print_message (FStarC_Ident.string_of_lid name)) in
      (if tmp3 then (print_to (FStarC_Format.fmt2 "Verified %s: %s\n" tag (FStarC_Ident.string_of_lid name))) else ()))
  )) fmods);
  (if (Prims.op_Greater errs (Prims.parse_int "0")) then (if ((=) errs (Prims.parse_int "1")) then (FStarC_Format.print_error "1 error was reported (see above)\n") else (let tmp2 = (FStarC_Class_Show.fStarC_Class_Show_show__int errs) in
  (FStarC_Format.print1_error "%s errors were reported (see above)\n" tmp2))) else (FStarC_Format.print1 "%s\n" (FStarC_Format.colorize_bold "All verification conditions discharged successfully")))) else ()))

let cleanup (tmp : unit) : unit =
  (FStarC_Util.kill_all ())

let report_errors (fmods : ((bool * FStarC_Ident.lident)) list) : unit =
  ((ignore (FStarC_Errors.report_all ()));
  let nerrs = (FStarC_Errors.get_err_count ()) in
  (if (Prims.op_Greater nerrs (Prims.parse_int "0")) then ((finished_message fmods nerrs);
  (print_stats ());
  (cleanup ());
  (FStarC_Effect.exit (Prims.parse_int "1"))) else ()))

let fstar_files : (((string) list) option ref) =
  (ref None)

let friends_of_implementation (fn : string) : (FStarC_Ident.lident) list =
  (let tmp = (FStarC_Parser_Driver.parse_file fn) in
  (match tmp with
    | (ast, tmp1) -> (FStarC_List.collect (fun d -> (match (d).FStarC_Parser_AST.d with
        | (FStarC_Parser_AST.Friend (l)) -> (let tmp2 = (FStarC_Ident.lid_of_str (FStarC_String.lowercase (FStarC_Ident.string_of_lid l))) in
          (tmp2 :: []))
        | tmp2 -> []
      )) (FStarC_Parser_AST.decls_of_modul ast))
  ))

let go_normal (tmp : unit) : unit =
  (let tmp1 = (process_args ()) in
  (match tmp1 with
    | (res, filenames0) -> (let tmp2 = (FStarC_Options.output_to ()) in
      let tmp3 = (match tmp2 with
          | (Some (v)) -> true
          | tmp3 -> false
        ) in
      let tmp4 = (if tmp3 then (let tmp4 = (FStarC_Options.dep ()) in
        let tmp5 = (match tmp4 with
            | (Some (v)) -> true
            | tmp5 -> false
          ) in
        (not tmp5)) else false) in
      let tmp5 = (if tmp4 then (Prims.op_Greater (FStarC_List.length filenames0) (Prims.parse_int "1")) else false) in
      (if tmp5 then (FStarC_Errors.fStarC_Errors_raise_error0__list_document FStarC_Errors_Codes.Fatal_OptionsNotCompatible ((FStarC_Errors_Msg.text "When using -o, you can only provide a single file in the\n        command line (except for dependency analysis).") :: [])) else ());
      let chopsuf = (fun suf s -> (if (FStarC_Util.ends_with s suf) then (let tmp6 = (FStarC_String.substring s (Prims.parse_int "0") (Prims.op_Minus (FStarC_String.length s) (FStarC_String.length suf))) in
        (Some (tmp6))) else None)) in
      let checked_of = (fun f -> (chopsuf ".checked" f)) in
      let filenames = (FStarC_List.map (fun f -> (if (not (FStarC_Filepath.file_exists f)) then f else (let tmp6 = (checked_of f) in
        (match tmp6 with
          | (Some (f')) -> (let tmp7 = (FStarC_Debug.any ()) in
            (if tmp7 then (FStarC_Format.print1 "Rewriting argument file %s to its source file\n" f) else ());
            let tmp8 = (FStarC_Find.find_file (FStarC_Filepath.basename f')) in
            (match tmp8 with
              | (Some (r)) -> r
              | None -> (let tmp9 = (FStarC_Effect.failwith "Couldn't find source for file") in
                (Prims.strcat tmp9 (Prims.strcat f' "!\n")))
            ))
          | None -> f
        )))) filenames0) in
      let tmp6 = (FStarC_Debug.high ()) in
      (if tmp6 then (let tmp7 = (FStarC_Class_Show.fStarC_Class_Show_show__list_string filenames0) in
      let tmp8 = (FStarC_Class_Show.fStarC_Class_Show_show__list_string filenames) in
      (FStarC_Format.print2 "Rewrote\n%s\ninto\n%s\n\n" tmp7 tmp8)) else ());
      let tmp7 = (FStarC_Find.get_odir ()) in
      (FStarC_Option.iter (FStarC_Util.mkdir false true) tmp7);
      let tmp8 = (FStarC_Find.get_cache_dir ()) in
      (FStarC_Option.iter (FStarC_Util.mkdir false true) tmp8);
      let check_no_filenames = (fun opt -> (if (match filenames with
          | (hd :: tl) -> true
          | tmp9 -> false
        ) then ((FStarC_Format.print1_error "error: No filenames should be passed with option %s\n" opt);
        (FStarC_Effect.exit (Prims.parse_int "1"))) else ())) in
      let tmp9 = (FStarC_Options.trace_error ()) in
      (if tmp9 then (set_error_trap ()) else ());
      (match res with
        | tmp10 when (FStarC_Options.help ()) -> ((FStarC_Options.display_usage ());
          (FStarC_Effect.exit (Prims.parse_int "0")))
        | FStarC_Getopt.Empty -> (let tmp10 = (!(FStarC_Options.u__version)) in
          (FStarC_Format.print1 "F* version %s\n" tmp10);
          (FStarC_Format.print1 "Usage: %s [options] file.fst\n" FStarC_Util.argv0);
          (FStarC_Format.print_string "Use `--help` to see all available options.\n");
          (FStarC_Effect.exit (Prims.parse_int "1")))
        | (FStarC_Getopt.Error ((msg, opt))) -> ((FStarC_Format.print_error (Prims.strcat "error: " msg));
          (print_help_for opt);
          (FStarC_Effect.exit (Prims.parse_int "1")))
        | FStarC_Getopt.Success when (FStarC_Options.print_cache_version ()) -> (let tmp10 = (FStarC_Class_Show.fStarC_Class_Show_show__int FStarC_CheckedFiles.cache_version_number) in
          (FStarC_Format.print1 "F* cache version number: %s\n" tmp10);
          (FStarC_Effect.exit (Prims.parse_int "0")))
        | FStarC_Getopt.Success when (let tmp10 = (FStarC_Options.dep ()) in
        ((<>) tmp10 None)) -> ((load_native_tactics ());
          let tmp10 = (FStarC_Parser_Dep.collect filenames FStarC_CheckedFiles.load_parsing_data_from_cache) in
          (match tmp10 with
            | (tmp11, deps) -> ((FStarC_Parser_Dep.print deps);
              (report_errors []))
          ))
        | FStarC_Getopt.Success when (let tmp10 = (FStarC_Options.print ()) in
        (if tmp10 then true else (FStarC_Options.print_in_place ()))) -> (let tmp10 = (FStarC_Options.print ()) in
          let printing_mode = (if tmp10 then FStarC_Prettyprint.FromTempToStdout else FStarC_Prettyprint.FromTempToFile) in
          (FStarC_Prettyprint.generate printing_mode filenames))
        | FStarC_Getopt.Success when (let tmp10 = (FStarC_Options.read_checked_file ()) in
        (match tmp10 with
          | (Some (v)) -> true
          | tmp11 -> false
        )) -> (let tmp10 = (FStarC_Options.read_checked_file ()) in
          let path = (match tmp10 with
              | (Some (v)) -> v
            ) in
          let tmp11 = (FStarC_Parser_Dep.empty_deps filenames) in
          (ignore (FStarC_Universal.init_env tmp11));
          let res1 = (FStarC_CheckedFiles.load_tc_result path) in
          (match res1 with
            | None -> (FStarC_Errors.fStarC_Errors_raise_error0__list_document FStarC_Errors_Codes.Fatal_ModuleOrFileNotFound ((FStar_Pprint.op_Hat_Slash_Hat (FStarC_Errors_Msg.text "Could not read checked file:") (FStar_Pprint.doc_of_string path)) :: []))
            | (Some ((deps, tcr))) -> (let tmp12 = (FStarC_Class_Show.fStarC_Class_Show_show__list_tuple2_string_string deps) in
              (FStarC_Format.print1 "Deps: %s\n" tmp12);
              let tmp13 = (FStarC_Syntax_DsEnv.fStarC_Class_Show_show__module_inclusion_info (tcr).FStarC_CheckedFiles.mii) in
              (FStarC_Format.print1 "Inclusion info: %s\n" tmp13);
              let tmp14 = (FStarC_Syntax_Print.fStarC_Class_Show_show__modul (tcr).FStarC_CheckedFiles.checked_module) in
              (FStarC_Format.print1 "Checked module: %s\n" tmp14);
              let tmp15 = (((tcr).FStarC_CheckedFiles.smt_encoding).FStarC_SMTEncoding_Env.me_decls ()) in
              let tmp16 = (FStarC_SMTEncoding_Term.fStarC_Class_Show_show__list_decls_elt tmp15) in
              (FStarC_Format.print1 "SMT decls: %s\n" tmp16);
              let tmp17 = (FStarC_SMTEncoding_Env.fStarC_Class_Show_show__list_fvar_binding ((tcr).FStarC_CheckedFiles.smt_encoding).FStarC_SMTEncoding_Env.me_fvbs) in
              (FStarC_Format.print1 "SMT fvars: %s\n" tmp17))
          ))
        | FStarC_Getopt.Success when (let tmp10 = (FStarC_Options.read_krml_file ()) in
        (match tmp10 with
          | (Some (v)) -> true
          | tmp11 -> false
        )) -> (let tmp10 = (FStarC_Options.read_krml_file ()) in
          let path = (match tmp10 with
              | (Some (v)) -> v
            ) in
          let tmp11 = (FStarC_Util.load_value_from_file path) in
          (match tmp11 with
            | None -> (FStarC_Errors.fStarC_Errors_raise_error0__list_document FStarC_Errors_Codes.Fatal_ModuleOrFileNotFound ((FStar_Pprint.op_Hat_Slash_Hat (FStarC_Errors_Msg.text "Could not read krml file:") (FStar_Pprint.doc_of_string path)) :: []))
            | (Some ((version, files))) -> (let tmp12 = (FStarC_Class_Show.fStarC_Class_Show_show__int version) in
              (FStarC_Format.print1 "Karamel format version: %s\n" tmp12);
              (FStarC_List.iter (fun tmp13 -> (match tmp13 with
                | (name, decls) -> ((FStarC_Format.print1 "%s:\n" name);
                  (FStarC_List.iter (fun d -> (let tmp14 = (FStarC_Extraction_KrmlAst.fStarC_Class_Show_show__decl_157 d) in
                  (FStarC_Format.print1 "%s\n\n" tmp14))) decls))
              )) files))
          ))
        | FStarC_Getopt.Success when (FStarC_Options.list_plugins ()) -> ((load_native_tactics ());
          let ps = (FStarC_TypeChecker_Cfg.list_plugins ()) in
          let ts = (FStarC_Tactics_Interpreter.native_tactics_steps ()) in
          let tmp10 = (FStarC_List.map (fun p -> (let tmp10 = (FStarC_Ident.fStarC_Class_Show_show__lident (p).FStarC_TypeChecker_Primops_Base.name) in
            (Prims.strcat "  " tmp10))) ps) in
          let tmp11 = (FStarC_String.concat "\n" tmp10) in
          (FStarC_Format.print1 "Registered plugins:\n%s\n" tmp11);
          let tmp12 = (FStarC_List.map (fun p -> (let tmp12 = (FStarC_Ident.fStarC_Class_Show_show__lident (p).FStarC_TypeChecker_Primops_Base.name) in
            (Prims.strcat "  " tmp12))) ts) in
          let tmp13 = (FStarC_String.concat "\n" tmp12) in
          (FStarC_Format.print1 "Registered tactic plugins:\n%s\n" tmp13);
          ())
        | FStarC_Getopt.Success when (let tmp10 = (FStarC_Options.expand_include ()) in
        (match tmp10 with
          | (Some (v)) -> true
          | tmp11 -> false
        )) -> (let tmp10 = (FStarC_Options.expand_include ()) in
          (match tmp10 with
            | (Some (d)) -> (let ds = (FStarC_Find.expand_include_d d) in
              (FStarC_List.iter (fun s -> (FStarC_Format.print_string (Prims.strcat (FStarC_Filepath.canonicalize s) "\n"))) ds);
              (FStarC_Effect.exit (Prims.parse_int "0")))
          ))
        | FStarC_Getopt.Success when (FStarC_Options.locate ()) -> ((check_no_filenames "--locate");
          let tmp10 = (FStarC_Find.locate ()) in
          (FStarC_Format.print1 "%s\n" tmp10);
          (FStarC_Effect.exit (Prims.parse_int "0")))
        | FStarC_Getopt.Success when (FStarC_Options.locate_lib ()) -> ((check_no_filenames "--locate_lib");
          let tmp10 = (FStarC_Find.locate_lib ()) in
          (match tmp10 with
            | None -> ((FStarC_Format.print_error "No library found (is --no_default_includes set?)\n");
              (FStarC_Effect.exit (Prims.parse_int "1")))
            | (Some (s)) -> ((FStarC_Format.print1 "%s\n" s);
              (FStarC_Effect.exit (Prims.parse_int "0")))
          ))
        | FStarC_Getopt.Success when (FStarC_Options.locate_ocaml ()) -> ((check_no_filenames "--locate_ocaml");
          let tmp10 = (FStarC_Find.locate_ocaml ()) in
          (FStarC_Format.print1 "%s\n" tmp10);
          (FStarC_Effect.exit (Prims.parse_int "0")))
        | FStarC_Getopt.Success when (let tmp10 = (FStarC_Options.locate_file ()) in
        (match tmp10 with
          | (Some (v)) -> true
          | tmp11 -> false
        )) -> ((check_no_filenames "--locate_file");
          let tmp10 = (FStarC_Options.locate_file ()) in
          let f = (match tmp10 with
              | (Some (v)) -> v
            ) in
          let tmp11 = (FStarC_Find.find_file f) in
          (match tmp11 with
            | None -> ((FStarC_Format.print1_error "File %s was not found in include path.\n" f);
              (FStarC_Effect.exit (Prims.parse_int "1")))
            | (Some (fn)) -> (let tmp12 = (FStarC_Filepath.normalize_file_path fn) in
              (FStarC_Format.print1 "%s\n" tmp12);
              (FStarC_Effect.exit (Prims.parse_int "0")))
          ))
        | FStarC_Getopt.Success when (let tmp10 = (FStarC_Options.locate_z3 ()) in
        (match tmp10 with
          | (Some (v)) -> true
          | tmp11 -> false
        )) -> ((check_no_filenames "--locate_z3");
          let tmp10 = (FStarC_Options.locate_z3 ()) in
          let v = (match tmp10 with
              | (Some (v)) -> v
            ) in
          let tmp11 = (FStarC_Find_Z3.locate_z3 v) in
          (match tmp11 with
            | None -> ((FStarC_Errors.fStarC_Errors_log_issue0__list_document FStarC_Errors_Codes.Error_Z3InvocationError (FStarC_List.op_At ((FStarC_Errors_Msg.text (FStarC_Format.fmt1 "Z3 version ‘%s’ was not found." v)) :: []) (FStarC_Find_Z3.z3_install_suggestion v)));
              (report_errors []);
              (FStarC_Effect.exit (Prims.parse_int "1")))
            | (Some (fn)) -> ((FStarC_Format.print1 "%s\n" fn);
              (FStarC_Effect.exit (Prims.parse_int "0")))
          ))
        | FStarC_Getopt.Success when (FStarC_Options.dump_ast ()) -> ((FStarC_List.iter (fun fn -> (let tmp10 = (FStarC_Parser_Driver.parse_file fn) in
          (match tmp10 with
            | (ast, tmp11) -> (let tmp12 = (FStarC_Parser_AST.fStarC_Class_PP_pp__modul ast) in
              let tmp13 = (FStar_Pprint.render tmp12) in
              (FStarC_Format.print2 "Parsed %s:\n%s\n\n" fn tmp13))
          ))) filenames);
          (FStarC_Effect.exit (Prims.parse_int "0")))
        | FStarC_Getopt.Success -> (((fstar_files) := (Some (filenames)));
          let tmp10 = (FStarC_Debug.any ()) in
          (if tmp10 then (let tmp11 = (!(FStarC_Options.u__version)) in
          let tmp12 = (!(FStarC_Options.u__commit)) in
          let tmp13 = (FStarC_Platform_Base.kernel ()) in
          (FStarC_Format.print3 "- F* version %s -- %s (on %s)\n" tmp11 tmp12 tmp13);
          (FStarC_Format.print1 "- Executable: %s\n" FStarC_Util.exec_name);
          let tmp14 = (FStarC_Find.lib_root ()) in
          let tmp15 = (FStarC_Option.dflt "<none>" tmp14) in
          (FStarC_Format.print1 "- Library root: %s\n" tmp15);
          let tmp16 = (FStarC_Find.full_include_path ()) in
          let tmp17 = (FStarC_Class_Show.fStarC_Class_Show_show__list_string tmp16) in
          (FStarC_Format.print1 "- Full include path: %s\n" tmp17);
          (FStarC_Format.print_string "\n");
          ()) else ());
          (FStarC_Syntax_Unionfind.set_ro ());
          (load_native_tactics ());
          let tmp11 = (FStarC_Options.interactive ()) in
          (if tmp11 then ((FStarC_Syntax_Unionfind.set_rw ());
          (match filenames with
            | [] -> ((FStarC_Errors.fStarC_Errors_log_issue0__string FStarC_Errors_Codes.Error_MissingFileName "--ide: Name of current file missing in command line invocation\n");
              (FStarC_Effect.exit (Prims.parse_int "1")))
            | (tmp12 :: (tmp13 :: tmp14)) -> ((FStarC_Errors.fStarC_Errors_log_issue0__string FStarC_Errors_Codes.Error_TooManyFiles "--ide: Too many files in command line invocation\n");
              (FStarC_Effect.exit (Prims.parse_int "1")))
            | (filename :: []) -> (FStarC_Interactive_Ide.interactive_mode filename)
          )) else ((if (match filenames with
            | [] -> true
            | tmp12 -> false
          ) then (FStarC_Errors.fStarC_Errors_raise_error0__string FStarC_Errors_Codes.Error_MissingFileName "No file provided") else ());
          let tmp12 = (FStarC_Parser_Dep.fly_deps_enabled ()) in
          let tmp13 = (if tmp12 then (match filenames with
              | (fn :: []) -> (let m = (FStarC_Parser_Dep.lowercase_module_name fn) in
                (FStarC_Options.add_verify_module m);
                let default_flydeps = (fun tmp13 -> (let deps = (FStarC_Parser_Dep.empty_deps (fn :: [])) in
                  let tmp14 = (FStarC_Parser_Dep.is_implementation fn) in
                  let filenames1 = (if tmp14 then (let tmp15 = (friends_of_implementation fn) in
                    (FStarC_Parser_Dep.set_root_friends tmp15);
                    let tmp16 = (FStarC_Parser_Dep.interface_of deps m) in
                    (match tmp16 with
                      | None -> (fn :: [])
                      | (Some (iface)) -> (let tmp17 = (FStarC_Options.output_to ()) in
                        let tmp18 = (match tmp17 with
                            | None -> true
                            | tmp18 -> false
                          ) in
                        let tmp19 = (if tmp18 then (let tmp19 = (FStarC_CheckedFiles.scan_deps_and_check_cache_validity iface) in
                          (match tmp19 with
                            | (Some (v)) -> true
                            | tmp20 -> false
                          )) else false) in
                        (if tmp19 then (fn :: []) else (iface :: (fn :: []))))
                    )) else (fn :: [])) in
                  (filenames1, deps, true))) in
                let tmp13 = (FStarC_Options.force ()) in
                (if tmp13 then (default_flydeps ()) else (let tmp14 = (FStarC_CheckedFiles.scan_deps_and_check_cache_validity fn) in
                (match tmp14 with
                  | (Some ((files, deps))) -> (files, deps, false)
                  | None -> (default_flydeps ())
                ))))
              | tmp13 -> (FStarC_Errors.fStarC_Errors_raise_error0__string FStarC_Errors_Codes.Error_TooManyFiles "When using --ext fly_deps, only one file can be provided.")
            ) else (let tmp13 = (FStarC_Dependencies.find_deps_if_needed filenames FStarC_CheckedFiles.load_parsing_data_from_cache) in
            (match tmp13 with
              | (files, deps) -> (files, deps, false)
            ))) in
          (match tmp13 with
            | (filenames1, dep_graph, fly_deps) -> (let tmp14 = (FStarC_Universal.batch_mode_tc fly_deps filenames1 dep_graph) in
              (match tmp14 with
                | (tcrs, env, cleanup_) -> ((ignore (cleanup_ env));
                  let module_names = (FStarC_List.map (fun tcr -> (FStarC_Universal.module_or_interface_name (tcr).FStarC_CheckedFiles.checked_module)) tcrs) in
                  (report_errors module_names);
                  (finished_message module_names (Prims.parse_int "0")))
              ))
          ))))
      ))
  ))

let go (tmp : unit) : unit =
  (let args = (FStarC_Util.get_cmd_args ()) in
  (match args with
    | (tmp1 :: ("--ocamlenv" :: [])) -> (let new_ocamlpath = (FStarC_OCaml.new_ocamlpath ()) in
      (FStarC_Format.print1 "OCAMLPATH='%s'; export OCAMLPATH;\n" (FStarC_OCaml.shellescape new_ocamlpath));
      (FStarC_Effect.exit (Prims.parse_int "0")))
    | (tmp1 :: ("--ocamlenv" :: (cmd :: args1))) -> (FStarC_OCaml.exec_in_ocamlenv cmd args1)
    | (tmp1 :: ("--ocamlc" :: rest)) -> (FStarC_OCaml.exec_ocamlc rest)
    | (tmp1 :: ("--ocamlopt" :: rest)) -> (FStarC_OCaml.exec_ocamlopt rest)
    | (tmp1 :: ("--ocamlopt_plugin" :: rest)) -> (FStarC_OCaml.exec_ocamlopt_plugin rest)
    | tmp1 -> (go_normal ())
  ))

let handle_error (e : exn) : unit =
  ((if (FStarC_Errors.handleable e) then (FStarC_Errors.err_exn e) else (let tmp = (FStarC_Util.message_of_exn e) in
  (FStarC_Format.print1_error "Unexpected error: %s\n" tmp);
  let tmp1 = (FStarC_Options.trace_error ()) in
  (if tmp1 then (let tmp2 = (FStarC_Util.trace_of_exn e) in
  (FStarC_Format.print1_error "Trace:\n%s\n" tmp2)) else (FStarC_Format.print_error "Please file a bug report, ideally with a minimized version of the source program that triggered the error.\n"))));
  (report_errors []))

let main (tmp : unit) : unit =
  (try (let tmp1 = (FStarC_Timing.record_ms go) in
  (match tmp1 with
    | (tmp2, time) -> (let tmp3 = (FStarC_Options.query_stats ()) in
      (if tmp3 then (let tmp4 = (FStarC_Class_Show.fStarC_Class_Show_show__int time) in
      let tmp5 = (FStarC_Getopt.cmdline ()) in
      let tmp6 = (FStarC_String.concat " " tmp5) in
      (FStarC_Format.print2_error "TOTAL TIME %s ms: %s\n" tmp4 tmp6)) else ());
      (print_stats ());
      (cleanup ());
      (FStarC_Effect.exit (Prims.parse_int "0")))
  )) with
    | u__cexn -> ((handle_error u__cexn);
      (print_stats ());
      (FStarC_Effect.exit (Prims.parse_int "1")))
  )

