(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let open_comb (r : FStarC_Range_Type.range) (n : Prims.int) (mname : FStarC_Ident.lident) (name : string) (ts : ((FStarC_Ident.ident) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) : ((FStarC_Ident.ident) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (match ts with
    | (us, t) -> (if (match us with
        | [] -> true
        | tmp -> false
      ) then (let tmp = (if ((=) n (Prims.parse_int "1")) then (let tmp = (FStarC_Syntax_Syntax.new_univ_name (Some (r))) in
        (tmp :: [])) else (let tmp = (FStarC_Syntax_Syntax.new_univ_name (Some (r))) in
        let tmp1 = (FStarC_Syntax_Syntax.new_univ_name (Some (r))) in
        let tmp2 = (tmp1 :: []) in
        (tmp :: tmp2))) in
      (tmp, t)) else (if ((=) (FStarC_List.length us) n) then (FStarC_Syntax_Subst.open_univ_vars us t) else (let tmp = (FStarC_Class_Show.fStarC_Class_Show_show__int n) in
      let tmp1 = (FStarC_Class_Show.fStarC_Class_Show_show__int_4 (FStarC_List.length us)) in
      let tmp2 = (FStarC_Format.fmt4 "The '%s' combinator of effect %s must be polymorphic in exactly %s universe(s), but it has %s" name (FStarC_Ident.string_of_lid mname) tmp tmp1) in
      (FStarC_Errors.fStarC_Errors_raise_error__range_string r FStarC_Errors_Codes.Fatal_UnexpectedEffect tmp2))))
  )

let u_type (r : FStarC_Range_Type.range) (u : FStarC_Ident.ident) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (FStarC_Syntax_Syntax.mk (FStarC_Syntax_Syntax.Tm_type ((FStarC_Syntax_Syntax.U_name (u)))) r)

let check_comb (env : FStarC_TypeChecker_Env.env) (us : (FStarC_Ident.ident) list) (expected : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : ((FStarC_Ident.ident) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (let env1 = (FStarC_TypeChecker_Env.push_univ_vars env us) in
  let t1 = (FStarC_TypeChecker_TcTerm.tc_check_trivial_guard env1 t expected) in
  let tmp = (FStarC_Syntax_Subst.close_univ_vars us t1) in
  (us, tmp))

let repr_app (repr_ts : ((FStarC_Ident.ident) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) (u : FStarC_Ident.ident) (a : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (r : FStarC_Range_Type.range) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let tmp = (FStarC_TypeChecker_Env.inst_tscheme_with repr_ts ((FStarC_Syntax_Syntax.U_name (u)) :: [])) in
  (match tmp with
    | (tmp1, repr) -> (FStarC_Syntax_Syntax.mk_Tm_app repr ((FStarC_Syntax_Syntax.as_arg a) :: []) r)
  ))

let check_total_repr (env : FStarC_TypeChecker_Env.env) (mname : FStarC_Ident.lident) (repr_ts : ((FStarC_Ident.ident) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) (r : FStarC_Range_Type.range) : unit =
  (match repr_ts with
    | (us, tmp) -> (let u_a = (FStarC_List.hd us) in
      let env1 = (FStarC_TypeChecker_Env.push_univ_vars env us) in
      let tmp1 = (u_type r u_a) in
      let bv_a = (FStarC_Syntax_Syntax.new_bv (Some (r)) tmp1) in
      let env2 = (FStarC_TypeChecker_Env.push_bv env1 bv_a) in
      let tmp2 = (FStarC_Syntax_Syntax.bv_to_name bv_a) in
      let t = (repr_app repr_ts u_a tmp2 r) in
      let t1 = (FStarC_TypeChecker_Normalize.normalize (FStarC_TypeChecker_Env.Beta :: (FStarC_TypeChecker_Env.Eager_unfolding :: ((FStarC_TypeChecker_Env.UnfoldUntil (FStarC_Syntax_Syntax.delta_constant)) :: []))) env2 t) in
      let tmp3 = (FStarC_Syntax_Subst.compress t1) in
      let t2 = (FStarC_Syntax_Util.unascribe tmp3) in
      (match (t2).FStarC_Syntax_Syntax.n with
        | (FStarC_Syntax_Syntax.Tm_arrow (tmp4)) -> (let tmp5 = (FStarC_Syntax_Util.arrow_formals_comp_ln t2) in
          (match tmp5 with
            | (tmp6, c) -> (let tmp7 = (FStarC_Syntax_Util.is_total_comp c) in
              let tmp8 = (not tmp7) in
              (if tmp8 then (let tmp9 = (FStarC_Ident.fStarC_Class_Show_show__lident (FStarC_Syntax_Util.comp_effect_name c)) in
              let tmp10 = (FStarC_Format.fmt2 "Effect %s is marked total, but its representation is a function into %s" (FStarC_Ident.string_of_lid mname) tmp9) in
              (FStarC_Errors.fStarC_Errors_raise_error__range_string r FStarC_Errors_Codes.Fatal_UnexpectedEffect tmp10)) else ()))
          ))
        | tmp4 -> ()
      ))
  )

let repr_universe (env : FStarC_TypeChecker_Env.env) (repr_ts : ((FStarC_Ident.ident) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) (r : FStarC_Range_Type.range) : ((FStarC_Ident.ident) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (match repr_ts with
    | (us, tmp) -> (let u_a = (FStarC_List.hd us) in
      let env1 = (FStarC_TypeChecker_Env.push_univ_vars env us) in
      let tmp1 = (u_type r u_a) in
      let bv_a = (FStarC_Syntax_Syntax.new_bv (Some (r)) tmp1) in
      let env2 = (FStarC_TypeChecker_Env.push_bv env1 bv_a) in
      let tmp2 = (FStarC_Syntax_Syntax.bv_to_name bv_a) in
      let tmp3 = (repr_app repr_ts u_a tmp2 r) in
      let u = (FStarC_TypeChecker_TcTerm.universe_of env2 tmp3) in
      let tmp4 = (FStarC_Syntax_Syntax.mk (FStarC_Syntax_Syntax.Tm_type (u)) r) in
      let tmp5 = (FStarC_Syntax_Subst.close_univ_vars (u_a :: []) tmp4) in
      ((u_a :: []), tmp5))
  )

let tc_eff_decl (env : FStarC_TypeChecker_Env.env) (ed : FStarC_Syntax_Syntax.eff_decl) (quals : (FStarC_Syntax_Syntax.qualifier) list) (u__attrs : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) list) : FStarC_Syntax_Syntax.eff_decl =
  (match (ed).FStarC_Syntax_Syntax.combinators with
    | None -> ed
    | (Some (combs)) -> (let r = (FStarC_Ident.range_of_lid (ed).FStarC_Syntax_Syntax.mname) in
      let tmp = (open_comb r (Prims.parse_int "1") (ed).FStarC_Syntax_Syntax.mname "repr" (combs).FStarC_Syntax_Syntax.repr) in
      let repr_ts = (match tmp with
          | (us, t) -> (let u_a = (FStarC_List.hd us) in
            let tmp1 = (u_type r u_a) in
            let tmp2 = (FStarC_Syntax_Syntax.new_bv (Some (r)) tmp1) in
            let b_a = (FStarC_Syntax_Syntax.mk_binder tmp2) in
            let tmp3 = (FStarC_Syntax_Util.type_u ()) in
            (match tmp3 with
              | (t_r, tmp4) -> (let tmp5 = (FStarC_Syntax_Syntax.mk_Total t_r) in
                let expected = (FStarC_Syntax_Util.arrow (b_a :: []) tmp5) in
                (check_comb env us expected t))
            ))
        ) in
      let tmp1 = (open_comb r (Prims.parse_int "1") (ed).FStarC_Syntax_Syntax.mname "return" (combs).FStarC_Syntax_Syntax.return_repr) in
      let return_ts = (match tmp1 with
          | (us, t) -> (let u_a = (FStarC_List.hd us) in
            let tmp2 = (u_type r u_a) in
            let bv_a = (FStarC_Syntax_Syntax.new_bv (Some (r)) tmp2) in
            let a = (FStarC_Syntax_Syntax.bv_to_name bv_a) in
            let tmp3 = (FStarC_Syntax_Syntax.null_binder a) in
            let tmp4 = (tmp3 :: []) in
            let tmp5 = ((FStarC_Syntax_Syntax.mk_binder bv_a) :: tmp4) in
            let tmp6 = (repr_app repr_ts u_a a r) in
            let tmp7 = (FStarC_Syntax_Syntax.mk_Total tmp6) in
            let expected = (FStarC_Syntax_Util.arrow tmp5 tmp7) in
            (check_comb env us expected t))
        ) in
      let tmp2 = (open_comb r (Prims.parse_int "2") (ed).FStarC_Syntax_Syntax.mname "bind" (combs).FStarC_Syntax_Syntax.bind_repr) in
      let bind_ts = (match tmp2 with
          | (us, t) -> (let tmp3 = ((FStarC_List.hd us), (FStarC_List.hd (FStarC_List.tl us))) in
            (match tmp3 with
              | (u_a, u_b) -> (let tmp4 = (u_type r u_a) in
                let bv_a = (FStarC_Syntax_Syntax.new_bv (Some (r)) tmp4) in
                let tmp5 = (u_type r u_b) in
                let bv_b = (FStarC_Syntax_Syntax.new_bv (Some (r)) tmp5) in
                let a = (FStarC_Syntax_Syntax.bv_to_name bv_a) in
                let b = (FStarC_Syntax_Syntax.bv_to_name bv_b) in
                let repr_b = (repr_app repr_ts u_b b r) in
                let tmp6 = (FStarC_Syntax_Syntax.null_binder a) in
                let tmp7 = (tmp6 :: []) in
                let tmp8 = (FStarC_Syntax_Syntax.mk_Total repr_b) in
                let k = (FStarC_Syntax_Util.arrow tmp7 tmp8) in
                let tmp9 = (repr_app repr_ts u_a a r) in
                let tmp10 = (FStarC_Syntax_Syntax.null_binder tmp9) in
                let tmp11 = (FStarC_Syntax_Syntax.null_binder k) in
                let tmp12 = (tmp11 :: []) in
                let tmp13 = (tmp10 :: tmp12) in
                let tmp14 = ((FStarC_Syntax_Syntax.mk_binder bv_b) :: tmp13) in
                let tmp15 = ((FStarC_Syntax_Syntax.mk_binder bv_a) :: tmp14) in
                let tmp16 = (FStarC_Syntax_Syntax.mk_Total repr_b) in
                let expected = (FStarC_Syntax_Util.arrow tmp15 tmp16) in
                (check_comb env us expected t))
            ))
        ) in
      (if (FStarC_List.contains FStarC_Syntax_Syntax.TotalEffect quals) then (check_total_repr env (ed).FStarC_Syntax_Syntax.mname repr_ts r) else ());
      let tmp3 = (repr_universe env repr_ts r) in
      let tmp4 = { FStarC_Syntax_Syntax.repr = repr_ts;
          return_repr = return_ts;
          bind_repr = bind_ts;
          repr_universe = tmp3 } in
      let tmp5 = (Some (tmp4)) in
      { FStarC_Syntax_Syntax.mname = (ed).FStarC_Syntax_Syntax.mname;
        cattributes = (ed).FStarC_Syntax_Syntax.cattributes;
        combinators = tmp5;
        eff_attrs = (ed).FStarC_Syntax_Syntax.eff_attrs;
        extraction_mode = (ed).FStarC_Syntax_Syntax.extraction_mode })
  )

let tc_lift (env : FStarC_TypeChecker_Env.env) (sub : FStarC_Syntax_Syntax.sub_eff) (r : FStarC_Range_Type.range) : FStarC_Syntax_Syntax.sub_eff =
  ((ignore (FStarC_TypeChecker_Env.get_effect_decl env (sub).FStarC_Syntax_Syntax.source));
  let ed_tgt = (FStarC_TypeChecker_Env.get_effect_decl env (sub).FStarC_Syntax_Syntax.target) in
  let lift = (match (sub).FStarC_Syntax_Syntax.lift with
      | None -> ((if ((match (ed_tgt).FStarC_Syntax_Syntax.combinators with
          | (Some (v)) -> true
          | tmp -> false
        ) && (not ((((FStarC_Syntax_Util.is_pure_effect (sub).FStarC_Syntax_Syntax.source) || (FStarC_Syntax_Util.is_div_effect (sub).FStarC_Syntax_Syntax.source)) || (FStarC_Syntax_Util.is_ndet_effect (sub).FStarC_Syntax_Syntax.source)) || (FStarC_Syntax_Util.is_ghost_effect (sub).FStarC_Syntax_Syntax.source)))) then (FStarC_Errors.fStarC_Errors_raise_error__range_string r FStarC_Errors_Codes.Fatal_UnexpectedEffect (FStarC_Format.fmt2 "Effect %s has a representation, so the lift from %s must be given explicitly: only a pure, ghost, nondeterministic or divergent computation can be lifted with the target's return combinator" (FStarC_Ident.string_of_lid (sub).FStarC_Syntax_Syntax.target) (FStarC_Ident.string_of_lid (sub).FStarC_Syntax_Syntax.source))) else ());
        None)
      | (Some (ts)) -> (let repr_ts = (match (FStarC_Syntax_Util.get_eff_repr ed_tgt) with
            | (Some (repr)) -> repr
            | None -> (FStarC_Errors.fStarC_Errors_raise_error__range_string r FStarC_Errors_Codes.Fatal_UnexpectedEffect (FStarC_Format.fmt1 "Effect %s has no representation, so it cannot be the target of a lift with a term" (FStarC_Ident.string_of_lid (sub).FStarC_Syntax_Syntax.target)))
          ) in
        let tmp = (open_comb r (Prims.parse_int "1") (sub).FStarC_Syntax_Syntax.target "lift" ts) in
        (match tmp with
          | (us, t) -> (let u_a = (FStarC_List.hd us) in
            let tmp1 = (u_type r u_a) in
            let bv_a = (FStarC_Syntax_Syntax.new_bv (Some (r)) tmp1) in
            let a = (FStarC_Syntax_Syntax.bv_to_name bv_a) in
            let tmp2 = (FStarC_TypeChecker_Env.effect_decl_opt env (sub).FStarC_Syntax_Syntax.source) in
            let src_arg = (match tmp2 with
                | (Some ((ed_src, tmp3))) when (match (ed_src).FStarC_Syntax_Syntax.combinators with
                  | (Some (v)) -> true
                  | tmp4 -> false
                ) -> (let tmp4 = (FStarC_Option.must (FStarC_Syntax_Util.get_eff_repr ed_src)) in
                  (repr_app tmp4 u_a a r))
                | tmp3 -> (let c = (FStarC_Syntax_Syntax.mk_Comp { FStarC_Syntax_Syntax.effect_name = (sub).FStarC_Syntax_Syntax.source;
                      result_typ = a;
                      flags = [];
                      source_effect_name = (sub).FStarC_Syntax_Syntax.source }) in
                  let tmp4 = (FStarC_Syntax_Syntax.null_binder FStarC_Syntax_Syntax.t_unit) in
                  let tmp5 = (tmp4 :: []) in
                  (FStarC_Syntax_Util.arrow tmp5 c))
              ) in
            let tmp3 = (FStarC_Syntax_Syntax.null_binder src_arg) in
            let tmp4 = (tmp3 :: []) in
            let tmp5 = ((FStarC_Syntax_Syntax.mk_binder bv_a) :: tmp4) in
            let tmp6 = (repr_app repr_ts u_a a r) in
            let tmp7 = (FStarC_Syntax_Syntax.mk_Total tmp6) in
            let expected = (FStarC_Syntax_Util.arrow tmp5 tmp7) in
            let tmp8 = (check_comb env us expected t) in
            (Some (tmp8)))
        ))
    ) in
  { FStarC_Syntax_Syntax.source = (sub).FStarC_Syntax_Syntax.source;
    target = (sub).FStarC_Syntax_Syntax.target;
    lift = lift })

