(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

type eq_result =
  | Equal
  | NotEqual
  | Unknown


let eq_inj (r : eq_result) (s : eq_result) : eq_result =
  (match (r, s) with
    | (Equal, Equal) -> Equal
    | (NotEqual, tmp) -> NotEqual
    | (tmp, NotEqual) -> NotEqual
    | (tmp, tmp1) -> Unknown
  )

let equal_if (tmp : bool) : eq_result =
  (if tmp then Equal else Unknown)

let eq_and (r : eq_result) (s : (unit -> eq_result)) : eq_result =
  (let tmp = (if ((=) r Equal) then (let tmp = (s ()) in
    ((=) tmp Equal)) else false) in
  (if tmp then Equal else Unknown))

let equal_iff (tmp : bool) : eq_result =
  (if tmp then Equal else NotEqual)

let injectives : (string) list =
  ("FStar.Int8.int_to_t" :: ("FStar.Int16.int_to_t" :: ("FStar.Int32.int_to_t" :: ("FStar.Int64.int_to_t" :: ("FStar.Int128.int_to_t" :: ("FStar.UInt8.uint_to_t" :: ("FStar.UInt16.uint_to_t" :: ("FStar.UInt32.uint_to_t" :: ("FStar.UInt64.uint_to_t" :: ("FStar.UInt128.uint_to_t" :: ("FStar.SizeT.uint_to_t" :: ("FStar.Int8.__int_to_t" :: ("FStar.Int16.__int_to_t" :: ("FStar.Int32.__int_to_t" :: ("FStar.Int64.__int_to_t" :: ("FStar.Int128.__int_to_t" :: ("FStar.UInt8.__uint_to_t" :: ("FStar.UInt16.__uint_to_t" :: ("FStar.UInt32.__uint_to_t" :: ("FStar.UInt64.__uint_to_t" :: ("FStar.UInt128.__uint_to_t" :: ("FStar.SizeT.__uint_to_t" :: []))))))))))))))))))))))

let rec eq_args (env : FStarC_TypeChecker_Env.env) (t1 : (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax * (FStarC_Syntax_Syntax.arg_qualifier) option)) list) (t2 : (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax * (FStarC_Syntax_Syntax.arg_qualifier) option)) list) : eq_result =
  (match (t1, t2) with
    | ([], []) -> Equal
    | (((a, tmp) :: a1), ((b, tmp1) :: b1)) -> (let tmp2 = (eq_tm env a b) in
      (match tmp2 with
        | Equal -> (eq_args env a1 b1)
        | tmp3 -> Unknown
      ))
    | tmp -> Unknown
  )

and branch_matches (env : FStarC_TypeChecker_Env.env) (b1 : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) (b2 : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) : eq_result =
  (let related_by = (fun f o1 o2 -> (match (o1, o2) with
      | (None, None) -> true
      | ((Some (x)), (Some (y))) -> (f x y)
      | (tmp, tmp1) -> false
    )) in
  (match b1 with
    | (p1, w1, t1) -> (match b2 with
        | (p2, w2, t2) -> (let tmp = (FStarC_Syntax_Syntax.eq_pat p1 p2) in
          (if tmp then (let tmp1 = (eq_tm env t1 t2) in
          let tmp2 = ((=) tmp1 Equal) in
          let tmp3 = (if tmp2 then (related_by (fun t11 t21 -> (let tmp3 = (eq_tm env t11 t21) in
            ((=) tmp3 Equal))) w1 w2) else false) in
          (if tmp3 then Equal else Unknown)) else Unknown))
      )
  ))

and eq_comp (env : FStarC_TypeChecker_Env.env) (t1 : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) (t2 : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : eq_result =
  (let ct1 = (t1).FStarC_Syntax_Syntax.n in
  let ct2 = (t2).FStarC_Syntax_Syntax.n in
  (eq_and (equal_if (FStarC_Ident.lid_equals (ct1).FStarC_Syntax_Syntax.effect_name (ct2).FStarC_Syntax_Syntax.effect_name)) (fun tmp -> (let tmp1 = (eq_tm env (ct1).FStarC_Syntax_Syntax.result_typ (ct2).FStarC_Syntax_Syntax.result_typ) in
  (eq_and tmp1 (fun tmp2 -> Equal))))))

and eq_tm (env : FStarC_TypeChecker_Env.env) (t1 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (t2 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : eq_result =
  (let t11 = (FStarC_Syntax_Util.canon_app t1) in
  let t21 = (FStarC_Syntax_Util.canon_app t2) in
  let equal_data = (fun f1 args1 f2 args2 n_parms -> (if (FStarC_Syntax_Syntax.fv_eq f1 f2) then (let n1 = (FStarC_List.length args1) in
    let n2 = (FStarC_List.length args2) in
    (if (((=) n1 n2) && (Prims.op_Less_Equals n_parms n1)) then (let tmp = (FStarC_List.splitAt n_parms args1) in
    (match tmp with
      | (parms1, args11) -> (let tmp1 = (FStarC_List.splitAt n_parms args2) in
        (match tmp1 with
          | (parms2, args21) -> (let eq_arg_list = (fun as1 as2 -> (FStarC_List.fold_left2 (fun acc tmp2 tmp3 -> (match (tmp2, tmp3) with
                | ((a1, q1), (a2, q2)) -> (let tmp4 = (eq_tm env a1 a2) in
                  (eq_inj acc tmp4))
              )) Equal as1 as2)) in
            (eq_arg_list args11 args21))
        ))
    )) else Unknown)) else NotEqual)) in
  let qual_is_inj = (fun tmp -> (match tmp with
      | (Some (FStarC_Syntax_Syntax.Data_ctor)) -> true
      | (Some ((FStarC_Syntax_Syntax.Record_ctor (u__1, u__2)))) -> true
      | tmp1 -> false
    )) in
  let tmp = (FStarC_Syntax_Util.unmeta t11) in
  let tmp1 = (FStarC_Syntax_Util.head_and_args_full tmp) in
  let heads_and_args_in_case_both_data = (match tmp1 with
      | (head1, args1) -> (let tmp2 = (FStarC_Syntax_Util.unmeta t21) in
        let tmp3 = (FStarC_Syntax_Util.head_and_args_full tmp2) in
        (match tmp3 with
          | (head2, args2) -> (let tmp4 = (FStarC_Syntax_Util.un_uinst head1) in
            let tmp5 = (tmp4).FStarC_Syntax_Syntax.n in
            let tmp6 = (FStarC_Syntax_Util.un_uinst head2) in
            let tmp7 = (tmp6).FStarC_Syntax_Syntax.n in
            let tmp8 = (tmp5, tmp7) in
            (match tmp8 with
              | ((FStarC_Syntax_Syntax.Tm_fvar (f)), (FStarC_Syntax_Syntax.Tm_fvar (g))) when ((qual_is_inj (f).FStarC_Syntax_Syntax.fv_qual) && (qual_is_inj (g).FStarC_Syntax_Syntax.fv_qual)) -> (let tmp9 = (FStarC_TypeChecker_Env.num_datacon_non_injective_ty_params env (FStarC_Syntax_Syntax.lid_of_fv f)) in
                (match tmp9 with
                  | (Some (n)) -> (Some ((f, args1, g, args2, n)))
                  | tmp10 -> None
                ))
              | tmp9 -> None
            ))
        ))
    ) in
  let t12 = (FStarC_Syntax_Util.unmeta t11) in
  let t22 = (FStarC_Syntax_Util.unmeta t21) in
  (match ((t12).FStarC_Syntax_Syntax.n, (t22).FStarC_Syntax_Syntax.n) with
    | ((FStarC_Syntax_Syntax.Tm_bvar (bv1)), (FStarC_Syntax_Syntax.Tm_bvar (bv2))) -> (equal_if ((=) (bv1).FStarC_Syntax_Syntax.index (bv2).FStarC_Syntax_Syntax.index))
    | ((FStarC_Syntax_Syntax.Tm_lazy (tmp2)), tmp3) -> (let tmp4 = (FStarC_Syntax_Util.unlazy t12) in
      (eq_tm env tmp4 t22))
    | (tmp2, (FStarC_Syntax_Syntax.Tm_lazy (tmp3))) -> (let tmp4 = (FStarC_Syntax_Util.unlazy t22) in
      (eq_tm env t12 tmp4))
    | ((FStarC_Syntax_Syntax.Tm_name (a)), (FStarC_Syntax_Syntax.Tm_name (b))) -> (equal_if (FStarC_Syntax_Syntax.bv_eq a b))
    | tmp2 when (match heads_and_args_in_case_both_data with
      | (Some (v)) -> true
      | tmp3 -> false
    ) -> (let tmp3 = (FStarC_Option.must heads_and_args_in_case_both_data) in
      (match tmp3 with
        | (f, args1, g, args2, n) -> (equal_data f args1 g args2 n)
      ))
    | ((FStarC_Syntax_Syntax.Tm_fvar (f)), (FStarC_Syntax_Syntax.Tm_fvar (g))) -> (equal_if (FStarC_Syntax_Syntax.fv_eq f g))
    | ((FStarC_Syntax_Syntax.Tm_uinst (f, us)), (FStarC_Syntax_Syntax.Tm_uinst (g, vs))) -> (let tmp2 = (eq_tm env f g) in
      (eq_and tmp2 (fun tmp3 -> (let tmp4 = (FStarC_Syntax_Util.eq_univs_list us vs) in
      (equal_if tmp4)))))
    | ((FStarC_Syntax_Syntax.Tm_constant ((FStarC_Const.Const_range (tmp2)))), (FStarC_Syntax_Syntax.Tm_constant ((FStarC_Const.Const_range (tmp3))))) -> Unknown
    | ((FStarC_Syntax_Syntax.Tm_constant ((FStarC_Const.Const_real (r1)))), (FStarC_Syntax_Syntax.Tm_constant ((FStarC_Const.Const_real (r2))))) -> (match (FStarC_Real.cmp r1 r2) with
        | FStarC_Order.Eq -> Equal
        | FStarC_Order.Lt -> NotEqual
        | FStarC_Order.Gt -> NotEqual
      )
    | ((FStarC_Syntax_Syntax.Tm_constant (c)), (FStarC_Syntax_Syntax.Tm_constant (d))) -> (equal_iff (FStarC_Const.eq_const c d))
    | ((FStarC_Syntax_Syntax.Tm_uvar (u1, ([], tmp2))), (FStarC_Syntax_Syntax.Tm_uvar (u2, ([], tmp3)))) -> (let tmp4 = (FStarC_Syntax_Unionfind.equiv ((u1).FStarC_Syntax_Syntax.ctx_uvar_head, (u1).FStarC_Syntax_Syntax.ctx_uvar_head1, (u1).FStarC_Syntax_Syntax.ctx_uvar_head2) ((u2).FStarC_Syntax_Syntax.ctx_uvar_head, (u2).FStarC_Syntax_Syntax.ctx_uvar_head1, (u2).FStarC_Syntax_Syntax.ctx_uvar_head2)) in
      (equal_if tmp4))
    | ((FStarC_Syntax_Syntax.Tm_app ({ FStarC_Syntax_Syntax.hd = h1; arg = u__1; arg1 = u__2; _ })), (FStarC_Syntax_Syntax.Tm_app ({ FStarC_Syntax_Syntax.hd = h2; arg = u__11; arg1 = u__21; _ }))) -> (let tmp2 = (FStarC_Syntax_Util.un_uinst h1) in
      let tmp3 = (tmp2).FStarC_Syntax_Syntax.n in
      let tmp4 = (FStarC_Syntax_Util.un_uinst h2) in
      let tmp5 = (tmp4).FStarC_Syntax_Syntax.n in
      let tmp6 = (tmp3, tmp5) in
      (match tmp6 with
        | ((FStarC_Syntax_Syntax.Tm_fvar (f1)), (FStarC_Syntax_Syntax.Tm_fvar (f2))) when ((FStarC_Syntax_Syntax.fv_eq f1 f2) && (FStarC_List.mem (FStarC_Ident.string_of_lid (FStarC_Syntax_Syntax.lid_of_fv f1)) injectives)) -> (equal_data f1 ((u__1, u__2) :: []) f2 ((u__11, u__21) :: []) (Prims.parse_int "0"))
        | tmp7 -> (let tmp8 = (eq_tm env h1 h2) in
          (eq_and tmp8 (fun tmp9 -> (eq_args env ((u__1, u__2) :: []) ((u__11, u__21) :: [])))))
      ))
    | ((FStarC_Syntax_Syntax.Tm_match ({ FStarC_Syntax_Syntax.scrutinee = t13; ret_opt = tmp2; brs = bs1; rc_opt = tmp3; _ })), (FStarC_Syntax_Syntax.Tm_match ({ FStarC_Syntax_Syntax.scrutinee = t23; ret_opt = tmp4; brs = bs2; rc_opt = tmp5; _ }))) -> (if ((=) (FStarC_List.length bs1) (FStarC_List.length bs2)) then (let tmp6 = (eq_tm env t13 t23) in
      (FStarC_List.fold_right (fun tmp7 a -> (match tmp7 with
        | (b1, b2) -> (eq_and a (fun tmp8 -> (branch_matches env b1 b2)))
      )) (FStarC_List.zip bs1 bs2) tmp6)) else Unknown)
    | ((FStarC_Syntax_Syntax.Tm_type (u)), (FStarC_Syntax_Syntax.Tm_type (v))) -> (let tmp2 = (FStarC_Syntax_Util.eq_univs u v) in
      (equal_if tmp2))
    | ((FStarC_Syntax_Syntax.Tm_quoted (t13, q1)), (FStarC_Syntax_Syntax.Tm_quoted (t23, q2))) -> Unknown
    | ((FStarC_Syntax_Syntax.Tm_refine ({ FStarC_Syntax_Syntax.b = t13; phi = phi1; _ })), (FStarC_Syntax_Syntax.Tm_refine ({ FStarC_Syntax_Syntax.b = t23; phi = phi2; _ }))) -> (let tmp2 = (eq_tm env (t13).FStarC_Syntax_Syntax.sort (t23).FStarC_Syntax_Syntax.sort) in
      (eq_and tmp2 (fun tmp3 -> (eq_tm env phi1 phi2))))
    | ((FStarC_Syntax_Syntax.Tm_abs ({ FStarC_Syntax_Syntax.b = b1; body = body1; rc_opt = tmp2; _ })), (FStarC_Syntax_Syntax.Tm_abs ({ FStarC_Syntax_Syntax.b = b2; body = body2; rc_opt = tmp3; _ }))) -> (let tmp4 = (eq_tm env ((b1).FStarC_Syntax_Syntax.binder_bv).FStarC_Syntax_Syntax.sort ((b2).FStarC_Syntax_Syntax.binder_bv).FStarC_Syntax_Syntax.sort) in
      (eq_and tmp4 (fun tmp5 -> (eq_tm env body1 body2))))
    | ((FStarC_Syntax_Syntax.Tm_arrow ({ FStarC_Syntax_Syntax.b = b1; comp = c1; _ })), (FStarC_Syntax_Syntax.Tm_arrow ({ FStarC_Syntax_Syntax.b = b2; comp = c2; _ }))) -> (if (not (FStarC_Syntax_Util.bqual_compat (b1).FStarC_Syntax_Syntax.binder_qual (b2).FStarC_Syntax_Syntax.binder_qual)) then Unknown else (let tmp2 = (eq_tm env ((b1).FStarC_Syntax_Syntax.binder_bv).FStarC_Syntax_Syntax.sort ((b2).FStarC_Syntax_Syntax.binder_bv).FStarC_Syntax_Syntax.sort) in
      (eq_and tmp2 (fun tmp3 -> (eq_comp env c1 c2)))))
    | tmp2 -> Unknown
  ))

let eq_tm_bool (e : FStarC_TypeChecker_Env.env) (t1 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (t2 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : bool =
  (let tmp = (eq_tm e t1 t2) in
  ((=) tmp Equal))

let rec simplify__clearly_inhabited (ty : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : bool =
  (let tmp = (FStarC_Syntax_Util.unmeta ty) in
  let tmp1 = (tmp).FStarC_Syntax_Syntax.n in
  (match tmp1 with
    | (FStarC_Syntax_Syntax.Tm_uinst (t, tmp2)) -> (simplify__clearly_inhabited t)
    | (FStarC_Syntax_Syntax.Tm_arrow ({ FStarC_Syntax_Syntax.b = tmp2; comp = c; _ })) -> (simplify__clearly_inhabited (FStarC_Syntax_Util.comp_result c))
    | (FStarC_Syntax_Syntax.Tm_fvar (fv)) -> (let l = (FStarC_Syntax_Syntax.lid_of_fv fv) in
      ((((FStarC_Ident.lid_equals l FStarC_Parser_Const.int_lid) || (FStarC_Ident.lid_equals l FStarC_Parser_Const.bool_lid)) || (FStarC_Ident.lid_equals l FStarC_Parser_Const.string_lid)) || (FStarC_Ident.lid_equals l FStarC_Parser_Const.exn_lid)))
    | tmp2 -> false
  ))

let simplify (debug : bool) (env : FStarC_TypeChecker_Env.env) (tm : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let w = (fun t -> { FStarC_Syntax_Syntax.n = (t).FStarC_Syntax_Syntax.n;
      pos = (tm).FStarC_Syntax_Syntax.pos;
      hash_code = (t).FStarC_Syntax_Syntax.hash_code }) in
  let simp_t = (fun t -> (let tmp = (FStarC_Syntax_Util.unmeta t) in
    let tmp1 = (tmp).FStarC_Syntax_Syntax.n in
    (match tmp1 with
      | (FStarC_Syntax_Syntax.Tm_fvar (fv)) when (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.true_lid) -> (Some (true))
      | (FStarC_Syntax_Syntax.Tm_fvar (fv)) when (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.false_lid) -> (Some (false))
      | tmp2 -> None
    ))) in
  let is_const_match = (fun phi -> (let tmp = (FStarC_Syntax_Subst.compress phi) in
    let tmp1 = (tmp).FStarC_Syntax_Syntax.n in
    (match tmp1 with
      | (FStarC_Syntax_Syntax.Tm_match ({ FStarC_Syntax_Syntax.scrutinee = tmp2; ret_opt = tmp3; brs = (br :: brs); rc_opt = tmp4; _ })) -> (match br with
          | (tmp5, tmp6, e) -> (let tmp7 = (simp_t e) in
            (match tmp7 with
              | None -> None
              | (Some (b)) -> (let tmp8 = (FStarC_List.for_all (fun tmp8 -> (match tmp8 with
                    | (tmp9, tmp10, e') -> (let tmp11 = (simp_t e') in
                      ((=) tmp11 (Some (b))))
                  )) brs) in
                (if tmp8 then (Some (b)) else None))
            ))
        )
      | tmp2 -> None
    ))) in
  let maybe_auto_squash = (fun t -> t) in
  let squashed_head_un_auto_squash_args = (fun t -> t) in
  let simplify_ = (fun arg -> (let tmp = (simp_t (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst arg)) in
    (tmp, arg))) in
  let tmp = (FStarC_Syntax_Subst.compress tm) in
  let tmp1 = (tmp).FStarC_Syntax_Syntax.n in
  (match tmp1 with
    | (FStarC_Syntax_Syntax.Tm_app (tmp2)) -> (let tmp3 = (FStarC_Syntax_Util.head_and_args_full tm) in
      (match tmp3 with
        | (head, args) -> (let tmp4 = (FStarC_Syntax_Util.un_uinst head) in
          let tmp5 = (tmp4).FStarC_Syntax_Syntax.n in
          (match tmp5 with
            | (FStarC_Syntax_Syntax.Tm_fvar (fv)) -> (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.squash_lid) then (squashed_head_un_auto_squash_args tm) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.and_lid) then (let tmp6 = (FStarC_List.map simplify_ args) in
              (match tmp6 with
                | (((Some (true)), tmp7) :: ((tmp8, (arg, tmp9)) :: [])) -> (maybe_auto_squash arg)
                | ((tmp7, (arg, tmp8)) :: (((Some (true)), tmp9) :: [])) -> (maybe_auto_squash arg)
                | (((Some (false)), tmp7) :: (tmp8 :: [])) -> (w FStarC_Syntax_Util.t_false)
                | (tmp7 :: (((Some (false)), tmp8) :: [])) -> (w FStarC_Syntax_Util.t_false)
                | tmp7 -> (squashed_head_un_auto_squash_args tm)
              )) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.or_lid) then (let tmp6 = (FStarC_List.map simplify_ args) in
              (match tmp6 with
                | (((Some (true)), tmp7) :: (tmp8 :: [])) -> (w FStarC_Syntax_Util.t_true)
                | (tmp7 :: (((Some (true)), tmp8) :: [])) -> (w FStarC_Syntax_Util.t_true)
                | (((Some (false)), tmp7) :: ((tmp8, (arg, tmp9)) :: [])) -> (maybe_auto_squash arg)
                | ((tmp7, (arg, tmp8)) :: (((Some (false)), tmp9) :: [])) -> (maybe_auto_squash arg)
                | tmp7 -> (squashed_head_un_auto_squash_args tm)
              )) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.imp_lid) then (let tmp6 = (FStarC_List.map simplify_ args) in
              (match tmp6 with
                | (tmp7 :: (((Some (true)), tmp8) :: [])) -> (w FStarC_Syntax_Util.t_true)
                | (((Some (false)), tmp7) :: (tmp8 :: [])) -> (w FStarC_Syntax_Util.t_true)
                | (((Some (true)), tmp7) :: ((tmp8, (arg, tmp9)) :: [])) -> (maybe_auto_squash arg)
                | ((tmp7, (p, tmp8)) :: ((tmp9, (q, tmp10)) :: [])) -> (let tmp11 = (FStarC_Syntax_Util.term_eq p q) in
                  (if tmp11 then (w FStarC_Syntax_Util.t_true) else (squashed_head_un_auto_squash_args tm)))
                | tmp7 -> (squashed_head_un_auto_squash_args tm)
              )) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.iff_lid) then (let tmp6 = (FStarC_List.map simplify_ args) in
              (match tmp6 with
                | (((Some (true)), tmp7) :: (((Some (true)), tmp8) :: [])) -> (w FStarC_Syntax_Util.t_true)
                | (((Some (false)), tmp7) :: (((Some (false)), tmp8) :: [])) -> (w FStarC_Syntax_Util.t_true)
                | (((Some (true)), tmp7) :: (((Some (false)), tmp8) :: [])) -> (w FStarC_Syntax_Util.t_false)
                | (((Some (false)), tmp7) :: (((Some (true)), tmp8) :: [])) -> (w FStarC_Syntax_Util.t_false)
                | ((tmp7, (arg, tmp8)) :: (((Some (true)), tmp9) :: [])) -> (maybe_auto_squash arg)
                | (((Some (true)), tmp7) :: ((tmp8, (arg, tmp9)) :: [])) -> (maybe_auto_squash arg)
                | ((tmp7, (arg, tmp8)) :: (((Some (false)), tmp9) :: [])) -> (let tmp10 = (FStarC_Syntax_Util.mk_neg arg) in
                  (maybe_auto_squash tmp10))
                | (((Some (false)), tmp7) :: ((tmp8, (arg, tmp9)) :: [])) -> (let tmp10 = (FStarC_Syntax_Util.mk_neg arg) in
                  (maybe_auto_squash tmp10))
                | ((tmp7, (p, tmp8)) :: ((tmp9, (q, tmp10)) :: [])) -> (let tmp11 = (FStarC_Syntax_Util.term_eq p q) in
                  (if tmp11 then (w FStarC_Syntax_Util.t_true) else (squashed_head_un_auto_squash_args tm)))
                | tmp7 -> (squashed_head_un_auto_squash_args tm)
              )) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.not_lid) then (let tmp6 = (FStarC_List.map simplify_ args) in
              (match tmp6 with
                | (((Some (true)), tmp7) :: []) -> (w FStarC_Syntax_Util.t_false)
                | (((Some (false)), tmp7) :: []) -> (w FStarC_Syntax_Util.t_true)
                | tmp7 -> (squashed_head_un_auto_squash_args tm)
              )) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.forall_lid) then (match args with
                | ((t, tmp6) :: []) -> (let tmp7 = (FStarC_Syntax_Subst.compress t) in
                  let tmp8 = (tmp7).FStarC_Syntax_Syntax.n in
                  (match tmp8 with
                    | (FStarC_Syntax_Syntax.Tm_abs ({ FStarC_Syntax_Syntax.b = tmp9; body = body; rc_opt = tmp10; _ })) -> (let tmp11 = (simp_t body) in
                      (match tmp11 with
                        | (Some (true)) -> (w FStarC_Syntax_Util.t_true)
                        | tmp12 -> tm
                      ))
                    | tmp9 -> tm
                  ))
                | ((ty, (Some ({ FStarC_Syntax_Syntax.aqual_implicit = true; aqual_attributes = tmp6; _ }))) :: ((t, tmp7) :: [])) -> (let tmp8 = (FStarC_Syntax_Subst.compress t) in
                  let tmp9 = (tmp8).FStarC_Syntax_Syntax.n in
                  (match tmp9 with
                    | (FStarC_Syntax_Syntax.Tm_abs ({ FStarC_Syntax_Syntax.b = tmp10; body = body; rc_opt = tmp11; _ })) -> (let tmp12 = (simp_t body) in
                      (match tmp12 with
                        | (Some (true)) -> (w FStarC_Syntax_Util.t_true)
                        | (Some (false)) when (simplify__clearly_inhabited ty) -> (w FStarC_Syntax_Util.t_false)
                        | tmp13 -> tm
                      ))
                    | tmp10 -> tm
                  ))
                | tmp6 -> tm
              ) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.exists_lid) then (match args with
                | ((t, tmp6) :: []) -> (let tmp7 = (FStarC_Syntax_Subst.compress t) in
                  let tmp8 = (tmp7).FStarC_Syntax_Syntax.n in
                  (match tmp8 with
                    | (FStarC_Syntax_Syntax.Tm_abs ({ FStarC_Syntax_Syntax.b = tmp9; body = body; rc_opt = tmp10; _ })) -> (let tmp11 = (simp_t body) in
                      (match tmp11 with
                        | (Some (false)) -> (w FStarC_Syntax_Util.t_false)
                        | tmp12 -> tm
                      ))
                    | tmp9 -> tm
                  ))
                | ((ty, (Some ({ FStarC_Syntax_Syntax.aqual_implicit = true; aqual_attributes = tmp6; _ }))) :: ((t, tmp7) :: [])) -> (let tmp8 = (FStarC_Syntax_Subst.compress t) in
                  let tmp9 = (tmp8).FStarC_Syntax_Syntax.n in
                  (match tmp9 with
                    | (FStarC_Syntax_Syntax.Tm_abs ({ FStarC_Syntax_Syntax.b = tmp10; body = body; rc_opt = tmp11; _ })) -> (let tmp12 = (simp_t body) in
                      (match tmp12 with
                        | (Some (false)) -> (w FStarC_Syntax_Util.t_false)
                        | (Some (true)) when (simplify__clearly_inhabited ty) -> (w FStarC_Syntax_Util.t_true)
                        | tmp13 -> tm
                      ))
                    | tmp10 -> tm
                  ))
                | tmp6 -> tm
              ) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.b2t_lid) then (match args with
                | (({ FStarC_Syntax_Syntax.n = (FStarC_Syntax_Syntax.Tm_constant ((FStarC_Const.Const_bool (true)))); pos = tmp6; hash_code = tmp7; _ }, tmp8) :: []) -> (w FStarC_Syntax_Util.t_true)
                | (({ FStarC_Syntax_Syntax.n = (FStarC_Syntax_Syntax.Tm_constant ((FStarC_Const.Const_bool (false)))); pos = tmp6; hash_code = tmp7; _ }, tmp8) :: []) -> (w FStarC_Syntax_Util.t_false)
                | tmp6 -> tm
              ) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.haseq_lid) then (let t_has_eq_for_sure = (fun t -> (let haseq_lids = (FStarC_Parser_Const.int_lid :: (FStarC_Parser_Const.bool_lid :: (FStarC_Parser_Const.unit_lid :: (FStarC_Parser_Const.string_lid :: [])))) in
                let tmp6 = (FStarC_Syntax_Subst.compress t) in
                let tmp7 = (tmp6).FStarC_Syntax_Syntax.n in
                (match tmp7 with
                  | (FStarC_Syntax_Syntax.Tm_fvar (fv1)) when (FStarC_List.existsb (fun l -> (FStarC_Syntax_Syntax.fv_eq_lid fv1 l)) haseq_lids) -> true
                  | tmp8 -> false
                ))) in
              (if ((=) (FStarC_List.length args) (Prims.parse_int "1")) then (let t = (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst (FStarC_List.hd args)) in
              let tmp6 = (t_has_eq_for_sure t) in
              (if tmp6 then (w FStarC_Syntax_Util.t_true) else (let tmp7 = (FStarC_Syntax_Subst.compress t) in
              let tmp8 = (tmp7).FStarC_Syntax_Syntax.n in
              (match tmp8 with
                | (FStarC_Syntax_Syntax.Tm_refine (tmp9)) -> (let t1 = (FStarC_Syntax_Util.unrefine t) in
                  let tmp10 = (t_has_eq_for_sure t1) in
                  (if tmp10 then (w FStarC_Syntax_Util.t_true) else (let tmp11 = (FStarC_Syntax_Subst.compress tm) in
                  let tmp12 = (tmp11).FStarC_Syntax_Syntax.n in
                  let haseq_tm = (match tmp12 with
                      | (FStarC_Syntax_Syntax.Tm_app ({ FStarC_Syntax_Syntax.hd = hd; arg = u__1; arg1 = u__2; _ })) -> hd
                      | tmp13 -> (FStarC_Effect.failwith "Impossible! We have already checked that this is a Tm_app")
                    ) in
                  (FStarC_Syntax_Util.mk_app haseq_tm ((FStarC_Syntax_Syntax.as_arg t1) :: [])))))
                | tmp9 -> tm
              )))) else tm)) else (if (FStarC_Syntax_Syntax.fv_eq_lid fv FStarC_Parser_Const.eq2_lid) then (match args with
                | ((u__typ, tmp6) :: ((a1, tmp7) :: ((a2, tmp8) :: []))) -> (let tmp9 = (eq_tm env a1 a2) in
                  (match tmp9 with
                    | Equal -> (w FStarC_Syntax_Util.t_true)
                    | NotEqual -> (w FStarC_Syntax_Util.t_false)
                    | tmp10 -> tm
                  ))
                | tmp6 -> tm
              ) else tm)))))))))))
            | tmp6 -> tm
          ))
      ))
    | (FStarC_Syntax_Syntax.Tm_refine ({ FStarC_Syntax_Syntax.b = bv; phi = t; _ })) -> (let tmp2 = (simp_t t) in
      (match tmp2 with
        | (Some (true)) -> (bv).FStarC_Syntax_Syntax.sort
        | (Some (false)) -> tm
        | None -> tm
      ))
    | (FStarC_Syntax_Syntax.Tm_match (tmp2)) -> (let tmp3 = (is_const_match tm) in
      (match tmp3 with
        | (Some (true)) -> (w FStarC_Syntax_Util.t_true)
        | (Some (false)) -> (w FStarC_Syntax_Util.t_false)
        | None -> tm
      ))
    | tmp2 -> tm
  ))

