(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let compose_subst (s1 : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (s2 : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range) =
  (let s = (FStarC_List.op_At (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst s1) (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst s2)) in
  let ropt = (match (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s2) with
      | (FStarC_Syntax_Syntax.SomeUseRange (tmp)) -> (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s2)
      | tmp -> (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s1)
    ) in
  (s, ropt))

let delay (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (match (t).FStarC_Syntax_Syntax.n with
    | (FStarC_Syntax_Syntax.Tm_delayed ({ FStarC_Syntax_Syntax.tm = t'; substs = u__1; substs1 = u__2; _ })) -> (FStarC_Syntax_Syntax.mk_Tm_delayed (t', (compose_subst (u__1, u__2) s)) (t).FStarC_Syntax_Syntax.pos)
    | tmp -> (FStarC_Syntax_Syntax.mk_Tm_delayed (t, s) (t).FStarC_Syntax_Syntax.pos)
  )

let rec force_uvar' (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax * bool) =
  (match (t).FStarC_Syntax_Syntax.n with
    | (FStarC_Syntax_Syntax.Tm_uvar ({ FStarC_Syntax_Syntax.ctx_uvar_head = u__1; ctx_uvar_head1 = u__2; ctx_uvar_head2 = u__3; ctx_uvar_gamma = tmp; ctx_uvar_binders = tmp1; ctx_uvar_reason = tmp2; ctx_uvar_range = tmp3; ctx_uvar_meta = tmp4; _ }, s)) -> (let tmp5 = (FStarC_Syntax_Unionfind.find (u__1, u__2, u__3)) in
      (match tmp5 with
        | (Some (t')) -> (let tmp6 = (delay t' s) in
          let tmp7 = (force_uvar' tmp6) in
          let tmp8 = (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst tmp7) in
          (tmp8, true))
        | tmp6 -> (t, false)
      ))
    | tmp -> (t, false)
  )

let force_uvar (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let tmp = (force_uvar' t) in
  (match tmp with
    | (t', forced) -> (if forced then (delay t' ([], (FStarC_Syntax_Syntax.SomeUseRange ((t).FStarC_Syntax_Syntax.pos)))) else t)
  ))

let mk_range (r : FStarC_Range_Type.range) (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) : FStarC_Range_Type.range =
  (match (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s) with
    | FStarC_Syntax_Syntax.NoUseRange -> r
    | (FStarC_Syntax_Syntax.SomeUseRange (r')) -> (let tmp = (FStarC_Range_Ops.rng_included (FStarC_Range_Type.use_range r) (FStarC_Range_Type.use_range r')) in
      (if tmp then r else (FStarC_Range_Type.set_use_range r (FStarC_Range_Type.use_range r'))))
  )

let tag_with_range (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (match (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s) with
    | FStarC_Syntax_Syntax.NoUseRange -> t
    | (FStarC_Syntax_Syntax.SomeUseRange (r)) -> (let tmp = (FStarC_Range_Ops.rng_included (FStarC_Range_Type.use_range (t).FStarC_Syntax_Syntax.pos) (FStarC_Range_Type.use_range r)) in
      (if tmp then t else (let r1 = (FStarC_Range_Type.set_use_range (t).FStarC_Syntax_Syntax.pos (FStarC_Range_Type.use_range r)) in
      let t' = (match (t).FStarC_Syntax_Syntax.n with
          | (FStarC_Syntax_Syntax.Tm_bvar (bv)) -> (let tmp1 = (FStarC_Syntax_Syntax.fStarC_Class_HasRange_setPos__bv r1 bv) in
            (FStarC_Syntax_Syntax.Tm_bvar (tmp1)))
          | (FStarC_Syntax_Syntax.Tm_name (bv)) -> (let tmp1 = (FStarC_Syntax_Syntax.fStarC_Class_HasRange_setPos__bv r1 bv) in
            (FStarC_Syntax_Syntax.Tm_name (tmp1)))
          | (FStarC_Syntax_Syntax.Tm_fvar (fv)) -> (let tmp1 = (FStarC_Syntax_Syntax.fStarC_Class_HasRange_setPos__fv r1 fv) in
            (FStarC_Syntax_Syntax.Tm_fvar (tmp1)))
          | t' -> t'
        ) in
      { FStarC_Syntax_Syntax.n = t';
        pos = r1;
        hash_code = (t).FStarC_Syntax_Syntax.hash_code })))
  )

let rec apply_until_some (f : ('u_'a -> ('u_'b) option)) (s : ('u_'a) list) : ((('u_'a) list * 'u_'b)) option =
  (match s with
    | [] -> None
    | (s0 :: rest) -> (let tmp = (f s0) in
      (match tmp with
        | None -> (apply_until_some f rest)
        | (Some (st)) -> (Some ((rest, st)))
      ))
  )

let map_some_curry (f : ('u_'a -> ('u_'b -> 'u_'c))) (x : 'u_'c) (tmp : (('u_'a * 'u_'b)) option) : 'u_'c =
  (match tmp with
    | None -> x
    | (Some ((a, b))) -> (f a b)
  )

let apply_until_some_then_map (f : ('u_'a -> ('u_'b) option)) (s : ('u_'a) list) (g : (('u_'a) list -> ('u_'b -> 'u_'c))) (t : 'u_'c) : 'u_'c =
  (let tmp = (apply_until_some f s) in
  (map_some_curry g t tmp))

let subst_bv (a : FStarC_Syntax_Syntax.bv) (s : (FStarC_Syntax_Syntax.subst_elt) list) : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option =
  (FStarC_Util.find_map s (fun tmp -> (match tmp with
    | (FStarC_Syntax_Syntax.DB (i, x)) when ((=) i (a).FStarC_Syntax_Syntax.index) -> (let tmp1 = (FStarC_Syntax_Syntax.bv_to_name (FStarC_Syntax_Syntax.set_range_of_bv x (FStarC_Syntax_Syntax.range_of_bv a))) in
      (Some (tmp1)))
    | (FStarC_Syntax_Syntax.DT (i, t)) when ((=) i (a).FStarC_Syntax_Syntax.index) -> (Some (t))
    | tmp1 -> None
  )))

let subst_nm (a : FStarC_Syntax_Syntax.bv) (s : (FStarC_Syntax_Syntax.subst_elt) list) : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option =
  (FStarC_Util.find_map s (fun tmp -> (match tmp with
    | (FStarC_Syntax_Syntax.NM (x, i)) when (FStarC_Syntax_Syntax.bv_eq a x) -> (let tmp1 = (FStarC_Syntax_Syntax.bv_to_tm { FStarC_Syntax_Syntax.ppname = (a).FStarC_Syntax_Syntax.ppname;
          index = i;
          sort = (a).FStarC_Syntax_Syntax.sort }) in
      (Some (tmp1)))
    | (FStarC_Syntax_Syntax.NT (x, t)) when (FStarC_Syntax_Syntax.bv_eq a x) -> (Some (t))
    | tmp1 -> None
  )))

let rec compress_univ (u : FStarC_Syntax_Syntax.universe) : FStarC_Syntax_Syntax.universe =
  (match u with
    | (FStarC_Syntax_Syntax.U_unif (u__1, u__2, u__3)) -> (let tmp = (FStarC_Syntax_Unionfind.univ_find (u__1, u__2, u__3)) in
      (match tmp with
        | (Some (u1)) -> (compress_univ u1)
        | tmp1 -> u
      ))
    | tmp -> u
  )

let subst_univ_bv (x : Prims.int) (s : (FStarC_Syntax_Syntax.subst_elt) list) : (FStarC_Syntax_Syntax.universe) option =
  (FStarC_Util.find_map s (fun tmp -> (match tmp with
    | (FStarC_Syntax_Syntax.UN (y, t)) when ((=) x y) -> (Some (t))
    | tmp1 -> None
  )))

let subst_univ_nm (x : FStarC_Ident.ident) (s : (FStarC_Syntax_Syntax.subst_elt) list) : (FStarC_Syntax_Syntax.universe) option =
  (FStarC_Util.find_map s (fun tmp -> (match tmp with
    | (FStarC_Syntax_Syntax.UD (y, i)) when (FStarC_Ident.ident_equals x y) -> (Some ((FStarC_Syntax_Syntax.U_bvar (i))))
    | tmp1 -> None
  )))

let rec subst_univ (s : ((FStarC_Syntax_Syntax.subst_elt) list) list) (u : FStarC_Syntax_Syntax.universe) : FStarC_Syntax_Syntax.universe =
  (let u1 = (compress_univ u) in
  (match u1 with
    | (FStarC_Syntax_Syntax.U_bvar (x)) -> (apply_until_some_then_map (subst_univ_bv x) s subst_univ u1)
    | (FStarC_Syntax_Syntax.U_name (x)) -> (apply_until_some_then_map (subst_univ_nm x) s subst_univ u1)
    | FStarC_Syntax_Syntax.U_zero -> u1
    | FStarC_Syntax_Syntax.U_unknown -> u1
    | (FStarC_Syntax_Syntax.U_unif (u__1, u__2, u__3)) -> u1
    | (FStarC_Syntax_Syntax.U_succ (u2)) -> (let tmp = (subst_univ s u2) in
      (FStarC_Syntax_Syntax.U_succ (tmp)))
    | (FStarC_Syntax_Syntax.U_max (us)) -> (let tmp = (FStarC_List.map (subst_univ s) us) in
      (FStarC_Syntax_Syntax.U_max (tmp)))
  ))

let rec subst' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let subst_tail = (fun tl -> (subst' (tl, (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s)))) in
  (match s with
    | ([], FStarC_Syntax_Syntax.NoUseRange) -> t
    | (([] :: []), FStarC_Syntax_Syntax.NoUseRange) -> t
    | tmp -> (match (t).FStarC_Syntax_Syntax.n with
        | FStarC_Syntax_Syntax.Tm_unknown -> (tag_with_range t s)
        | (FStarC_Syntax_Syntax.Tm_constant (tmp1)) -> (tag_with_range t s)
        | (FStarC_Syntax_Syntax.Tm_fvar (tmp1)) -> (tag_with_range t s)
        | (FStarC_Syntax_Syntax.Tm_delayed ({ FStarC_Syntax_Syntax.tm = t'; substs = u__1; substs1 = u__2; _ })) -> (FStarC_Syntax_Syntax.mk_Tm_delayed (t', (compose_subst (u__1, u__2) s)) (t).FStarC_Syntax_Syntax.pos)
        | (FStarC_Syntax_Syntax.Tm_bvar (a)) -> (apply_until_some_then_map (subst_bv a) (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst s) subst_tail t)
        | (FStarC_Syntax_Syntax.Tm_name (a)) -> (apply_until_some_then_map (subst_nm a) (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst s) subst_tail t)
        | (FStarC_Syntax_Syntax.Tm_type (u)) -> (let tmp1 = (subst_univ (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst s) u) in
          let tmp2 = (FStarC_Syntax_Syntax.Tm_type (tmp1)) in
          let tmp3 = (mk_range (t).FStarC_Syntax_Syntax.pos s) in
          (FStarC_Syntax_Syntax.mk tmp2 tmp3))
        | tmp1 -> (let tmp2 = (mk_range (t).FStarC_Syntax_Syntax.pos s) in
          (FStarC_Syntax_Syntax.mk_Tm_delayed (t, s) tmp2))
      )
  ))

let rec compose_uvar_subst__aux (should_retain : (FStarC_Syntax_Syntax.bv -> bool)) (l : ((FStarC_Syntax_Syntax.subst_elt) list) list) : (FStarC_Syntax_Syntax.subst_elt) list =
  (match l with
    | [] -> []
    | (hd_subst :: rest) -> (let hd = (FStarC_List.collect (fun tmp -> (match tmp with
          | (FStarC_Syntax_Syntax.NT (x, t)) -> (let tmp1 = (should_retain x) in
            (if tmp1 then (let tmp2 = (delay t (rest, FStarC_Syntax_Syntax.NoUseRange)) in
            let tmp3 = (x, tmp2) in
            let tmp4 = (FStarC_Syntax_Syntax.NT ((match tmp3 with (custard_tup, _) -> custard_tup), (match tmp3 with (_, custard_tup) -> custard_tup))) in
            (tmp4 :: [])) else []))
          | (FStarC_Syntax_Syntax.NM (x, i)) -> (let tmp1 = (should_retain x) in
            (if tmp1 then (let x_i = (FStarC_Syntax_Syntax.bv_to_tm { FStarC_Syntax_Syntax.ppname = (x).FStarC_Syntax_Syntax.ppname;
                index = i;
                sort = (x).FStarC_Syntax_Syntax.sort }) in
            let t = (subst' (rest, FStarC_Syntax_Syntax.NoUseRange) x_i) in
            (match (t).FStarC_Syntax_Syntax.n with
              | (FStarC_Syntax_Syntax.Tm_bvar (x_j)) -> ((FStarC_Syntax_Syntax.NM (x, (x_j).FStarC_Syntax_Syntax.index)) :: [])
              | tmp2 -> ((FStarC_Syntax_Syntax.NT (x, t)) :: [])
            )) else []))
          | tmp1 -> []
        )) hd_subst) in
      let tmp = ((compose_uvar_subst__aux should_retain) rest) in
      (FStarC_List.op_At hd tmp))
  )

let compose_uvar_subst (u : FStarC_Syntax_Syntax.ctx_uvar) (s0 : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range) =
  (let should_retain = (fun x -> (FStarC_Util.for_some (fun b -> (FStarC_Syntax_Syntax.bv_eq x (b).FStarC_Syntax_Syntax.binder_bv)) (u).FStarC_Syntax_Syntax.ctx_uvar_binders)) in
  let tmp = ((compose_uvar_subst__aux should_retain) (FStarC_List.op_At (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst s0) (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst s))) in
  (match tmp with
    | [] -> ([], (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s))
    | s' -> ((s' :: []), (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s))
  ))

let subst_arg' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (tmp : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax * 'tmp)) : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax * 'tmp) =
  (match tmp with
    | (t, imp) -> (let tmp1 = (subst' s t) in
      (tmp1, imp))
  )

let tag_lid_with_range (l : FStarC_Ident.lident) (s : ('tmp * FStarC_Syntax_Syntax.maybe_set_use_range)) : FStarC_Ident.lident =
  (match (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s) with
    | FStarC_Syntax_Syntax.NoUseRange -> l
    | (FStarC_Syntax_Syntax.SomeUseRange (r)) -> (let tmp = (FStarC_Range_Ops.rng_included (FStarC_Range_Type.use_range (FStarC_Ident.range_of_lid l)) (FStarC_Range_Type.use_range r)) in
      (if tmp then l else (FStarC_Ident.set_lid_range l (FStarC_Range_Type.set_use_range (FStarC_Ident.range_of_lid l) (FStarC_Range_Type.use_range r)))))
  )

let subst_dec_order' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (tmp : FStarC_Syntax_Syntax.decreases_order) : FStarC_Syntax_Syntax.decreases_order =
  (match tmp with
    | (FStarC_Syntax_Syntax.Decreases_lex (l)) -> (let tmp1 = (FStarC_List.map (subst' s) l) in
      (FStarC_Syntax_Syntax.Decreases_lex (tmp1)))
    | (FStarC_Syntax_Syntax.Decreases_wf (rel, e)) -> (let tmp1 = (subst' s rel) in
      let tmp2 = (subst' s e) in
      let tmp3 = (tmp1, tmp2) in
      (FStarC_Syntax_Syntax.Decreases_wf ((match tmp3 with (custard_tup, _) -> custard_tup), (match tmp3 with (_, custard_tup) -> custard_tup))))
  )

let subst_flags' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (eta : (FStarC_Syntax_Syntax.cflag) list) : (FStarC_Syntax_Syntax.cflag) list =
  (FStarC_List.map (fun tmp -> (match tmp with
    | (FStarC_Syntax_Syntax.DECREASES (dec_order)) -> (let tmp1 = (subst_dec_order' s dec_order) in
      (FStarC_Syntax_Syntax.DECREASES (tmp1)))
    | (FStarC_Syntax_Syntax.SMTPAT (p)) -> (let tmp1 = (subst' s p) in
      (FStarC_Syntax_Syntax.SMTPAT (tmp1)))
    | f -> f
  )) eta)

let subst_comp_typ' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (t : FStarC_Syntax_Syntax.comp_typ) : FStarC_Syntax_Syntax.comp_typ =
  (match s with
    | ([], FStarC_Syntax_Syntax.NoUseRange) -> t
    | (([] :: []), FStarC_Syntax_Syntax.NoUseRange) -> t
    | tmp -> (let tmp1 = (tag_lid_with_range (t).FStarC_Syntax_Syntax.effect_name s) in
      let tmp2 = (subst' s (t).FStarC_Syntax_Syntax.result_typ) in
      let tmp3 = (subst_flags' s (t).FStarC_Syntax_Syntax.flags) in
      let tmp4 = (tag_lid_with_range (t).FStarC_Syntax_Syntax.source_effect_name s) in
      { FStarC_Syntax_Syntax.effect_name = tmp1;
        result_typ = tmp2;
        flags = tmp3;
        source_effect_name = tmp4 })
  )

let subst_comp' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (t : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax =
  (match s with
    | ([], FStarC_Syntax_Syntax.NoUseRange) -> t
    | (([] :: []), FStarC_Syntax_Syntax.NoUseRange) -> t
    | tmp -> (let ct = (t).FStarC_Syntax_Syntax.n in
      let tmp1 = (subst_comp_typ' s ct) in
      (FStarC_Syntax_Syntax.mk_Comp tmp1))
  )

let subst_ascription' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (asc : (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax, (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) FStar_Pervasives.either * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * bool)) : (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax, (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) FStar_Pervasives.either * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * bool) =
  (match asc with
    | (annot, topt, use_eq) -> (let annot1 = (match annot with
          | (FStar_Pervasives.Inl (t)) -> (let tmp = (subst' s t) in
            (FStar_Pervasives.Inl (tmp)))
          | (FStar_Pervasives.Inr (c)) -> (let tmp = (subst_comp' s c) in
            (FStar_Pervasives.Inr (tmp)))
        ) in
      let tmp = (FStarC_Option.map (subst' s) topt) in
      (annot1, tmp, use_eq))
  )

let shift (n : Prims.int) (s : FStarC_Syntax_Syntax.subst_elt) : FStarC_Syntax_Syntax.subst_elt =
  (match s with
    | (FStarC_Syntax_Syntax.DB (i, t)) -> (FStarC_Syntax_Syntax.DB ((Prims.op_Plus i n), t))
    | (FStarC_Syntax_Syntax.DT (i, t)) -> (FStarC_Syntax_Syntax.DT ((Prims.op_Plus i n), t))
    | (FStarC_Syntax_Syntax.UN (i, t)) -> (FStarC_Syntax_Syntax.UN ((Prims.op_Plus i n), t))
    | (FStarC_Syntax_Syntax.NM (x, i)) -> (FStarC_Syntax_Syntax.NM (x, (Prims.op_Plus i n)))
    | (FStarC_Syntax_Syntax.UD (x, i)) -> (FStarC_Syntax_Syntax.UD (x, (Prims.op_Plus i n)))
    | (FStarC_Syntax_Syntax.NT (u__1, u__2)) -> s
  )

let shift_subst (n : Prims.int) : ((FStarC_Syntax_Syntax.subst_elt) list -> (FStarC_Syntax_Syntax.subst_elt) list) =
  (FStarC_List.map (shift n))

let shift_subst' (n : Prims.int) (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * 'tmp)) : (((FStarC_Syntax_Syntax.subst_elt) list) list * 'tmp) =
  (let tmp = (FStarC_List.map (shift_subst n) (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst s)) in
  (tmp, (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd s)))

let subst_bqual' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (i : (FStarC_Syntax_Syntax.binder_qualifier) option) : (FStarC_Syntax_Syntax.binder_qualifier) option =
  (match i with
    | (Some ((FStarC_Syntax_Syntax.Meta (t)))) -> (let tmp = (subst' s t) in
      let tmp1 = (FStarC_Syntax_Syntax.Meta (tmp)) in
      (Some (tmp1)))
    | tmp -> i
  )

let subst_binder' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (b : FStarC_Syntax_Syntax.binder) : FStarC_Syntax_Syntax.binder =
  (let tmp = (b).FStarC_Syntax_Syntax.binder_bv in
  let tmp1 = (subst' s ((b).FStarC_Syntax_Syntax.binder_bv).FStarC_Syntax_Syntax.sort) in
  let tmp2 = { FStarC_Syntax_Syntax.ppname = (tmp).FStarC_Syntax_Syntax.ppname;
      index = (tmp).FStarC_Syntax_Syntax.index;
      sort = tmp1 } in
  let tmp3 = (subst_bqual' s (b).FStarC_Syntax_Syntax.binder_qual) in
  let tmp4 = (FStarC_List.map (subst' s) (b).FStarC_Syntax_Syntax.binder_attrs) in
  (FStarC_Syntax_Syntax.mk_binder_with_attrs tmp2 tmp3 (b).FStarC_Syntax_Syntax.binder_positivity tmp4))

let push_subst_rc (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (lopt : (FStarC_Syntax_Syntax.residual_comp) option) : (FStarC_Syntax_Syntax.residual_comp) option =
  (match lopt with
    | None -> None
    | (Some (rc)) -> (let residual_typ = (FStarC_Option.map (subst' s) (rc).FStarC_Syntax_Syntax.residual_typ) in
      let rc1 = { FStarC_Syntax_Syntax.residual_effect = (rc).FStarC_Syntax_Syntax.residual_effect;
          residual_typ = residual_typ;
          residual_flags = (rc).FStarC_Syntax_Syntax.residual_flags } in
      (Some (rc1)))
  )

let subst_univs_opt (sub : ((FStarC_Syntax_Syntax.subst_elt) list) list) (us_opt : ((FStarC_Syntax_Syntax.universe) list) option) : ((FStarC_Syntax_Syntax.universe) list) option =
  (match us_opt with
    | None -> None
    | (Some (us)) -> (let tmp = (FStarC_List.map (subst_univ sub) us) in
      (Some (tmp)))
  )

let rec subst_pat'__aux (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (n : Prims.int) (p : (FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t) : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * Prims.int) =
  (match (p).FStarC_Syntax_Syntax.v with
    | (FStarC_Syntax_Syntax.Pat_constant (tmp)) -> (p, n)
    | (FStarC_Syntax_Syntax.Pat_cons (fv, us_opt, pats)) -> (let tmp = (shift_subst' n s) in
      let tmp1 = (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst tmp) in
      let us_opt1 = (subst_univs_opt tmp1 us_opt) in
      let tmp2 = (FStarC_List.fold_left (fun tmp2 tmp3 -> (match (tmp2, tmp3) with
          | ((pats1, n1), (p1, imp)) -> (let tmp4 = ((subst_pat'__aux s) n1 p1) in
            (match tmp4 with
              | (p2, m) -> (((p2, imp) :: pats1), m)
            ))
        )) ([], n) pats) in
      (match tmp2 with
        | (pats1, n1) -> ({ FStarC_Syntax_Syntax.v = (FStarC_Syntax_Syntax.Pat_cons (fv, us_opt1, (FStarC_List.rev pats1)));
            p = (p).FStarC_Syntax_Syntax.p }, n1)
      ))
    | (FStarC_Syntax_Syntax.Pat_var (x)) -> (let s1 = (shift_subst' n s) in
      let tmp = (subst' s1 (x).FStarC_Syntax_Syntax.sort) in
      let x1 = { FStarC_Syntax_Syntax.ppname = (x).FStarC_Syntax_Syntax.ppname;
          index = (x).FStarC_Syntax_Syntax.index;
          sort = tmp } in
      ({ FStarC_Syntax_Syntax.v = (FStarC_Syntax_Syntax.Pat_var (x1));
        p = (p).FStarC_Syntax_Syntax.p }, (Prims.op_Plus n (Prims.parse_int "1"))))
    | (FStarC_Syntax_Syntax.Pat_dot_term (eopt)) -> (let s1 = (shift_subst' n s) in
      let eopt1 = (FStarC_Option.map (subst' s1) eopt) in
      ({ FStarC_Syntax_Syntax.v = (FStarC_Syntax_Syntax.Pat_dot_term (eopt1));
        p = (p).FStarC_Syntax_Syntax.p }, n))
  )

let subst_pat' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (eta : (FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t) : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * Prims.int) =
  ((subst_pat'__aux s) (Prims.parse_int "0") eta)

let subst_args' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) : ((((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax * 'tmp)) list -> (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax * 'tmp)) list) =
  (FStarC_List.map (subst_arg' s))

let rec push_subst_aux (resolve_uvars : bool) (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let mk = (fun t' -> (let tmp = (mk_range (t).FStarC_Syntax_Syntax.pos s) in
    (FStarC_Syntax_Syntax.mk t' tmp))) in
  (match (t).FStarC_Syntax_Syntax.n with
    | (FStarC_Syntax_Syntax.Tm_delayed (tmp)) -> (FStarC_Effect.failwith "Impossible (delayed node in push_subst)")
    | (FStarC_Syntax_Syntax.Tm_lazy (i)) -> (match (i).FStarC_Syntax_Syntax.lkind with
        | (FStarC_Syntax_Syntax.Lazy_embedding (u__1, u__2)) -> (let tmp = (!(FStarC_Syntax_Syntax.lazy_chooser)) in
          let tmp1 = (FStarC_Option.must tmp) in
          let t1 = (tmp1 (i).FStarC_Syntax_Syntax.lkind i) in
          (push_subst_aux resolve_uvars s t1))
        | tmp -> (tag_with_range t s)
      )
    | (FStarC_Syntax_Syntax.Tm_constant (tmp)) -> (tag_with_range t s)
    | (FStarC_Syntax_Syntax.Tm_fvar (tmp)) -> (tag_with_range t s)
    | FStarC_Syntax_Syntax.Tm_unknown -> (tag_with_range t s)
    | (FStarC_Syntax_Syntax.Tm_uvar (uv, s0)) -> (let fallback = (fun tmp -> (let tmp1 = (compose_uvar_subst uv s0 s) in
        let tmp2 = (uv, tmp1) in
        let tmp3 = (FStarC_Syntax_Syntax.Tm_uvar ((match tmp2 with (custard_tup, _) -> custard_tup), (match tmp2 with (_, custard_tup) -> custard_tup))) in
        let tmp4 = { FStarC_Syntax_Syntax.n = tmp3;
            pos = (t).FStarC_Syntax_Syntax.pos;
            hash_code = (t).FStarC_Syntax_Syntax.hash_code } in
        (tag_with_range tmp4 s))) in
      (if (not resolve_uvars) then (fallback ()) else (let tmp = (FStarC_Syntax_Unionfind.find ((uv).FStarC_Syntax_Syntax.ctx_uvar_head, (uv).FStarC_Syntax_Syntax.ctx_uvar_head1, (uv).FStarC_Syntax_Syntax.ctx_uvar_head2)) in
      (match tmp with
        | None -> (fallback ())
        | (Some (t1)) -> (push_subst_aux resolve_uvars (compose_subst s0 s) t1)
      ))))
    | (FStarC_Syntax_Syntax.Tm_type (tmp)) -> (subst' s t)
    | (FStarC_Syntax_Syntax.Tm_bvar (tmp)) -> (subst' s t)
    | (FStarC_Syntax_Syntax.Tm_name (tmp)) -> (subst' s t)
    | (FStarC_Syntax_Syntax.Tm_uinst (t', us)) -> (let us1 = (FStarC_List.map (subst_univ (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst s)) us) in
      let tmp = (mk (FStarC_Syntax_Syntax.Tm_uinst (t', us1))) in
      (tag_with_range tmp s))
    | (FStarC_Syntax_Syntax.Tm_app ({ FStarC_Syntax_Syntax.hd = t0; arg = u__1; arg1 = u__2; _ })) -> (let tmp = (subst' s t0) in
      let tmp1 = (subst_arg' s (u__1, u__2)) in
      let tmp2 = { FStarC_Syntax_Syntax.hd = tmp;
          arg = (match tmp1 with (custard_tup, _) -> custard_tup);
          arg1 = (match tmp1 with (_, custard_tup) -> custard_tup) } in
      let tmp3 = (FStarC_Syntax_Syntax.Tm_app (tmp2)) in
      (mk tmp3))
    | (FStarC_Syntax_Syntax.Tm_ascribed ({ FStarC_Syntax_Syntax.tm = t0; asc = u__1; asc1 = u__2; asc2 = u__3; eff_opt = lopt; _ })) -> (let tmp = (subst' s t0) in
      let tmp1 = (subst_ascription' s (u__1, u__2, u__3)) in
      let tmp2 = ({ FStarC_Syntax_Syntax.tm = tmp;
          asc = (match tmp1 with (custard_tup, _, _) -> custard_tup);
          asc1 = (match tmp1 with (_, custard_tup, _) -> custard_tup);
          asc2 = (match tmp1 with (_, _, custard_tup) -> custard_tup);
          eff_opt = lopt } : FStarC_Syntax_Syntax.term'__Tm_ascribed__payload) in
      let tmp3 = (FStarC_Syntax_Syntax.Tm_ascribed (tmp2)) in
      (mk tmp3))
    | (FStarC_Syntax_Syntax.Tm_abs ({ FStarC_Syntax_Syntax.b = b; body = body; rc_opt = lopt; _ })) -> (let s' = (shift_subst' (Prims.parse_int "1") s) in
      let tmp = (subst_binder' s b) in
      let tmp1 = (subst' s' body) in
      let tmp2 = (push_subst_rc s' lopt) in
      let tmp3 = ({ FStarC_Syntax_Syntax.b = tmp; body = tmp1; rc_opt = tmp2 } : FStarC_Syntax_Syntax.term'__Tm_abs__payload) in
      let tmp4 = (FStarC_Syntax_Syntax.Tm_abs (tmp3)) in
      (mk tmp4))
    | (FStarC_Syntax_Syntax.Tm_arrow ({ FStarC_Syntax_Syntax.b = b; comp = comp; _ })) -> (let tmp = (subst_binder' s b) in
      let tmp1 = (shift_subst' (Prims.parse_int "1") s) in
      let tmp2 = (subst_comp' tmp1 comp) in
      let tmp3 = ({ FStarC_Syntax_Syntax.b = tmp; comp = tmp2 } : FStarC_Syntax_Syntax.term'__Tm_arrow__payload) in
      let tmp4 = (FStarC_Syntax_Syntax.Tm_arrow (tmp3)) in
      (mk tmp4))
    | (FStarC_Syntax_Syntax.Tm_refine ({ FStarC_Syntax_Syntax.b = x; phi = phi; _ })) -> (let tmp = (subst' s (x).FStarC_Syntax_Syntax.sort) in
      let x1 = { FStarC_Syntax_Syntax.ppname = (x).FStarC_Syntax_Syntax.ppname;
          index = (x).FStarC_Syntax_Syntax.index;
          sort = tmp } in
      let tmp1 = (shift_subst' (Prims.parse_int "1") s) in
      let phi1 = (subst' tmp1 phi) in
      (mk (FStarC_Syntax_Syntax.Tm_refine (({ FStarC_Syntax_Syntax.b = x1; phi = phi1 } : FStarC_Syntax_Syntax.term'__Tm_refine__payload)))))
    | (FStarC_Syntax_Syntax.Tm_match ({ FStarC_Syntax_Syntax.scrutinee = t0; ret_opt = asc_opt; brs = pats; rc_opt = lopt; _ })) -> (let t01 = (subst' s t0) in
      let pats1 = (FStarC_List.map (fun tmp -> (match tmp with
          | (pat, wopt, branch) -> (let tmp1 = (subst_pat' s pat) in
            (match tmp1 with
              | (pat1, n) -> (let s1 = (shift_subst' n s) in
                let wopt1 = (match wopt with
                    | None -> None
                    | (Some (w)) -> (let tmp2 = (subst' s1 w) in
                      (Some (tmp2)))
                  ) in
                let branch1 = (subst' s1 branch) in
                (pat1, wopt1, branch1))
            ))
        )) pats) in
      let asc_opt1 = (match asc_opt with
          | None -> None
          | (Some ((b, asc))) -> (let b1 = (subst_binder' s b) in
            let tmp = (shift_subst' (Prims.parse_int "1") s) in
            let asc1 = (subst_ascription' tmp asc) in
            (Some ((b1, asc1))))
        ) in
      let tmp = (push_subst_rc s lopt) in
      let tmp1 = ({ FStarC_Syntax_Syntax.scrutinee = t01;
          ret_opt = asc_opt1;
          brs = pats1;
          rc_opt = tmp } : FStarC_Syntax_Syntax.term'__Tm_match__payload) in
      let tmp2 = (FStarC_Syntax_Syntax.Tm_match (tmp1)) in
      (mk tmp2))
    | (FStarC_Syntax_Syntax.Tm_let ({ FStarC_Syntax_Syntax.lbs = is_rec; lbs1 = lbs; body = body; _ })) -> (let n = (FStarC_List.length lbs) in
      let sn = (shift_subst' n s) in
      let body1 = (subst' sn body) in
      let lbs1 = (FStarC_List.map (fun lb -> (let lbt = (subst' s (lb).FStarC_Syntax_Syntax.lbtyp) in
        let lbd = (if (is_rec && (match (lb).FStarC_Syntax_Syntax.lbname with
            | (FStar_Pervasives.Inl (v)) -> true
            | tmp -> false
          )) then (subst' sn (lb).FStarC_Syntax_Syntax.lbdef) else (subst' s (lb).FStarC_Syntax_Syntax.lbdef)) in
        let lbname = (match (lb).FStarC_Syntax_Syntax.lbname with
            | (FStar_Pervasives.Inl (x)) -> (FStar_Pervasives.Inl ({ FStarC_Syntax_Syntax.ppname = (x).FStarC_Syntax_Syntax.ppname;
                index = (x).FStarC_Syntax_Syntax.index;
                sort = lbt }))
            | (FStar_Pervasives.Inr (fv)) -> (FStar_Pervasives.Inr (fv))
          ) in
        let lbattrs = (FStarC_List.map (subst' s) (lb).FStarC_Syntax_Syntax.lbattrs) in
        { FStarC_Syntax_Syntax.lbname = lbname;
          lbunivs = (lb).FStarC_Syntax_Syntax.lbunivs;
          lbtyp = lbt;
          lbeff = (lb).FStarC_Syntax_Syntax.lbeff;
          lbdef = lbd;
          lbattrs = lbattrs;
          lbpos = (lb).FStarC_Syntax_Syntax.lbpos })) lbs) in
      (mk (FStarC_Syntax_Syntax.Tm_let (({ FStarC_Syntax_Syntax.lbs = is_rec; lbs1 = lbs1; body = body1 } : FStarC_Syntax_Syntax.term'__Tm_let__payload)))))
    | (FStarC_Syntax_Syntax.Tm_meta ({ FStarC_Syntax_Syntax.tm = t0; meta = (FStarC_Syntax_Syntax.Meta_pattern (bs, ps)); _ })) -> (let tmp = (subst' s t0) in
      let tmp1 = (FStarC_List.map (subst' s) bs) in
      let tmp2 = (FStarC_List.map (subst_args' s) ps) in
      let tmp3 = (tmp1, tmp2) in
      let tmp4 = (FStarC_Syntax_Syntax.Meta_pattern ((match tmp3 with (custard_tup, _) -> custard_tup), (match tmp3 with (_, custard_tup) -> custard_tup))) in
      let tmp5 = ({ FStarC_Syntax_Syntax.tm = tmp; meta = tmp4 } : FStarC_Syntax_Syntax.term'__Tm_meta__payload) in
      let tmp6 = (FStarC_Syntax_Syntax.Tm_meta (tmp5)) in
      (mk tmp6))
    | (FStarC_Syntax_Syntax.Tm_meta ({ FStarC_Syntax_Syntax.tm = t0; meta = (FStarC_Syntax_Syntax.Meta_monadic (m, t1)); _ })) -> (let tmp = (subst' s t0) in
      let tmp1 = (subst' s t1) in
      let tmp2 = (m, tmp1) in
      let tmp3 = (FStarC_Syntax_Syntax.Meta_monadic ((match tmp2 with (custard_tup, _) -> custard_tup), (match tmp2 with (_, custard_tup) -> custard_tup))) in
      let tmp4 = ({ FStarC_Syntax_Syntax.tm = tmp; meta = tmp3 } : FStarC_Syntax_Syntax.term'__Tm_meta__payload) in
      let tmp5 = (FStarC_Syntax_Syntax.Tm_meta (tmp4)) in
      (mk tmp5))
    | (FStarC_Syntax_Syntax.Tm_meta ({ FStarC_Syntax_Syntax.tm = t0; meta = (FStarC_Syntax_Syntax.Meta_monadic_lift (m1, m2, t1)); _ })) -> (let tmp = (subst' s t0) in
      let tmp1 = (subst' s t1) in
      let tmp2 = (m1, m2, tmp1) in
      let tmp3 = (FStarC_Syntax_Syntax.Meta_monadic_lift ((match tmp2 with (custard_tup, _, _) -> custard_tup), (match tmp2 with (_, custard_tup, _) -> custard_tup), (match tmp2 with (_, _, custard_tup) -> custard_tup))) in
      let tmp4 = ({ FStarC_Syntax_Syntax.tm = tmp; meta = tmp3 } : FStarC_Syntax_Syntax.term'__Tm_meta__payload) in
      let tmp5 = (FStarC_Syntax_Syntax.Tm_meta (tmp4)) in
      (mk tmp5))
    | (FStarC_Syntax_Syntax.Tm_quoted (tm, qi)) -> (match (qi).FStarC_Syntax_Syntax.qkind with
        | FStarC_Syntax_Syntax.Quote_dynamic -> (let tmp = (subst' s tm) in
          let tmp1 = (tmp, qi) in
          let tmp2 = (FStarC_Syntax_Syntax.Tm_quoted ((match tmp1 with (custard_tup, _) -> custard_tup), (match tmp1 with (_, custard_tup) -> custard_tup))) in
          (mk tmp2))
        | FStarC_Syntax_Syntax.Quote_static -> (let qi1 = (FStarC_Syntax_Syntax.on_antiquoted (subst' s) qi) in
          (mk (FStarC_Syntax_Syntax.Tm_quoted (tm, qi1))))
      )
    | (FStarC_Syntax_Syntax.Tm_meta ({ FStarC_Syntax_Syntax.tm = t1; meta = m; _ })) -> (let tmp = (subst' s t1) in
      let tmp1 = ({ FStarC_Syntax_Syntax.tm = tmp; meta = m } : FStarC_Syntax_Syntax.term'__Tm_meta__payload) in
      let tmp2 = (FStarC_Syntax_Syntax.Tm_meta (tmp1)) in
      (mk tmp2))
  ))

let push_subst (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (push_subst_aux true s t)

let rec compress_slow (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let t1 = (force_uvar t) in
  (match (t1).FStarC_Syntax_Syntax.n with
    | (FStarC_Syntax_Syntax.Tm_delayed ({ FStarC_Syntax_Syntax.tm = t'; substs = u__1; substs1 = u__2; _ })) -> (let tmp = (push_subst (u__1, u__2) t') in
      (compress tmp))
    | tmp -> t1
  ))

and compress (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (match (t).FStarC_Syntax_Syntax.n with
    | (FStarC_Syntax_Syntax.Tm_delayed (tmp)) -> (compress_slow t)
    | (FStarC_Syntax_Syntax.Tm_uvar (u__1, u__2)) -> (compress_slow t)
    | tmp -> t
  )

let subst (s : (FStarC_Syntax_Syntax.subst_elt) list) : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax -> (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (subst' ((s :: []), FStarC_Syntax_Syntax.NoUseRange))

let subst_bqual (s : (FStarC_Syntax_Syntax.subst_elt) list) (i : (FStarC_Syntax_Syntax.binder_qualifier) option) : (FStarC_Syntax_Syntax.binder_qualifier) option =
  (subst_bqual' ((s :: []), FStarC_Syntax_Syntax.NoUseRange) i)

let rec open_binders'__aux (bs : (FStarC_Syntax_Syntax.binder) list) (o : (FStarC_Syntax_Syntax.subst_elt) list) : ((FStarC_Syntax_Syntax.binder) list * (FStarC_Syntax_Syntax.subst_elt) list) =
  (match bs with
    | [] -> ([], o)
    | (b :: bs') -> (let tmp = (FStarC_Syntax_Syntax.freshen_bv (b).FStarC_Syntax_Syntax.binder_bv) in
      let tmp1 = (subst o ((b).FStarC_Syntax_Syntax.binder_bv).FStarC_Syntax_Syntax.sort) in
      let x' = { FStarC_Syntax_Syntax.ppname = (tmp).FStarC_Syntax_Syntax.ppname;
          index = (tmp).FStarC_Syntax_Syntax.index;
          sort = tmp1 } in
      let imp = (subst_bqual o (b).FStarC_Syntax_Syntax.binder_qual) in
      let attrs = (FStarC_List.map (subst o) (b).FStarC_Syntax_Syntax.binder_attrs) in
      let tmp2 = (shift_subst (Prims.parse_int "1") o) in
      let o1 = ((FStarC_Syntax_Syntax.DB ((Prims.parse_int "0"), x')) :: tmp2) in
      let tmp3 = (open_binders'__aux bs' o1) in
      (match tmp3 with
        | (bs'1, o2) -> (((FStarC_Syntax_Syntax.mk_binder_with_attrs x' imp (b).FStarC_Syntax_Syntax.binder_positivity attrs) :: bs'1), o2)
      ))
  )

let open_binders' (bs : (FStarC_Syntax_Syntax.binder) list) : ((FStarC_Syntax_Syntax.binder) list * (FStarC_Syntax_Syntax.subst_elt) list) =
  (open_binders'__aux bs [])

let open_term' (bs : (FStarC_Syntax_Syntax.binder) list) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : ((FStarC_Syntax_Syntax.binder) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax * (FStarC_Syntax_Syntax.subst_elt) list) =
  (let tmp = (open_binders' bs) in
  (match tmp with
    | (bs', opening) -> (let tmp1 = (subst opening t) in
      (bs', tmp1, opening))
  ))

let open_term (bs : (FStarC_Syntax_Syntax.binder) list) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : ((FStarC_Syntax_Syntax.binder) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (let tmp = (open_term' bs t) in
  (match tmp with
    | (b, t1, tmp1) -> (b, t1)
  ))

let subst_comp (s : (FStarC_Syntax_Syntax.subst_elt) list) (t : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax =
  (subst_comp' ((s :: []), FStarC_Syntax_Syntax.NoUseRange) t)

let open_comp (bs : (FStarC_Syntax_Syntax.binder) list) (t : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : ((FStarC_Syntax_Syntax.binder) list * (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) =
  (let tmp = (open_binders' bs) in
  (match tmp with
    | (bs', opening) -> (let tmp1 = (subst_comp opening t) in
      (bs', tmp1))
  ))

let subst_ascription (s : (FStarC_Syntax_Syntax.subst_elt) list) (asc : (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax, (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) FStar_Pervasives.either * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * bool)) : (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax, (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) FStar_Pervasives.either * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * bool) =
  (subst_ascription' ((s :: []), FStarC_Syntax_Syntax.NoUseRange) asc)

let open_ascription (bs : (FStarC_Syntax_Syntax.binder) list) (asc : (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax, (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) FStar_Pervasives.either * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * bool)) : ((FStarC_Syntax_Syntax.binder) list * (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax, (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) FStar_Pervasives.either * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * bool)) =
  (let tmp = (open_binders' bs) in
  (match tmp with
    | (bs', opening) -> (let tmp1 = (subst_ascription opening asc) in
      (bs', tmp1))
  ))

let rec open_pat__open_pat_aux (sub : (FStarC_Syntax_Syntax.subst_elt) list) (p : (FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t) : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * (FStarC_Syntax_Syntax.subst_elt) list) =
  (match (p).FStarC_Syntax_Syntax.v with
    | (FStarC_Syntax_Syntax.Pat_constant (tmp)) -> (p, sub)
    | (FStarC_Syntax_Syntax.Pat_cons (fv, us_opt, pats)) -> (let us_opt1 = (subst_univs_opt (sub :: []) us_opt) in
      let tmp = (FStarC_List.fold_left (fun tmp tmp1 -> (match (tmp, tmp1) with
          | ((pats1, sub1), (p1, imp)) -> (let tmp2 = (open_pat__open_pat_aux sub1 p1) in
            (match tmp2 with
              | (p2, sub2) -> (((p2, imp) :: pats1), sub2)
            ))
        )) ([], sub) pats) in
      (match tmp with
        | (pats1, sub1) -> ({ FStarC_Syntax_Syntax.v = (FStarC_Syntax_Syntax.Pat_cons (fv, us_opt1, (FStarC_List.rev pats1)));
            p = (p).FStarC_Syntax_Syntax.p }, sub1)
      ))
    | (FStarC_Syntax_Syntax.Pat_var (x)) -> (let tmp = (FStarC_Syntax_Syntax.freshen_bv x) in
      let tmp1 = (subst sub (x).FStarC_Syntax_Syntax.sort) in
      let x' = { FStarC_Syntax_Syntax.ppname = (tmp).FStarC_Syntax_Syntax.ppname;
          index = (tmp).FStarC_Syntax_Syntax.index;
          sort = tmp1 } in
      let tmp2 = (shift_subst (Prims.parse_int "1") sub) in
      let sub1 = ((FStarC_Syntax_Syntax.DB ((Prims.parse_int "0"), x')) :: tmp2) in
      ({ FStarC_Syntax_Syntax.v = (FStarC_Syntax_Syntax.Pat_var (x'));
        p = (p).FStarC_Syntax_Syntax.p }, sub1))
    | (FStarC_Syntax_Syntax.Pat_dot_term (eopt)) -> (let eopt1 = (FStarC_Option.map (subst sub) eopt) in
      ({ FStarC_Syntax_Syntax.v = (FStarC_Syntax_Syntax.Pat_dot_term (eopt1));
        p = (p).FStarC_Syntax_Syntax.p }, sub))
  )

let open_pat (p : (FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t) : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * (FStarC_Syntax_Syntax.subst_elt) list) =
  (open_pat__open_pat_aux [] p)

let open_branch' (br : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) : (((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) * (FStarC_Syntax_Syntax.subst_elt) list) =
  (match br with
    | (p, wopt, e) -> (let tmp = (open_pat p) in
      (match tmp with
        | (p1, opening) -> (let wopt1 = (match wopt with
              | None -> None
              | (Some (w)) -> (let tmp1 = (subst opening w) in
                (Some (tmp1)))
            ) in
          let e1 = (subst opening e) in
          ((p1, wopt1, e1), opening))
      ))
  )

let open_branch (br : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (let tmp = (open_branch' br) in
  (match tmp with
    | (br1, tmp1) -> br1
  ))

let open_let_rec (lbs : (FStarC_Syntax_Syntax.letbinding) list) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : ((FStarC_Syntax_Syntax.letbinding) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (let tmp = (if (FStarC_Syntax_Syntax.is_top_level lbs) then ((Prims.parse_int "0"), lbs, []) else (FStarC_List.fold_right (fun lb tmp -> (match tmp with
      | (i, lbs1, out) -> (let x = (FStarC_Syntax_Syntax.freshen_bv (match (lb).FStarC_Syntax_Syntax.lbname with
            | (FStar_Pervasives.Inl (v)) -> v
          )) in
        ((Prims.op_Plus i (Prims.parse_int "1")), ({ FStarC_Syntax_Syntax.lbname = (FStar_Pervasives.Inl (x));
          lbunivs = (lb).FStarC_Syntax_Syntax.lbunivs;
          lbtyp = (lb).FStarC_Syntax_Syntax.lbtyp;
          lbeff = (lb).FStarC_Syntax_Syntax.lbeff;
          lbdef = (lb).FStarC_Syntax_Syntax.lbdef;
          lbattrs = (lb).FStarC_Syntax_Syntax.lbattrs;
          lbpos = (lb).FStarC_Syntax_Syntax.lbpos } :: lbs1), ((FStarC_Syntax_Syntax.DB (i, x)) :: out)))
    )) lbs ((Prims.parse_int "0"), [], []))) in
  (match tmp with
    | (n_let_recs, lbs1, let_rec_opening) -> (let tmp1 = (FStarC_List.fold_right (fun u tmp1 -> (match tmp1 with
          | (i, us, out) -> (let u1 = (FStarC_Syntax_Syntax.new_univ_name None) in
            ((Prims.op_Plus i (Prims.parse_int "1")), (u1 :: us), ((FStarC_Syntax_Syntax.UN (i, (FStarC_Syntax_Syntax.U_name (u1)))) :: out)))
        )) (let scrut = (FStarC_List.hd lbs1) in
        (scrut).FStarC_Syntax_Syntax.lbunivs) (n_let_recs, [], let_rec_opening)) in
      (match tmp1 with
        | (tmp2, us, u_let_rec_opening) -> (let lbs2 = (FStarC_List.map (fun lb -> (let tmp3 = (subst u_let_rec_opening (lb).FStarC_Syntax_Syntax.lbtyp) in
            let tmp4 = (subst u_let_rec_opening (lb).FStarC_Syntax_Syntax.lbdef) in
            { FStarC_Syntax_Syntax.lbname = (lb).FStarC_Syntax_Syntax.lbname;
              lbunivs = us;
              lbtyp = tmp3;
              lbeff = (lb).FStarC_Syntax_Syntax.lbeff;
              lbdef = tmp4;
              lbattrs = (lb).FStarC_Syntax_Syntax.lbattrs;
              lbpos = (lb).FStarC_Syntax_Syntax.lbpos })) lbs1) in
          let t1 = (subst let_rec_opening t) in
          (lbs2, t1))
      ))
  ))

let set_use_range (r : FStarC_Range_Type.range) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (subst' ([], (FStarC_Syntax_Syntax.SomeUseRange ((FStarC_Range_Type.set_def_range r (FStarC_Range_Type.use_range r))))) t)

let closing_subst (bs : (FStarC_Syntax_Syntax.binder) list) : (FStarC_Syntax_Syntax.subst_elt) list =
  (let tmp = (FStarC_List.fold_right (fun b tmp -> (match tmp with
      | (subst_, n) -> (((FStarC_Syntax_Syntax.NM ((b).FStarC_Syntax_Syntax.binder_bv, n)) :: subst_), (Prims.op_Plus n (Prims.parse_int "1")))
    )) bs ([], (Prims.parse_int "0"))) in
  (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst tmp))

let close (bs : (FStarC_Syntax_Syntax.binder) list) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let tmp = (closing_subst bs) in
  (subst tmp t))

let rec close_binders__aux (s : (FStarC_Syntax_Syntax.subst_elt) list) (bs : (FStarC_Syntax_Syntax.binder) list) : (FStarC_Syntax_Syntax.binder) list =
  (match bs with
    | [] -> []
    | (b :: tl) -> (let tmp = (b).FStarC_Syntax_Syntax.binder_bv in
      let tmp1 = (subst s ((b).FStarC_Syntax_Syntax.binder_bv).FStarC_Syntax_Syntax.sort) in
      let x = { FStarC_Syntax_Syntax.ppname = (tmp).FStarC_Syntax_Syntax.ppname;
          index = (tmp).FStarC_Syntax_Syntax.index;
          sort = tmp1 } in
      let imp = (subst_bqual s (b).FStarC_Syntax_Syntax.binder_qual) in
      let attrs = (FStarC_List.map (subst s) (b).FStarC_Syntax_Syntax.binder_attrs) in
      let tmp2 = (shift_subst (Prims.parse_int "1") s) in
      let s' = ((FStarC_Syntax_Syntax.NM (x, (Prims.parse_int "0"))) :: tmp2) in
      let tmp3 = (close_binders__aux s' tl) in
      ((FStarC_Syntax_Syntax.mk_binder_with_attrs x imp (b).FStarC_Syntax_Syntax.binder_positivity attrs) :: tmp3))
  )

let close_binders (bs : (FStarC_Syntax_Syntax.binder) list) : (FStarC_Syntax_Syntax.binder) list =
  (close_binders__aux [] bs)

let open_term_bvs (bvs : (FStarC_Syntax_Syntax.bv) list) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : ((FStarC_Syntax_Syntax.bv) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (let tmp = (FStarC_List.map FStarC_Syntax_Syntax.mk_binder bvs) in
  let tmp1 = (open_term tmp t) in
  (match tmp1 with
    | (bs, t1) -> (let tmp2 = (FStarC_List.map (fun b -> (b).FStarC_Syntax_Syntax.binder_bv) bs) in
      (tmp2, t1))
  ))

let open_term_bv (bv : FStarC_Syntax_Syntax.bv) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.bv * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (let tmp = (open_term_bvs (bv :: []) t) in
  (match tmp with
    | ((bv1 :: []), t1) -> (bv1, t1)
    | tmp1 -> (FStarC_Effect.failwith "impossible: open_term_bv")
  ))

let rec close_pat__aux (sub : (FStarC_Syntax_Syntax.subst_elt) list) (p : (FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t) : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * (FStarC_Syntax_Syntax.subst_elt) list) =
  (match (p).FStarC_Syntax_Syntax.v with
    | (FStarC_Syntax_Syntax.Pat_constant (tmp)) -> (p, sub)
    | (FStarC_Syntax_Syntax.Pat_cons (fv, us_opt, pats)) -> (let us_opt1 = (subst_univs_opt (sub :: []) us_opt) in
      let tmp = (FStarC_List.fold_left (fun tmp tmp1 -> (match (tmp, tmp1) with
          | ((pats1, sub1), (p1, imp)) -> (let tmp2 = (close_pat__aux sub1 p1) in
            (match tmp2 with
              | (p2, sub2) -> (((p2, imp) :: pats1), sub2)
            ))
        )) ([], sub) pats) in
      (match tmp with
        | (pats1, sub1) -> ({ FStarC_Syntax_Syntax.v = (FStarC_Syntax_Syntax.Pat_cons (fv, us_opt1, (FStarC_List.rev pats1)));
            p = (p).FStarC_Syntax_Syntax.p }, sub1)
      ))
    | (FStarC_Syntax_Syntax.Pat_var (x)) -> (let tmp = (subst sub (x).FStarC_Syntax_Syntax.sort) in
      let x1 = { FStarC_Syntax_Syntax.ppname = (x).FStarC_Syntax_Syntax.ppname;
          index = (x).FStarC_Syntax_Syntax.index;
          sort = tmp } in
      let tmp1 = (shift_subst (Prims.parse_int "1") sub) in
      let sub1 = ((FStarC_Syntax_Syntax.NM (x1, (Prims.parse_int "0"))) :: tmp1) in
      ({ FStarC_Syntax_Syntax.v = (FStarC_Syntax_Syntax.Pat_var (x1));
        p = (p).FStarC_Syntax_Syntax.p }, sub1))
    | (FStarC_Syntax_Syntax.Pat_dot_term (eopt)) -> (let eopt1 = (FStarC_Option.map (subst sub) eopt) in
      ({ FStarC_Syntax_Syntax.v = (FStarC_Syntax_Syntax.Pat_dot_term (eopt1));
        p = (p).FStarC_Syntax_Syntax.p }, sub))
  )

let close_pat (p : (FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t) : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * (FStarC_Syntax_Syntax.subst_elt) list) =
  (close_pat__aux [] p)

let close_branch (br : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax)) : ((FStarC_Syntax_Syntax.pat') FStarC_Syntax_Syntax.withinfo_t * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (match br with
    | (p, wopt, e) -> (let tmp = (close_pat p) in
      (match tmp with
        | (p1, closing) -> (let wopt1 = (match wopt with
              | None -> None
              | (Some (w)) -> (let tmp1 = (subst closing w) in
                (Some (tmp1)))
            ) in
          let e1 = (subst closing e) in
          (p1, wopt1, e1))
      ))
  )

let close_ascription (bs : (FStarC_Syntax_Syntax.binder) list) (asc : (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax, (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) FStar_Pervasives.either * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * bool)) : (((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax, (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) FStar_Pervasives.either * ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option * bool) =
  (let tmp = (closing_subst bs) in
  (subst_ascription tmp asc))

let close_comp (bs : (FStarC_Syntax_Syntax.binder) list) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax =
  (let tmp = (closing_subst bs) in
  (subst_comp tmp c))

let univ_var_opening (us : (FStarC_Ident.ident) list) : ((FStarC_Syntax_Syntax.subst_elt) list * (FStarC_Ident.ident) list) =
  (let n = (Prims.op_Minus (FStarC_List.length us) (Prims.parse_int "1")) in
  let s = (FStarC_List.mapi (fun i u -> (FStarC_Syntax_Syntax.UN ((Prims.op_Minus n i), (FStarC_Syntax_Syntax.U_name (u))))) us) in
  (s, us))

let open_univ_vars (us : (FStarC_Ident.ident) list) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : ((FStarC_Ident.ident) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (let tmp = (univ_var_opening us) in
  (match tmp with
    | (s, us') -> (let t1 = (subst s t) in
      (us', t1))
  ))

let univ_var_closing (us : (FStarC_Ident.ident) list) : (FStarC_Syntax_Syntax.subst_elt) list =
  (let n = (Prims.op_Minus (FStarC_List.length us) (Prims.parse_int "1")) in
  (FStarC_List.mapi (fun i u -> (FStarC_Syntax_Syntax.UD (u, (Prims.op_Minus n i)))) us))

let close_univ_vars (us : (FStarC_Ident.ident) list) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (let s = (univ_var_closing us) in
  (subst s t))

let subst_binders' (s : (((FStarC_Syntax_Syntax.subst_elt) list) list * FStarC_Syntax_Syntax.maybe_set_use_range)) (eta : (FStarC_Syntax_Syntax.binder) list) : (FStarC_Syntax_Syntax.binder) list =
  (FStarC_List.mapi (fun i b -> (if ((=) i (Prims.parse_int "0")) then (subst_binder' s b) else (let tmp = (shift_subst' i s) in
  (subst_binder' tmp b)))) eta)

let subst_binders (s : (FStarC_Syntax_Syntax.subst_elt) list) (eta : (FStarC_Syntax_Syntax.binder) list) : (FStarC_Syntax_Syntax.binder) list =
  (subst_binders' ((s :: []), FStarC_Syntax_Syntax.NoUseRange) eta)

let close_let_rec (lbs : (FStarC_Syntax_Syntax.letbinding) list) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : ((FStarC_Syntax_Syntax.letbinding) list * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (let tmp = (if (FStarC_Syntax_Syntax.is_top_level lbs) then ((Prims.parse_int "0"), []) else (FStarC_List.fold_right (fun lb tmp -> (match tmp with
      | (i, out) -> ((Prims.op_Plus i (Prims.parse_int "1")), ((FStarC_Syntax_Syntax.NM ((match (lb).FStarC_Syntax_Syntax.lbname with
          | (FStar_Pervasives.Inl (v)) -> v
        ), i)) :: out))
    )) lbs ((Prims.parse_int "0"), []))) in
  (match tmp with
    | (n_let_recs, let_rec_closing) -> (let tmp1 = (FStarC_List.fold_right (fun u tmp1 -> (match tmp1 with
          | (i, out) -> ((Prims.op_Plus i (Prims.parse_int "1")), ((FStarC_Syntax_Syntax.UD (u, i)) :: out))
        )) (let scrut = (FStarC_List.hd lbs) in
        (scrut).FStarC_Syntax_Syntax.lbunivs) (n_let_recs, let_rec_closing)) in
      (match tmp1 with
        | (tmp2, u_let_rec_closing) -> (let lbs1 = (FStarC_List.map (fun lb -> (let tmp3 = (subst u_let_rec_closing (lb).FStarC_Syntax_Syntax.lbtyp) in
            let tmp4 = (subst u_let_rec_closing (lb).FStarC_Syntax_Syntax.lbdef) in
            { FStarC_Syntax_Syntax.lbname = (lb).FStarC_Syntax_Syntax.lbname;
              lbunivs = (lb).FStarC_Syntax_Syntax.lbunivs;
              lbtyp = tmp3;
              lbeff = (lb).FStarC_Syntax_Syntax.lbeff;
              lbdef = tmp4;
              lbattrs = (lb).FStarC_Syntax_Syntax.lbattrs;
              lbpos = (lb).FStarC_Syntax_Syntax.lbpos })) lbs) in
          let t1 = (subst let_rec_closing t) in
          (lbs1, t1))
      ))
  ))

let closing_of_binders (bs : (FStarC_Syntax_Syntax.binder) list) : (FStarC_Syntax_Syntax.subst_elt) list =
  (closing_subst bs)

let subst_residual_comp (s : (FStarC_Syntax_Syntax.subst_elt) list) (rc : FStarC_Syntax_Syntax.residual_comp) : FStarC_Syntax_Syntax.residual_comp =
  (match (rc).FStarC_Syntax_Syntax.residual_typ with
    | None -> rc
    | (Some (t)) -> (let tmp = (subst s t) in
      let tmp1 = (Some (tmp)) in
      { FStarC_Syntax_Syntax.residual_effect = (rc).FStarC_Syntax_Syntax.residual_effect;
        residual_typ = tmp1;
        residual_flags = (rc).FStarC_Syntax_Syntax.residual_flags })
  )

let open_term_1 (b : FStarC_Syntax_Syntax.binder) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.binder * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (let tmp = (open_term (b :: []) t) in
  (match tmp with
    | ((b1 :: []), t1) -> (b1, t1)
    | tmp1 -> (FStarC_Effect.failwith "impossible: open_term_1")
  ))

let subst_binder (s : (FStarC_Syntax_Syntax.subst_elt) list) (b : FStarC_Syntax_Syntax.binder) : FStarC_Syntax_Syntax.binder =
  (subst_binder' ((s :: []), FStarC_Syntax_Syntax.NoUseRange) b)

let subst_decreasing_order (s : (FStarC_Syntax_Syntax.subst_elt) list) (tmp : FStarC_Syntax_Syntax.decreases_order) : FStarC_Syntax_Syntax.decreases_order =
  (subst_dec_order' ((s :: []), FStarC_Syntax_Syntax.NoUseRange) tmp)

let compress_subst (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax =
  (match (t).FStarC_Syntax_Syntax.n with
    | (FStarC_Syntax_Syntax.Tm_delayed ({ FStarC_Syntax_Syntax.tm = t1; substs = u__1; substs1 = u__2; _ })) -> (let resolve_uvars = false in
      (push_subst_aux resolve_uvars (u__1, u__2) t1))
    | tmp -> t
  )

let open_binders (bs : (FStarC_Syntax_Syntax.binder) list) : (FStarC_Syntax_Syntax.binder) list =
  (let tmp = (open_binders' bs) in
  (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst tmp))

let opening_of_binders (bs : (FStarC_Syntax_Syntax.binder) list) : (FStarC_Syntax_Syntax.subst_elt) list =
  (let n = (Prims.op_Minus (FStarC_List.length bs) (Prims.parse_int "1")) in
  (FStarC_List.mapi (fun i b -> (FStarC_Syntax_Syntax.DB ((Prims.op_Minus n i), (b).FStarC_Syntax_Syntax.binder_bv))) bs))

