(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

type width =
  | UInt8
  | UInt16
  | UInt32
  | UInt64
  | Int8
  | Int16
  | Int32
  | Int64
  | Bool
  | CInt
  | SizeT
  | PtrdiffT
  | Float32
  | Float64


type typ =
  | TInt of width
  | TBuf of typ
  | TUnit
  | TQualified of ((string) list * string)
  | TBool
  | TAny
  | TArrow of (typ * typ)
  | TBound of Prims.int
  | TApp of (((string) list * string) * (typ) list)
  | TTuple of (typ) list
  | TConstBuf of typ
  | TArray of (typ * (width * string))


type flag =
  | Private
  | WipeBody
  | CInline
  | Substitute
  | GCType
  | Comment of string
  | MustDisappear
  | Const of string
  | Prologue of string
  | Epilogue of string
  | Abstract
  | IfDef
  | Macro
  | Deprecated of string
  | CNoInline


type binder = {
  name : string;
  typ : typ;
  mut : bool;
  meta : (flag) list;
}

type lifetime =
  | Eternal
  | Stack
  | ManuallyManaged


type pattern =
  | PUnit
  | PBool of bool
  | PVar of binder
  | PCons of (string * (pattern) list)
  | PTuple of (pattern) list
  | PRecord of ((string * pattern)) list
  | PConstant of (width * string)


type op =
  | Add
  | AddW
  | Sub
  | SubW
  | Div
  | DivW
  | Mult
  | MultW
  | Mod
  | BOr
  | BAnd
  | BXor
  | BShiftL
  | BShiftR
  | BNot
  | Eq
  | Neq
  | Lt
  | Lte
  | Gt
  | Gte
  | And
  | Or
  | Xor
  | Not


type expr =
  | EBound of Prims.int
  | EQualified of ((string) list * string)
  | EConstant of (width * string)
  | EUnit
  | EApp of (expr * (expr) list)
  | ETypApp of (expr * (typ) list)
  | ELet of (binder * expr * expr)
  | EIfThenElse of (expr * expr * expr)
  | ESequence of (expr) list
  | EAssign of (expr * expr)
  | EBufCreate of (lifetime * expr * expr)
  | EBufRead of (expr * expr)
  | EBufWrite of (expr * expr * expr)
  | EBufSub of (expr * expr)
  | EBufBlit of (expr * expr * expr * expr * expr)
  | EMatch of (expr * ((pattern * expr)) list)
  | EOp of (op * width)
  | ECast of (expr * typ)
  | EPushFrame
  | EPopFrame
  | EBool of bool
  | EAny
  | EAbort
  | EReturn of expr
  | EFlat of (typ * ((string * expr)) list)
  | EField of (typ * expr * string)
  | EWhile of (expr * expr)
  | EBufCreateL of (lifetime * (expr) list)
  | ETuple of (expr) list
  | ECons of (typ * string * (expr) list)
  | EBufFill of (expr * expr * expr)
  | EString of string
  | EFun of ((binder) list * expr * typ)
  | EAbortS of string
  | EBufFree of expr
  | EBufCreateNoInit of (lifetime * expr)
  | EAbortT of (string * typ)
  | EComment of (string * expr * string)
  | EStandaloneComment of string
  | EAddrOf of expr
  | EBufNull of typ
  | EBufDiff of (expr * expr)
  | ESizeof of typ


type cc =
  | StdCall
  | CDecl
  | FastCall


type decl =
  | DGlobal of ((flag) list * ((string) list * string) * Prims.int * typ * expr)
  | DFunction of ((cc) option * (flag) list * Prims.int * typ * ((string) list * string) * (binder) list * expr)
  | DTypeAlias of (((string) list * string) * (flag) list * Prims.int * typ)
  | DTypeFlat of (((string) list * string) * (flag) list * Prims.int * ((string * (typ * bool))) list)
  | DUnusedRetainedForBackwardsCompat of ((cc) option * (flag) list * ((string) list * string) * typ)
  | DTypeVariant of (((string) list * string) * (flag) list * Prims.int * ((string * ((string * (typ * bool))) list)) list)
  | DTypeAbstractStruct of ((string) list * string)
  | DExternal of ((cc) option * (flag) list * ((string) list * string) * typ * (string) list)
  | DUntaggedUnion of (((string) list * string) * (flag) list * Prims.int * ((string * typ)) list)


let ctor (n : string) (args : (FStar_Pprint.document) list) : FStar_Pprint.document =
  (FStar_Pprint.nest (Prims.parse_int "2") (FStar_Pprint.group (FStar_Pprint.parens (FStar_Pprint.flow (FStar_Pprint.break_ (Prims.parse_int "1")) ((FStar_Pprint.doc_of_string n) :: args)))))

let fStarC_Class_PP_pp__flag (tmp : flag) : FStar_Pprint.document =
  (match tmp with
    | Private -> (FStar_Pprint.doc_of_string "Private")
    | WipeBody -> (FStar_Pprint.doc_of_string "WipeBody")
    | CInline -> (FStar_Pprint.doc_of_string "CInline")
    | Substitute -> (FStar_Pprint.doc_of_string "Substitute")
    | GCType -> (FStar_Pprint.doc_of_string "GCType")
    | (Comment (s)) -> (let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string s) in
      let tmp2 = (tmp1 :: []) in
      (ctor "Comment" tmp2))
    | MustDisappear -> (FStar_Pprint.doc_of_string "MustDisappear")
    | (Const (s)) -> (let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string s) in
      let tmp2 = (tmp1 :: []) in
      (ctor "Const" tmp2))
    | (Prologue (s)) -> (let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string s) in
      let tmp2 = (tmp1 :: []) in
      (ctor "Prologue" tmp2))
    | (Epilogue (s)) -> (let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string s) in
      let tmp2 = (tmp1 :: []) in
      (ctor "Epilogue" tmp2))
    | Abstract -> (FStar_Pprint.doc_of_string "Abstract")
    | IfDef -> (FStar_Pprint.doc_of_string "IfDef")
    | Macro -> (FStar_Pprint.doc_of_string "Macro")
    | (Deprecated (s)) -> (let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string s) in
      let tmp2 = (tmp1 :: []) in
      (ctor "Deprecated" tmp2))
    | CNoInline -> (FStar_Pprint.doc_of_string "CNoInline")
  )

let fStarC_Class_PP_pp__list_flag (tmp : (flag) list) : FStar_Pprint.document =
  (let tmp1 = (FStarC_Pprint.flow_map (FStar_Pprint.op_Hat_Hat FStar_Pprint.semi (FStar_Pprint.break_ (Prims.parse_int "1"))) fStarC_Class_PP_pp__flag tmp) in
  (FStarC_Class_PP.gbrackets tmp1))

let fStarC_Class_PP_pp__width (tmp : width) : FStar_Pprint.document =
  (match tmp with
    | UInt8 -> (FStar_Pprint.doc_of_string "UInt8")
    | UInt16 -> (FStar_Pprint.doc_of_string "UInt16")
    | UInt32 -> (FStar_Pprint.doc_of_string "UInt32")
    | UInt64 -> (FStar_Pprint.doc_of_string "UInt64")
    | Int8 -> (FStar_Pprint.doc_of_string "Int8")
    | Int16 -> (FStar_Pprint.doc_of_string "Int16")
    | Int32 -> (FStar_Pprint.doc_of_string "Int32")
    | Int64 -> (FStar_Pprint.doc_of_string "Int64")
    | Bool -> (FStar_Pprint.doc_of_string "Bool")
    | CInt -> (FStar_Pprint.doc_of_string "CInt")
    | SizeT -> (FStar_Pprint.doc_of_string "SizeT")
    | PtrdiffT -> (FStar_Pprint.doc_of_string "PtrdiffT")
    | Float32 -> (FStar_Pprint.doc_of_string "Float32")
    | Float64 -> (FStar_Pprint.doc_of_string "Float64")
  )

let pp_list' (f : ('a -> FStar_Pprint.document)) (xs : ('a) list) : FStar_Pprint.document =
  (let tmp = (FStarC_Pprint.flow_map (FStar_Pprint.op_Hat_Hat FStar_Pprint.semi (FStar_Pprint.break_ (Prims.parse_int "1"))) f xs) in
  let tmp1 = (FStar_Pprint.brackets tmp) in
  let tmp2 = (FStar_Pprint.nest (Prims.parse_int "2") tmp1) in
  (FStar_Pprint.group tmp2))

let rec typ_to_doc (t : typ) : FStar_Pprint.document =
  (match t with
    | (TInt (w)) -> (let tmp = (fStarC_Class_PP_pp__width w) in
      let tmp1 = (tmp :: []) in
      (ctor "TInt" tmp1))
    | (TBuf (t1)) -> (let tmp = (typ_to_doc t1) in
      let tmp1 = (tmp :: []) in
      (ctor "TBuf" tmp1))
    | TUnit -> (FStar_Pprint.doc_of_string "TUnit")
    | (TQualified (x)) -> (let tmp = (FStarC_Class_Show.fStarC_Class_Show_show__tuple2_list_string_string x) in
      let tmp1 = (FStar_Pprint.doc_of_string tmp) in
      let tmp2 = (tmp1 :: []) in
      (ctor "TQualified" tmp2))
    | TBool -> (FStar_Pprint.doc_of_string "TBool")
    | TAny -> (FStar_Pprint.doc_of_string "TAny")
    | (TArrow ((t1, t2))) -> (let tmp = (typ_to_doc t1) in
      let tmp1 = (typ_to_doc t2) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "TArrow" tmp3))
    | (TBound (x)) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__int x) in
      let tmp1 = (tmp :: []) in
      (ctor "TBound" tmp1))
    | (TApp ((x, xs))) -> (let tmp = (FStarC_Class_Show.fStarC_Class_Show_show__tuple2_list_string_string x) in
      let tmp1 = (FStar_Pprint.doc_of_string tmp) in
      let tmp2 = (pp_list' typ_to_doc xs) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      (ctor "TApp" tmp4))
    | (TTuple (ts)) -> (let tmp = (pp_list' typ_to_doc ts) in
      let tmp1 = (tmp :: []) in
      (ctor "TTuple" tmp1))
    | (TConstBuf (t1)) -> (let tmp = (typ_to_doc t1) in
      let tmp1 = (tmp :: []) in
      (ctor "TConstBuf" tmp1))
    | (TArray ((t1, c))) -> (let tmp = (typ_to_doc t1) in
      let tmp1 = (fStarC_Class_PP_pp__width (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst c)) in
      let tmp2 = (tmp1 :: ((FStar_Pprint.doc_of_string (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_snd c)) :: [])) in
      let tmp3 = (FStar_Pprint.separate FStar_Pprint.comma tmp2) in
      let tmp4 = (FStar_Pprint.parens tmp3) in
      let tmp5 = (tmp4 :: []) in
      let tmp6 = (tmp :: tmp5) in
      (ctor "TArray" tmp6))
  )

let fStarC_Class_PP_pp__typ (tmp : typ) : FStar_Pprint.document =
  (typ_to_doc tmp)

let fStarC_Class_PP_pp__tuple2_width_string (tmp : (width * string)) : FStar_Pprint.document =
  (match tmp with
    | (x1, x2) -> (let tmp1 = (fStarC_Class_PP_pp__width x1) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__string x2) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (FStar_Pprint.separate FStarC_Class_PP.comma_space tmp4) in
      (FStarC_Class_PP.gparens tmp5))
  )

let fStarC_Class_PP_pp__list_typ (tmp : (typ) list) : FStar_Pprint.document =
  (let tmp1 = (FStarC_Pprint.flow_map (FStar_Pprint.op_Hat_Hat FStar_Pprint.semi (FStar_Pprint.break_ (Prims.parse_int "1"))) fStarC_Class_PP_pp__typ tmp) in
  (FStarC_Class_PP.gbrackets tmp1))

let fld (n : string) (v : FStar_Pprint.document) : FStar_Pprint.document =
  (FStar_Pprint.group (FStar_Pprint.nest (Prims.parse_int "2") (FStar_Pprint.op_Hat_Slash_Hat (FStar_Pprint.doc_of_string (Prims.strcat n " =")) v)))

let spaced (a : FStar_Pprint.document) : FStar_Pprint.document =
  (FStar_Pprint.op_Hat_Hat (FStar_Pprint.break_ (Prims.parse_int "1")) (FStar_Pprint.op_Hat_Hat a (FStar_Pprint.break_ (Prims.parse_int "1"))))

let record (fs : (FStar_Pprint.document) list) : FStar_Pprint.document =
  (FStar_Pprint.group (FStar_Pprint.nest (Prims.parse_int "2") (FStar_Pprint.braces (spaced (FStar_Pprint.separate (FStar_Pprint.op_Hat_Hat FStar_Pprint.semi (FStar_Pprint.break_ (Prims.parse_int "1"))) fs)))))

let fStarC_Class_PP_pp__binder (tmp : binder) : FStar_Pprint.document =
  (let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string (tmp).name) in
  let tmp2 = (fld "name" tmp1) in
  let tmp3 = (fStarC_Class_PP_pp__typ (tmp).typ) in
  let tmp4 = (fld "typ" tmp3) in
  let tmp5 = (FStarC_Class_PP.fStarC_Class_PP_pp__bool (tmp).mut) in
  let tmp6 = (fld "mut" tmp5) in
  let tmp7 = (fStarC_Class_PP_pp__list_flag (tmp).meta) in
  let tmp8 = (fld "meta" tmp7) in
  let tmp9 = (tmp8 :: []) in
  let tmp10 = (tmp6 :: tmp9) in
  let tmp11 = (tmp4 :: tmp10) in
  let tmp12 = (tmp2 :: tmp11) in
  (record tmp12))

let fStarC_Class_PP_pp__lifetime (tmp : lifetime) : FStar_Pprint.document =
  (match tmp with
    | Eternal -> (FStar_Pprint.doc_of_string "Eternal")
    | Stack -> (FStar_Pprint.doc_of_string "Stack")
    | ManuallyManaged -> (FStar_Pprint.doc_of_string "ManuallyManaged")
  )

let rec pattern_to_doc (p : pattern) : FStar_Pprint.document =
  (match p with
    | PUnit -> (FStar_Pprint.doc_of_string "PUnit")
    | (PBool (b)) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__bool b) in
      let tmp1 = (tmp :: []) in
      (ctor "PBool" tmp1))
    | (PVar (b)) -> (let tmp = (fStarC_Class_PP_pp__binder b) in
      let tmp1 = (tmp :: []) in
      (ctor "PVar" tmp1))
    | (PCons ((x, ps))) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__string x) in
      let tmp1 = (pp_list' pattern_to_doc ps) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "PCons" tmp3))
    | (PTuple (ps)) -> (let tmp = (pp_list' pattern_to_doc ps) in
      let tmp1 = (tmp :: []) in
      (ctor "PTuple" tmp1))
    | (PRecord (fs)) -> (let tmp = (FStarC_List.map (fun tmp -> (match tmp with
          | (s, p1) -> (let tmp1 = (pattern_to_doc p1) in
            (fld s tmp1))
        )) fs) in
      let tmp1 = (record tmp) in
      let tmp2 = (tmp1 :: []) in
      (ctor "PRecord" tmp2))
    | (PConstant (c)) -> (let tmp = (fStarC_Class_PP_pp__tuple2_width_string c) in
      let tmp1 = (tmp :: []) in
      (ctor "PConstant" tmp1))
  )

let fStarC_Class_PP_pp__pattern (tmp : pattern) : FStar_Pprint.document =
  (pattern_to_doc tmp)

let fStarC_Class_PP_pp__op (tmp : op) : FStar_Pprint.document =
  (match tmp with
    | Add -> (FStar_Pprint.doc_of_string "Add")
    | AddW -> (FStar_Pprint.doc_of_string "AddW")
    | Sub -> (FStar_Pprint.doc_of_string "Sub")
    | SubW -> (FStar_Pprint.doc_of_string "SubW")
    | Div -> (FStar_Pprint.doc_of_string "Div")
    | DivW -> (FStar_Pprint.doc_of_string "DivW")
    | Mult -> (FStar_Pprint.doc_of_string "Mult")
    | MultW -> (FStar_Pprint.doc_of_string "MultW")
    | Mod -> (FStar_Pprint.doc_of_string "Mod")
    | BOr -> (FStar_Pprint.doc_of_string "BOr")
    | BAnd -> (FStar_Pprint.doc_of_string "BAnd")
    | BXor -> (FStar_Pprint.doc_of_string "BXor")
    | BShiftL -> (FStar_Pprint.doc_of_string "BShiftL")
    | BShiftR -> (FStar_Pprint.doc_of_string "BShiftR")
    | BNot -> (FStar_Pprint.doc_of_string "BNot")
    | Eq -> (FStar_Pprint.doc_of_string "Eq")
    | Neq -> (FStar_Pprint.doc_of_string "Neq")
    | Lt -> (FStar_Pprint.doc_of_string "Lt")
    | Lte -> (FStar_Pprint.doc_of_string "Lte")
    | Gt -> (FStar_Pprint.doc_of_string "Gt")
    | Gte -> (FStar_Pprint.doc_of_string "Gte")
    | And -> (FStar_Pprint.doc_of_string "And")
    | Or -> (FStar_Pprint.doc_of_string "Or")
    | Xor -> (FStar_Pprint.doc_of_string "Xor")
    | Not -> (FStar_Pprint.doc_of_string "Not")
  )

let rec pp_branch (b : (pattern * expr)) : FStar_Pprint.document =
  (match b with
    | (p, e) -> (let tmp = (fStarC_Class_PP_pp__pattern p) in
      let tmp1 = (expr_to_doc e) in
      let tmp2 = (FStar_Pprint.op_Hat_Slash_Hat FStar_Pprint.comma tmp1) in
      let tmp3 = (FStar_Pprint.op_Hat_Hat tmp tmp2) in
      (FStar_Pprint.parens tmp3))
  )

and expr_to_doc (e : expr) : FStar_Pprint.document =
  (match e with
    | (EBound (x)) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__int x) in
      let tmp1 = (tmp :: []) in
      (ctor "EBound" tmp1))
    | (EQualified (x)) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp1 = (tmp :: []) in
      (ctor "EQualified" tmp1))
    | (EConstant (x)) -> (let tmp = (fStarC_Class_PP_pp__tuple2_width_string x) in
      let tmp1 = (tmp :: []) in
      (ctor "EConstant" tmp1))
    | EUnit -> (FStar_Pprint.doc_of_string "EUnit")
    | (EApp ((x, xs))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (pp_list' expr_to_doc xs) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EApp" tmp3))
    | (ETypApp ((x, xs))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (fStarC_Class_PP_pp__list_typ xs) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "ETypApp" tmp3))
    | (ELet ((x, y, z))) -> (let tmp = (fStarC_Class_PP_pp__binder x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (expr_to_doc z) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (tmp :: tmp4) in
      (ctor "ELet" tmp5))
    | (EIfThenElse ((x, y, z))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (expr_to_doc z) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (tmp :: tmp4) in
      (ctor "EIfThenElse" tmp5))
    | (ESequence (xs)) -> (let tmp = (pp_list' expr_to_doc xs) in
      let tmp1 = (tmp :: []) in
      (ctor "ESequence" tmp1))
    | (EAssign ((x, y))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EAssign" tmp3))
    | (EBufCreate ((x, y, z))) -> (let tmp = (fStarC_Class_PP_pp__lifetime x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (expr_to_doc z) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (tmp :: tmp4) in
      (ctor "EBufCreate" tmp5))
    | (EBufRead ((x, y))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EBufRead" tmp3))
    | (EBufWrite ((x, y, z))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (expr_to_doc z) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (tmp :: tmp4) in
      (ctor "EBufWrite" tmp5))
    | (EBufSub ((x, y))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EBufSub" tmp3))
    | (EBufBlit ((x, y, z, a, b))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (expr_to_doc z) in
      let tmp3 = (expr_to_doc a) in
      let tmp4 = (expr_to_doc b) in
      let tmp5 = (tmp4 :: []) in
      let tmp6 = (tmp3 :: tmp5) in
      let tmp7 = (tmp2 :: tmp6) in
      let tmp8 = (tmp1 :: tmp7) in
      let tmp9 = (tmp :: tmp8) in
      (ctor "EBufBlit" tmp9))
    | (EMatch ((x, bs))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (pp_list' pp_branch bs) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EMatch" tmp3))
    | (EOp ((x, y))) -> (let tmp = (fStarC_Class_PP_pp__op x) in
      let tmp1 = (fStarC_Class_PP_pp__width y) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EOp" tmp3))
    | (ECast ((x, y))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (fStarC_Class_PP_pp__typ y) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "ECast" tmp3))
    | EPushFrame -> (FStar_Pprint.doc_of_string "EPushFrame")
    | EPopFrame -> (FStar_Pprint.doc_of_string "EPopFrame")
    | (EBool (x)) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__bool x) in
      let tmp1 = (tmp :: []) in
      (ctor "EBool" tmp1))
    | EAny -> (FStar_Pprint.doc_of_string "EAny")
    | EAbort -> (FStar_Pprint.doc_of_string "EAbort")
    | (EReturn (x)) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (tmp :: []) in
      (ctor "EReturn" tmp1))
    | (EFlat ((x, xs))) -> (let tmp = (fStarC_Class_PP_pp__typ x) in
      let tmp1 = (FStarC_List.map (fun tmp1 -> (match tmp1 with
          | (s, e1) -> (let tmp2 = (expr_to_doc e1) in
            (fld s tmp2))
        )) xs) in
      let tmp2 = (record tmp1) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp :: tmp3) in
      (ctor "EFlat" tmp4))
    | (EField ((x, y, z))) -> (let tmp = (fStarC_Class_PP_pp__typ x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__string z) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (tmp :: tmp4) in
      (ctor "EField" tmp5))
    | (EWhile ((x, y))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EWhile" tmp3))
    | (EBufCreateL ((x, xs))) -> (let tmp = (fStarC_Class_PP_pp__lifetime x) in
      let tmp1 = (pp_list' expr_to_doc xs) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EBufCreateL" tmp3))
    | (ETuple (xs)) -> (let tmp = (pp_list' expr_to_doc xs) in
      let tmp1 = (tmp :: []) in
      (ctor "ETuple" tmp1))
    | (ECons ((x, y, xs))) -> (let tmp = (fStarC_Class_PP_pp__typ x) in
      let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string y) in
      let tmp2 = (pp_list' expr_to_doc xs) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (tmp :: tmp4) in
      (ctor "ECons" tmp5))
    | (EBufFill ((x, y, z))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (expr_to_doc z) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (tmp :: tmp4) in
      (ctor "EBufFill" tmp5))
    | (EString (x)) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__string x) in
      let tmp1 = (tmp :: []) in
      (ctor "EString" tmp1))
    | (EFun ((xs, y, z))) -> (let tmp = (pp_list' fStarC_Class_PP_pp__binder xs) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (fStarC_Class_PP_pp__typ z) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (tmp :: tmp4) in
      (ctor "EFun" tmp5))
    | (EAbortS (x)) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__string x) in
      let tmp1 = (tmp :: []) in
      (ctor "EAbortS" tmp1))
    | (EBufFree (x)) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (tmp :: []) in
      (ctor "EBufFree" tmp1))
    | (EBufCreateNoInit ((x, y))) -> (let tmp = (fStarC_Class_PP_pp__lifetime x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EBufCreateNoInit" tmp3))
    | (EAbortT ((x, y))) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__string x) in
      let tmp1 = (fStarC_Class_PP_pp__typ y) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EAbortT" tmp3))
    | (EComment ((x, y, z))) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__string x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__string z) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (tmp :: tmp4) in
      (ctor "EComment" tmp5))
    | (EStandaloneComment (x)) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__string x) in
      let tmp1 = (tmp :: []) in
      (ctor "EStandaloneComment" tmp1))
    | (EAddrOf (x)) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (tmp :: []) in
      (ctor "EAddrOf" tmp1))
    | (EBufNull (x)) -> (let tmp = (fStarC_Class_PP_pp__typ x) in
      let tmp1 = (tmp :: []) in
      (ctor "EBufNull" tmp1))
    | (EBufDiff ((x, y))) -> (let tmp = (expr_to_doc x) in
      let tmp1 = (expr_to_doc y) in
      let tmp2 = (tmp1 :: []) in
      let tmp3 = (tmp :: tmp2) in
      (ctor "EBufDiff" tmp3))
    | (ESizeof (t)) -> (let tmp = (fStarC_Class_PP_pp__typ t) in
      let tmp1 = (tmp :: []) in
      (ctor "ESizeof" tmp1))
  )

let fStarC_Class_PP_pp__cc (tmp : cc) : FStar_Pprint.document =
  (match tmp with
    | StdCall -> (FStar_Pprint.doc_of_string "StdCall")
    | CDecl -> (FStar_Pprint.doc_of_string "CDecl")
    | FastCall -> (FStar_Pprint.doc_of_string "FastCall")
  )

let fStarC_Class_PP_pp__option_cc (tmp : (cc) option) : FStar_Pprint.document =
  (match tmp with
    | (Some (v)) -> (let tmp1 = (fStarC_Class_PP_pp__cc v) in
      let tmp2 = (FStar_Pprint.op_Hat_Slash_Hat (FStar_Pprint.doc_of_string "Some") tmp1) in
      let tmp3 = (FStar_Pprint.nest (Prims.parse_int "2") tmp2) in
      (FStar_Pprint.group tmp3))
    | None -> (FStar_Pprint.doc_of_string "None")
  )

let fStarC_Class_PP_pp__list_binder (tmp : (binder) list) : FStar_Pprint.document =
  (let tmp1 = (FStarC_Pprint.flow_map (FStar_Pprint.op_Hat_Hat FStar_Pprint.semi (FStar_Pprint.break_ (Prims.parse_int "1"))) fStarC_Class_PP_pp__binder tmp) in
  (FStarC_Class_PP.gbrackets tmp1))

let fStarC_Class_PP_pp__tuple2_typ_bool (tmp : (typ * bool)) : FStar_Pprint.document =
  (match tmp with
    | (x1, x2) -> (let tmp1 = (fStarC_Class_PP_pp__typ x1) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__bool x2) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (FStar_Pprint.separate FStarC_Class_PP.comma_space tmp4) in
      (FStarC_Class_PP.gparens tmp5))
  )

let fStarC_Class_PP_pp__tuple2_string_tuple2_typ_bool (tmp : (string * (typ * bool))) : FStar_Pprint.document =
  (match tmp with
    | (x1, x2) -> (let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string x1) in
      let tmp2 = (fStarC_Class_PP_pp__tuple2_typ_bool x2) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (FStar_Pprint.separate FStarC_Class_PP.comma_space tmp4) in
      (FStarC_Class_PP.gparens tmp5))
  )

let fStarC_Class_PP_pp__list_tuple2_string_tuple2 (tmp : ((string * (typ * bool))) list) : FStar_Pprint.document =
  (let tmp1 = (FStarC_Pprint.flow_map (FStar_Pprint.op_Hat_Hat FStar_Pprint.semi (FStar_Pprint.break_ (Prims.parse_int "1"))) fStarC_Class_PP_pp__tuple2_string_tuple2_typ_bool tmp) in
  (FStarC_Class_PP.gbrackets tmp1))

let fStarC_Class_PP_pp__tuple2_string_list_tuple2 (tmp : (string * ((string * (typ * bool))) list)) : FStar_Pprint.document =
  (match tmp with
    | (x1, x2) -> (let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string x1) in
      let tmp2 = (fStarC_Class_PP_pp__list_tuple2_string_tuple2 x2) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (FStar_Pprint.separate FStarC_Class_PP.comma_space tmp4) in
      (FStarC_Class_PP.gparens tmp5))
  )

let fStarC_Class_PP_pp__list_tuple2_string_list (tmp : ((string * ((string * (typ * bool))) list)) list) : FStar_Pprint.document =
  (let tmp1 = (FStarC_Pprint.flow_map (FStar_Pprint.op_Hat_Hat FStar_Pprint.semi (FStar_Pprint.break_ (Prims.parse_int "1"))) fStarC_Class_PP_pp__tuple2_string_list_tuple2 tmp) in
  (FStarC_Class_PP.gbrackets tmp1))

let fStarC_Class_PP_pp__tuple2_string_typ (tmp : (string * typ)) : FStar_Pprint.document =
  (match tmp with
    | (x1, x2) -> (let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__string x1) in
      let tmp2 = (fStarC_Class_PP_pp__typ x2) in
      let tmp3 = (tmp2 :: []) in
      let tmp4 = (tmp1 :: tmp3) in
      let tmp5 = (FStar_Pprint.separate FStarC_Class_PP.comma_space tmp4) in
      (FStarC_Class_PP.gparens tmp5))
  )

let fStarC_Class_PP_pp__list_tuple2_string_typ (tmp : ((string * typ)) list) : FStar_Pprint.document =
  (let tmp1 = (FStarC_Pprint.flow_map (FStar_Pprint.op_Hat_Hat FStar_Pprint.semi (FStar_Pprint.break_ (Prims.parse_int "1"))) fStarC_Class_PP_pp__tuple2_string_typ tmp) in
  (FStarC_Class_PP.gbrackets tmp1))

let decl_to_doc (d : decl) : FStar_Pprint.document =
  (match d with
    | (DGlobal ((fs, x, i, t, e))) -> (let tmp = (fStarC_Class_PP_pp__list_flag fs) in
      let tmp1 = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__int i) in
      let tmp3 = (fStarC_Class_PP_pp__typ t) in
      let tmp4 = (expr_to_doc e) in
      let tmp5 = (tmp4 :: []) in
      let tmp6 = (tmp3 :: tmp5) in
      let tmp7 = (tmp2 :: tmp6) in
      let tmp8 = (tmp1 :: tmp7) in
      let tmp9 = (tmp :: tmp8) in
      (ctor "DGlobal" tmp9))
    | (DFunction ((cc, fs, i, t, x, bs, e))) -> (let tmp = (fStarC_Class_PP_pp__option_cc cc) in
      let tmp1 = (fStarC_Class_PP_pp__list_flag fs) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__int i) in
      let tmp3 = (fStarC_Class_PP_pp__typ t) in
      let tmp4 = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp5 = (fStarC_Class_PP_pp__list_binder bs) in
      let tmp6 = (expr_to_doc e) in
      let tmp7 = (tmp6 :: []) in
      let tmp8 = (tmp5 :: tmp7) in
      let tmp9 = (tmp4 :: tmp8) in
      let tmp10 = (tmp3 :: tmp9) in
      let tmp11 = (tmp2 :: tmp10) in
      let tmp12 = (tmp1 :: tmp11) in
      let tmp13 = (tmp :: tmp12) in
      (ctor "DFunction" tmp13))
    | (DTypeAlias ((x, fs, i, t))) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp1 = (fStarC_Class_PP_pp__list_flag fs) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__int i) in
      let tmp3 = (fStarC_Class_PP_pp__typ t) in
      let tmp4 = (tmp3 :: []) in
      let tmp5 = (tmp2 :: tmp4) in
      let tmp6 = (tmp1 :: tmp5) in
      let tmp7 = (tmp :: tmp6) in
      (ctor "DTypeAlias" tmp7))
    | (DTypeFlat ((x, fs, i, f))) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp1 = (fStarC_Class_PP_pp__list_flag fs) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__int i) in
      let tmp3 = (fStarC_Class_PP_pp__list_tuple2_string_tuple2 f) in
      let tmp4 = (tmp3 :: []) in
      let tmp5 = (tmp2 :: tmp4) in
      let tmp6 = (tmp1 :: tmp5) in
      let tmp7 = (tmp :: tmp6) in
      (ctor "DTypeFlat" tmp7))
    | (DUnusedRetainedForBackwardsCompat ((cc, fs, x, t))) -> (let tmp = (fStarC_Class_PP_pp__option_cc cc) in
      let tmp1 = (fStarC_Class_PP_pp__list_flag fs) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp3 = (fStarC_Class_PP_pp__typ t) in
      let tmp4 = (tmp3 :: []) in
      let tmp5 = (tmp2 :: tmp4) in
      let tmp6 = (tmp1 :: tmp5) in
      let tmp7 = (tmp :: tmp6) in
      (ctor "DUnusedRetainedForBackwardsCompat" tmp7))
    | (DTypeVariant ((x, fs, i, bs))) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp1 = (fStarC_Class_PP_pp__list_flag fs) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__int i) in
      let tmp3 = (fStarC_Class_PP_pp__list_tuple2_string_list bs) in
      let tmp4 = (tmp3 :: []) in
      let tmp5 = (tmp2 :: tmp4) in
      let tmp6 = (tmp1 :: tmp5) in
      let tmp7 = (tmp :: tmp6) in
      (ctor "DTypeVariant" tmp7))
    | (DTypeAbstractStruct (x)) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp1 = (tmp :: []) in
      (ctor "DTypeAbstractStruct" tmp1))
    | (DExternal ((cc, fs, x, t, xs))) -> (let tmp = (fStarC_Class_PP_pp__option_cc cc) in
      let tmp1 = (fStarC_Class_PP_pp__list_flag fs) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp3 = (fStarC_Class_PP_pp__typ t) in
      let tmp4 = (FStarC_Class_PP.fStarC_Class_PP_pp__list_string xs) in
      let tmp5 = (tmp4 :: []) in
      let tmp6 = (tmp3 :: tmp5) in
      let tmp7 = (tmp2 :: tmp6) in
      let tmp8 = (tmp1 :: tmp7) in
      let tmp9 = (tmp :: tmp8) in
      (ctor "DExternal" tmp9))
    | (DUntaggedUnion ((x, fs, i, xs))) -> (let tmp = (FStarC_Class_PP.fStarC_Class_PP_pp__tuple2_list_string_string x) in
      let tmp1 = (fStarC_Class_PP_pp__list_flag fs) in
      let tmp2 = (FStarC_Class_PP.fStarC_Class_PP_pp__int i) in
      let tmp3 = (fStarC_Class_PP_pp__list_tuple2_string_typ xs) in
      let tmp4 = (tmp3 :: []) in
      let tmp5 = (tmp2 :: tmp4) in
      let tmp6 = (tmp1 :: tmp5) in
      let tmp7 = (tmp :: tmp6) in
      (ctor "DUntaggedUnion" tmp7))
  )

let fStarC_Class_PP_pp__decl (tmp : decl) : FStar_Pprint.document =
  (decl_to_doc tmp)

let fStarC_Class_Show_show__decl_157 (tmp : decl) : string =
  (let tmp1 = (fStarC_Class_PP_pp__decl tmp) in
  (FStar_Pprint.render tmp1))

