(* Generated by F* Custard extraction. Do not edit. *)
[@@@ocaml.warning "-3-5-8-11-20-26-27-28-32-33-34-35-37-39-50-57-60-69-70"]

let rec print_discrepancy__blist_leq (l1 : (bool) list) (l2 : (bool) list) : bool =
  (match (l1, l2) with
    | ((h1 :: t1), (h2 :: t2)) -> (if ((not h1) || h2) then (print_discrepancy__blist_leq t1 t2) else false)
    | ([], []) -> true
    | tmp -> (FStarC_Effect.failwith "print_discrepancy: bad lists")
  )

let rec print_discrepancy__succ (l : (bool) list) : (bool) list =
  (match l with
    | (false :: t) -> (true :: t)
    | (true :: t) -> (let tmp = (print_discrepancy__succ t) in
      (false :: tmp))
    | [] -> (FStarC_Effect.failwith "")
  )

let rec print_discrepancy__go (print : (unit -> ('b * 'b * bool))) (full : ((bool) list -> bool)) (set : ((bool) list -> unit)) (bas : (bool) list) (cur : (bool) list) : ('b * 'b) =
  (let tmp = (full cur) in
  (if tmp then (let tmp1 = (print ()) in
  (match tmp1 with
    | (xs, ys, tmp2) -> (xs, ys)
  )) else (let tmp1 = (print_discrepancy__blist_leq bas cur) in
  let tmp2 = (not tmp1) in
  (if tmp2 then (let tmp3 = (print_discrepancy__succ cur) in
  ((print_discrepancy__go print full set bas) tmp3)) else ((set cur);
  let tmp3 = (print ()) in
  (match tmp3 with
    | (xs, ys, true) -> (xs, ys)
    | tmp4 -> (let tmp5 = (print_discrepancy__succ cur) in
      ((print_discrepancy__go print full set bas) tmp5))
  ))))))

let print_discrepancy (f : ('a -> 'b)) (x : 'a) (y : 'a) : ('b * 'b) =
  (let print = (fun tmp -> (let xs = (f x) in
    let ys = (f y) in
    (xs, ys, ((<>) xs ys)))) in
  let full = (fun l -> (FStarC_List.for_all (fun b -> b) l)) in
  let get_bool_option = (fun s -> (let tmp = (FStarC_Options.get_option s) in
    (match tmp with
      | (FStarC_Options.Bool (b)) -> b
      | tmp1 -> (FStarC_Effect.failwith "print_discrepancy: impossible")
    ))) in
  let set_bool_option = (fun s b -> (FStarC_Options.set_option s (FStarC_Options.Bool (b)))) in
  let get = (fun tmp -> (let pi = (get_bool_option "print_implicits") in
    let pu = (get_bool_option "print_universes") in
    let pea = (get_bool_option "print_effect_args") in
    let pf = (get_bool_option "print_full_names") in
    (pi :: (pu :: (pea :: (pf :: [])))))) in
  let set = (fun l -> (match l with
      | (pi :: (pu :: (pea :: (pf :: [])))) -> ((set_bool_option "print_implicits" pi);
        (set_bool_option "print_universes" pu);
        (set_bool_option "print_effect_args" pea);
        (set_bool_option "print_full_names " pf))
      | tmp -> (FStarC_Effect.failwith "impossible: print_discrepancy")
    )) in
  let bas = (get ()) in
  (FStarC_Options.with_saved_options (fun tmp -> ((print_discrepancy__go print full set bas) bas))))

let expected_expression_of_type (env : FStarC_TypeChecker_Env.env) (rng : FStarC_Range_Type.range) (t1 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (e : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (t2 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : 'a =
  (let d1 = (FStarC_TypeChecker_Normalize.term_to_doc env t1) in
  let d2 = (FStarC_TypeChecker_Normalize.term_to_doc env t2) in
  let ed = (FStarC_TypeChecker_Normalize.term_to_doc env e) in
  (FStarC_Errors.fStarC_Errors_raise_error__range_list_document rng FStarC_Errors_Codes.Fatal_UnexpectedExpressionType ((FStar_Pprint.op_Hat_Slash_Hat (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Expected expression of type") d1) (FStar_Pprint.op_Hat_Slash_Hat (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "got expression") ed) (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "of type") d2))) :: [])))

let subtyping_failed (tmp : FStarC_TypeChecker_Env.env) (tmp1 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (tmp2 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (tmp3 : unit) : (FStar_Pprint.document) list =
  (let ppt = (FStarC_TypeChecker_Normalize.term_to_doc tmp) in
  let tmp4 = (ppt tmp2) in
  let tmp5 = (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Expected type") tmp4) in
  let tmp6 = (ppt tmp1) in
  let tmp7 = (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "got type") tmp6) in
  let tmp8 = (FStar_Pprint.op_Hat_Slash_Hat tmp5 tmp7) in
  let tmp9 = (tmp8 :: []) in
  ((FStarC_Errors_Msg.text "Subtyping check failed") :: tmp9))

let name_and_result (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : (string * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) =
  (match (c).FStarC_Syntax_Syntax.n with
    | ct when (FStarC_Parser_Const.is_tot_lid (ct).FStarC_Syntax_Syntax.effect_name) -> ("Tot", (ct).FStarC_Syntax_Syntax.result_typ)
    | ct when (FStarC_Parser_Const.is_gtot_lid (ct).FStarC_Syntax_Syntax.effect_name) -> ("GTot", (ct).FStarC_Syntax_Syntax.result_typ)
    | ct -> (let tmp = (FStarC_Ident.fStarC_Class_Show_show__lident (ct).FStarC_Syntax_Syntax.effect_name) in
      (tmp, (ct).FStarC_Syntax_Syntax.result_typ))
  )

let u___expected_eff_expression (effname : string) (rng : FStarC_Range_Type.range) (e : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) (reason : (string) option) : 'a =
  (let tmp = (FStarC_Syntax_Print.fStarC_Class_PP_pp__syntax_term' e) in
  let tmp1 = (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Got an expression") tmp) in
  let tmp2 = (name_and_result c) in
  let tmp3 = (Custard_FStar_Pervasives_Native.fStar_Pervasives_Native_fst tmp2) in
  let tmp4 = (FStar_Pprint.doc_of_string tmp3) in
  let tmp5 = (FStarC_Errors_Msg.fquotes tmp4) in
  let tmp6 = (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "with effect") tmp5) in
  let tmp7 = (FStar_Pprint.op_Hat_Hat tmp6 FStar_Pprint.dot) in
  let tmp8 = (FStar_Pprint.op_Hat_Slash_Hat tmp1 tmp7) in
  let tmp9 = (tmp8 :: []) in
  let tmp10 = ((match reason with
      | None -> FStar_Pprint.empty
      | (Some (msg)) -> (FStar_Pprint.flow (FStar_Pprint.break_ (Prims.parse_int "1")) ((FStar_Pprint.doc_of_string "Because:") :: (FStar_Pprint.words (Prims.strcat msg "."))))
    ) :: tmp9) in
  let tmp11 = ((FStarC_Errors_Msg.text (Prims.strcat "Expected a " (Prims.strcat effname " expression."))) :: tmp10) in
  (FStarC_Errors.fStarC_Errors_raise_error__range_list_document rng FStarC_Errors_Codes.Fatal_ExpectedGhostExpression tmp11))

let expected_ghost_expression (rng : FStarC_Range_Type.range) (e : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) (reason : (string) option) : 'a =
  (u___expected_eff_expression "ghost" rng e c reason)

let expected_pure_expression (rng : FStarC_Range_Type.range) (e : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) (reason : (string) option) : 'a =
  (u___expected_eff_expression "pure" rng e c reason)

let err_msg_type_strings (env : FStarC_TypeChecker_Env.env) (x : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (y : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : (string * string) =
  (print_discrepancy (FStarC_TypeChecker_Normalize.term_to_string env) x y)

let basic_type_error (env : FStarC_TypeChecker_Env.env) (rng : FStarC_Range_Type.range) (eopt : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option) (t1 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (t2 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : unit =
  (let tmp = (err_msg_type_strings env t1 t2) in
  (match tmp with
    | (s1, s2) -> (let msg = (match eopt with
          | None -> (let tmp1 = (FStarC_TypeChecker_Normalize.term_to_doc env t1) in
            let tmp2 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Expected type") tmp1) in
            let tmp3 = (FStarC_TypeChecker_Normalize.term_to_doc env t2) in
            let tmp4 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "got type") tmp3) in
            let tmp5 = (FStar_Pprint.op_Hat_Slash_Hat tmp2 tmp4) in
            (tmp5 :: []))
          | (Some (e)) -> (let tmp1 = (FStarC_TypeChecker_Normalize.term_to_doc env t1) in
            let tmp2 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Expected type") tmp1) in
            let tmp3 = (FStarC_TypeChecker_Normalize.term_to_doc env e) in
            let tmp4 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "but") tmp3) in
            let tmp5 = (FStarC_TypeChecker_Normalize.term_to_doc env t2) in
            let tmp6 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "has type") tmp5) in
            let tmp7 = (FStar_Pprint.op_Hat_Slash_Hat tmp4 tmp6) in
            let tmp8 = (FStar_Pprint.op_Hat_Slash_Hat tmp2 tmp7) in
            (tmp8 :: []))
        ) in
      (FStarC_Errors.fStarC_Errors_log_issue__range_list_document rng FStarC_Errors_Codes.Error_TypeError msg))
  ))

let raise_basic_type_error (env : FStarC_TypeChecker_Env.env) (rng : FStarC_Range_Type.range) (eopt : ((FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) option) (t1 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (t2 : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : 'a =
  (let tmp = (err_msg_type_strings env t1 t2) in
  (match tmp with
    | (s1, s2) -> (let msg = (match eopt with
          | None -> (let tmp1 = (FStarC_TypeChecker_Normalize.term_to_doc env t1) in
            let tmp2 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Expected type") tmp1) in
            let tmp3 = (FStarC_TypeChecker_Normalize.term_to_doc env t2) in
            let tmp4 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "got type") tmp3) in
            let tmp5 = (FStar_Pprint.op_Hat_Slash_Hat tmp2 tmp4) in
            (tmp5 :: []))
          | (Some (e)) -> (let tmp1 = (FStarC_TypeChecker_Normalize.term_to_doc env t1) in
            let tmp2 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Expected type") tmp1) in
            let tmp3 = (FStarC_TypeChecker_Normalize.term_to_doc env e) in
            let tmp4 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "but") tmp3) in
            let tmp5 = (FStarC_TypeChecker_Normalize.term_to_doc env t2) in
            let tmp6 = (FStar_Pprint.prefix (Prims.parse_int "4") (Prims.parse_int "1") (FStarC_Errors_Msg.text "has type") tmp5) in
            let tmp7 = (FStar_Pprint.op_Hat_Slash_Hat tmp4 tmp6) in
            let tmp8 = (FStar_Pprint.op_Hat_Slash_Hat tmp2 tmp7) in
            (tmp8 :: []))
        ) in
      (FStarC_Errors.fStarC_Errors_raise_error__range_list_document rng FStarC_Errors_Codes.Error_TypeError msg))
  ))

let computed_computation_type_does_not_match_annotation_eq (env : FStarC_TypeChecker_Env.env) (r : FStarC_Range_Type.range) (e : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) (c' : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : 'a =
  (let ppc = (FStarC_TypeChecker_Normalize.comp_to_doc env) in
  let tmp = (ppc c) in
  let tmp1 = (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Computed type") tmp) in
  let tmp2 = (ppc c') in
  let tmp3 = (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "does not match annotated type") tmp2) in
  let tmp4 = (FStar_Pprint.op_Hat_Slash_Hat tmp3 (FStarC_Errors_Msg.text "and no subtyping was allowed")) in
  let tmp5 = (FStar_Pprint.op_Hat_Slash_Hat tmp1 tmp4) in
  let tmp6 = (tmp5 :: []) in
  (FStarC_Errors.fStarC_Errors_raise_error__range_list_document r FStarC_Errors_Codes.Fatal_ComputedTypeNotMatchAnnotation tmp6))

let computed_computation_type_does_not_match_annotation (env : FStarC_TypeChecker_Env.env) (r : FStarC_Range_Type.range) (e : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) (c : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) (c' : (FStarC_Syntax_Syntax.comp_typ) FStarC_Syntax_Syntax.syntax) : 'a =
  (let ppt = (FStarC_TypeChecker_Normalize.term_to_doc env) in
  let tmp = (name_and_result c) in
  (match tmp with
    | (f1, r1) -> (let tmp1 = (name_and_result c') in
      (match tmp1 with
        | (f2, r2) -> (let tmp2 = (ppt r1) in
          let tmp3 = (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Computed type") tmp2) in
          let tmp4 = (ppt r2) in
          let tmp5 = (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "is not compatible with the annotated type") tmp4) in
          let tmp6 = (FStar_Pprint.op_Hat_Slash_Hat tmp5 (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "and effect") (FStarC_Errors_Msg.text f2))) in
          let tmp7 = (FStar_Pprint.op_Hat_Slash_Hat (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "and effect") (FStarC_Errors_Msg.text f1)) tmp6) in
          let tmp8 = (FStar_Pprint.op_Hat_Slash_Hat tmp3 tmp7) in
          let tmp9 = (tmp8 :: []) in
          (FStarC_Errors.fStarC_Errors_raise_error__range_list_document r FStarC_Errors_Codes.Fatal_ComputedTypeNotMatchAnnotation tmp9))
      ))
  ))

let ill_kinded_type : (FStar_Pprint.document) list =
  (FStarC_Errors_Msg.mkmsg "Ill-kinded type")

let expected_function_typ (env : FStarC_TypeChecker_Env.env) (rng : FStarC_Range_Type.range) (t : (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax) : 'a =
  (let tmp = (FStarC_TypeChecker_Normalize.term_to_doc env t) in
  let tmp1 = (FStar_Pprint.prefix (Prims.parse_int "2") (Prims.parse_int "1") (FStarC_Errors_Msg.text "Got an expression of type:") tmp) in
  let tmp2 = (tmp1 :: []) in
  let tmp3 = ((FStarC_Errors_Msg.text "Expected a function.") :: tmp2) in
  (FStarC_Errors.fStarC_Errors_raise_error__range_list_document rng FStarC_Errors_Codes.Fatal_FunctionTypeExpected tmp3))

let exhaustiveness_check : (FStar_Pprint.document) list =
  ((FStarC_Errors_Msg.text "Patterns are incomplete") :: [])

let warn_top_level_effect (rng : FStarC_Range_Type.range) : unit =
  (FStarC_Errors.fStarC_Errors_log_issue__range_string rng FStarC_Errors_Codes.Warning_TopLevelEffect "Top-level let-bindings must be total; this term may have effects")

let errors_smt_detail (env : FStarC_TypeChecker_Env.env) (errs : ((FStarC_Errors_Codes.error_code * (FStar_Pprint.document) list * FStarC_Range_Type.range * (string) list)) list) (smt_detail : (FStar_Pprint.document) list) : ((FStarC_Errors_Codes.error_code * (FStar_Pprint.document) list * FStarC_Range_Type.range * (string) list)) list =
  (FStarC_List.map (fun tmp -> (match tmp with
    | (e, msg, r, ctx) -> (let msg1 = (FStar_List_Tot_Base.op_At msg smt_detail) in
      (if ((=) r FStarC_Range_Type.dummyRange) then (e, msg1, (FStarC_TypeChecker_Env.get_range env), ctx) else (let r' = (FStarC_Range_Type.set_def_range r (FStarC_Range_Type.use_range r)) in
      (if ((<>) (FStarC_Range_Ops.file_of_range r') (FStarC_Range_Ops.file_of_range (FStarC_TypeChecker_Env.get_range env))) then (let tmp1 = (FStarC_Range_Ops.string_of_use_range r) in
      let tmp2 = (Prims.strcat "Also see: " tmp1) in
      let tmp3 = (FStar_Pprint.doc_of_string tmp2) in
      let tmp4 = (if ((<>) (FStarC_Range_Type.use_range r) (FStarC_Range_Type.def_range r)) then (let tmp4 = (FStarC_Range_Ops.string_of_def_range r) in
        let tmp5 = (Prims.strcat "Other related locations: " tmp4) in
        (FStar_Pprint.doc_of_string tmp5)) else FStar_Pprint.empty) in
      let tmp5 = (tmp4 :: []) in
      let tmp6 = (tmp3 :: tmp5) in
      let msg2 = (FStar_List_Tot_Base.op_At msg1 tmp6) in
      (e, msg2, (FStarC_TypeChecker_Env.get_range env), ctx)) else (e, msg1, r, ctx)))))
  )) errs)

let add_errors (env : FStarC_TypeChecker_Env.env) (errs : ((FStarC_Errors_Codes.error_code * (FStar_Pprint.document) list * FStarC_Range_Type.range * (string) list)) list) : unit =
  (let tmp = (errors_smt_detail env errs []) in
  (FStarC_Errors.add_errors tmp))

let log_issue (env : FStarC_TypeChecker_Env.env) (r : FStarC_Range_Type.range) (ce : (FStarC_Errors_Codes.error_code * (FStar_Pprint.document) list)) : unit =
  (match ce with
    | (e, m) -> (let tmp = (FStarC_Errors.get_ctx ()) in
      let tmp1 = (e, m, r, tmp) in
      let tmp2 = (tmp1 :: []) in
      (add_errors env tmp2))
  )

let info_at_pos (env : FStarC_TypeChecker_Env.env) (file : string) (row : Prims.int) (col : Prims.int) : (((string, FStarC_Ident.lident) FStar_Pervasives.either * (FStarC_Syntax_Syntax.term') FStarC_Syntax_Syntax.syntax * FStarC_Range_Type.range)) option =
  (let tmp = (!((env).FStarC_TypeChecker_Env.identifier_info)) in
  let tmp1 = (FStarC_TypeChecker_Common.id_info_at_pos tmp file row col) in
  (match tmp1 with
    | None -> None
    | (Some (info)) -> (match (info).FStarC_TypeChecker_Common.identifier with
        | (FStar_Pervasives.Inl (bv)) -> (let tmp2 = (FStarC_Ident.fStarC_Class_Show_show__ident (bv).FStarC_Syntax_Syntax.ppname) in
          let tmp3 = (FStar_Pervasives.Inl (tmp2)) in
          let tmp4 = (tmp3, (info).FStarC_TypeChecker_Common.identifier_ty, (FStarC_Syntax_Syntax.range_of_bv bv)) in
          (Some (tmp4)))
        | (FStar_Pervasives.Inr (fv)) -> (Some (((FStar_Pervasives.Inr ((FStarC_Syntax_Syntax.lid_of_fv fv))), (info).FStarC_TypeChecker_Common.identifier_ty, (FStarC_Syntax_Syntax.range_of_fv fv))))
      )
  ))

