all: verify

# assuming share/steel/examples/pulse/parix
PULSE_HOME ?= ../../../../..

FSTAR_OPTIONS = --include $(PULSE_HOME)/lib/steel/pulse

COMPAT_INDEXED_EFFECTS=

include $(PULSE_HOME)/share/steel/Makefile.include
