STEEL_HOME=../../../../../..
FSTAR_FILES := $(wildcard *.fst *.fsti)
INCLUDE_PATHS := $(STEEL_HOME)/share/steel/examples/pulse/lib
include ../../Makefile.pulse.common

%.fst-in,%.fsti-in:
	@echo $(FSTAR_OPTIONS)
