ALLFILES=CPS.Double.fst       CPS.DoubleLambdaLifting.fst   CPS.Simple.fst\
	 CPS.DoubleCC.fst     CPS.DoubleLambdaLifting2.fst  CPS.SimpleDefun.fst\
	 CPS.DoubleDefun.fst  CPS.Expr.fst                  CPS.SimpleLambdaLifting.fst\
	 Eval.DB.fst	      Eval.DBCC.fst	            wf.fst\
	 termination.fst
include ../Makefile.include
all:$(ALLFILES)
	$(FSTAR) $^
