ALLFILES=wf CPS.Simple CPS.Double CPS.DoubleLambdaLifting2 CPS.DoubleDefun CPS.Expr \
	 CPS.SimpleDefun CPS.SimpleLambdaLifting Eval.DB termination

FSTAR_HOME=../..
include ../Makefile.include

all: $(addsuffix .uver, $(ALLFILES))
