all: verify

# assuming share/steel/examples/pulse/lib
STEEL_HOME ?= ../../../../..

FSTAR_OPTIONS = --include $(STEEL_HOME)/lib/steel/pulse

COMPAT_INDEXED_EFFECTS=

include $(STEEL_HOME)/share/steel/Makefile.include