name: Build F* (macos)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ inputs.ref || '' }}
          submodules: true

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0

      - name: Prepare
        run: |
          brew install opam bash gnu-getopt coreutils gnu-sed make
          ./.scripts/get_fstar_z3.sh $HOME/bin
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
          opam install --deps-only ./fstar.opam

      - name: Set version
        run: |
          # Setting FSTAR_VERSION for nightly and release builds. If unset,
          # we use $(version.txt)~dev. Setting it avoids the ~dev.
          if [[ "${{github.workflow_ref}}" =~ "nightly-build.yml" ]]; then
            REF="${{ inputs.ref }}"
            if [[ -n "$REF" && "$REF" != "master" ]]; then
              echo FSTAR_VERSION="nightly-${REF}-$(date -I)" >> $GITHUB_ENV
            else
              echo FSTAR_VERSION="nightly-$(date -I)" >> $GITHUB_ENV
            fi
          elif [[ "${{github.workflow_ref}}" =~ "release.yml" ]]; then
            echo FSTAR_VERSION="$(cat version.txt)" >> $GITHUB_ENV
            echo FSTAR_RELEASE=1 >> $GITHUB_ENV
          fi

      # Note *g*make below!
      # NB: release workflow later adds version number to the name
      - name: Build package
        run: |
          eval $(opam env)
          KERNEL=$(uname -s)
          ARCH=$(uname -m)
          export FSTAR_TAG=-$KERNEL-$ARCH
          gmake -skj$(nproc) package

      - uses: actions/upload-artifact@v7
        with:
          path: fstar-*
          name: package-mac

  smoke_test:
    needs: build
    strategy:
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cda-tum/setup-z3@main
        with:
          version: 4.13.3

      - name: Get fstar package
        uses: actions/download-artifact@v8
        with:
          name: package-mac

      - run: tar xzf fstar*.tar.gz

      - name: Smoke test
        run: |
          ./fstar/bin/fstar.exe --admit_smt_queries true fstar/lib/fstar/ulib/Prims.fst -f
          echo -e "module A\let _ = assert (forall x. 1 + x*x > 0)" > A.fst
          ./fstar/bin/fstar.exe --admit_smt_queries true A.fst
          echo -e "module B\n#lang-pulse\nopen Pulse\nfn test (x:int) returns int { (x+1); }" > B.fst
          ./fstar/bin/fstar.exe --admit_smt_queries true B.fst
