name: Build F* binaries (all archs)

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''
  workflow_dispatch:

jobs:
  # Windows build call this as a substep
  # src:
  #   uses: ./.github/workflows/build-src.yml

  linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      ref: ${{ inputs.ref || '' }}

  macos:
    uses: ./.github/workflows/build-macos.yml
    with:
      ref: ${{ inputs.ref || '' }}

  windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      ref: ${{ inputs.ref || '' }}
