name: Check world (test F* + all subprojects)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # 1AM UTC

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    uses: ./.github/workflows/build-ci.yml

  check-friends:
    needs: build
    name: friends
    uses: ./.github/workflows/check-friends.yml

  build-nix:
    name: build (nix)
    uses: ./.github/workflows/nix.yml

  check-nix-friends:
    needs: build-nix
    name: friends-nix
    uses: ./.github/workflows/check-nix-friends.yml
