name: Check for stale hints
on:
  workflow_dispatch:
  workflow_call:
jobs:
  check_stale_hints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: .scripts/check_stale_hints.sh
