#!/usr/bin/env bash

if [[ $# != 1 ]]; then
  echo "Usage: $0 FILENAME OUTPUT_DIR where FILENAME.fs exists and FILENAME.fsi may exist";
  echo "Returns 0 if move should happen; returns 1 if move should not happen; returns > 1 in case of error";
  exit 1
fi;

THE_FS=${1}.fs
THE_FST=${1}.fst
THE_FSI=${1}.fsi
if [ ! -f "$THE_FS" ]; then
  echo "$THE_FS does not exist"
  exit 2
fi;

if [ -f "$THE_FSI" ]; then
  HAS_FSI=true
else
  HAS_FSI=false
fi;

echo -n "Found an .fs"
if $HAS_FSI; then
  echo "; also found an .fsi"
else
  echo "; found no .fsi, doing a .fs → .fst copy";
  cp $THE_FS $THE_FST;
  exit 0
fi;

MARKER_LINE=$(grep -En "^\/\/ ?VALS_HACK_HERE" $THE_FS | cut -f1 -d:)
if [[ $MARKER_LINE != "" ]]; then
  echo "Found marker for $THE_FS at line $MARKER_LINE"
else
  echo "Didn't find a marker; exiting"
  exit 1
fi

BEFORE_MARKER=$(($MARKER_LINE - 1))
AFTER_MARKER=$(($MARKER_LINE + 1))
head -n $BEFORE_MARKER $THE_FS > $THE_FST
egrep "^val" $THE_FSI >> $THE_FST
tail -n +$AFTER_MARKER $THE_FS >> $THE_FST
